src/cascader/__tests__/cascader.test.tsx
src/cascader/core/helper.ts

- [ ☑️] 日常 bug 修复
[#1881](https://github.com/Tencent/tdesign-react/issues/1881)

fix(cascader): value is zero can be selected

---

src/message/__tests__/message.test.jsx

- [☑️] 测试用例
[#1280](https://github.com/Tencent/tdesign-react/issues/1280)

test(message): add test for message

---

CHANGELOG.md
package.json

chore: publish 0.45.4

---

src/tree-select/TreeSelect.tsx
src/tree-select/defaultProps.ts
src/tree-select/tree-select.md
src/tree-select/type.ts
src/tree/Tree.tsx
src/tree/tree.md

Fix: tree-select empty text 显示异常 & onClear 后value 重置问题

---

src/_util/parseTNode.ts
src/dialog/DialogCard.tsx

fix: 修复 dialog footer 渲染丢失包裹块问题

---

site/test-coverage.js
site/vite.config.js
src/color-picker/__tests__/color-picker.test.tsx
src/menu/__tests__/menu.test.tsx
src/time-picker/__tests__/time-picker.test.tsx

test(menu): add menu tests

---

site/test-coverage.js
src/date-picker/__tests__/date-picker-panel.test.tsx
src/date-picker/__tests__/date-picker.test.tsx
src/date-picker/__tests__/date-range-picker-panel.test.tsx
src/date-picker/__tests__/date-range-picker.test.tsx
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/defaultProps.ts
src/date-picker/type.ts

feat: 提升datepicker 测试覆盖率

---

src/date-picker/__tests__/date-picker-panel.test.tsx
src/date-picker/__tests__/date-picker.test.tsx
src/date-picker/__tests__/date-range-picker-panel.test.tsx
src/date-picker/__tests__/date-range-picker.test.tsx

feat: 提升 date-picker 测试覆盖率

---

src/button/__tests__/__snapshots__/vitest-button.test.jsx.snap
src/loading/gradient.tsx
src/upload/__tests__/__snapshots__/vitest-upload.test.jsx.snap

- fix(Loading): 修复loading在部分windows设备中晃动的问题

fix(loading): fix loading render in some devices

---

src/dialog/hooks/useLockStyle.ts
src/drawer/hooks/useLockStyle.ts

fix: 修复在 next 中 document 报错问题

---

src/color-picker/components/panel/slider.tsx
src/color-picker/hooks/useStyles.ts

- [ ☑️] 日常 bug 修复
[#1906](https://github.com/Tencent/tdesign-react/issues/1906)
- fix(color-picker): slider 初始化 thumb 位置计算问题

fix(color-picker): slider 初始化 thumb 位置计算问题

---

src/form/__tests__/form.test.tsx

test(form): add test for form (#1280)

---

site/test-coverage.js
src/form/__tests__/form-list.test.tsx
src/form/__tests__/form.test.tsx

feat: 提升 form 测试覆盖率

---

CHANGELOG.md
package.json

feat: publish 0.45.6

---

site/docs/getting-started.md

feat: react 发布lts

---

CHANGELOG.md
package.json

chore: publish 1.0.0

---

site/src/App.jsx
site/src/utils.js

chore: fix site version display

---

src/radio/defaultProps.ts

- fix(Radio): 修复 radio disabled 默认值问题 

fix: 修复 radio disabled 默认值问题

---

src/select/base/Option.tsx
src/table/EditableCell.tsx

fix #1974
https://github.com/Tencent/tdesign-react/issues/1974
- fix(table): editable cell keep edit state

fix(table): editable cell keep edit state

---

src/form/FormList.tsx

fix(form): 修复 formList onValuesChange 获取不到最新数据问题

---

src/dialog/plugin.tsx

re #1997
#1997
- feat(dialog): plugin 调用支持自定义 visbile

feat(dialog): plugin 调用支持自定义 visbile

---

src/tree-select/TreeSelect.tsx

fix(tree): 修复子节点被折叠后被过滤问题

---

package.json
src/dialog/hooks/useLockStyle.ts
src/drawer/hooks/useLockStyle.ts
src/table/hooks/useFixed.ts

fix: 修复 drawer、dialog 滚动条检测问题

---

src/cascader/Cascader.tsx
src/select-input/useMultiple.tsx
src/select/base/Select.tsx
src/tree-select/TreeSelect.tsx

chore: optimize

---

src/input/Input.tsx
src/popup/hooks/useTrigger.tsx

fix: 修复input 异步渲染宽度计算问题

---

src/form/FormItem.tsx

fix: 修复校验信息实用错误缓存问题

---

src/list/ListItemMeta.tsx

feat(list): listItemMeta 支持 className、style 属性

---

src/drawer/hooks/useLockStyle.ts

fix: 修复 drawer 拖拽后页面出现滚动条问题

---

src/form/FormItem.tsx

- fix(Form): 移除 formItem 多余事件通知逻辑

fix: 移除 formItem 多余事件通知逻辑

---

CHANGELOG.md
package.json

chore: publish 1.0.2

---

site/src/utils.js

chore: 修复站点版本展示问题

---

src/date-picker/hooks/useRange.tsx
src/date-picker/hooks/useSingleValue.tsx

- fix(DatePicker): 修复月份为0时展示当前月份问题

fix: 修复月份为0时展示当前月份问题

---

src/upload/hooks/useUpload.ts

fix: https://github.com/Tencent/tdesign-react/issues/2033
- fix(upload): 修复 upload method 无效问题

修复 upload method 无效问题

---

src/message/Message.tsx
src/message/MessageComponent.tsx
src/message/__tests__/message.test.jsx

https://github.com/Tencent/tdesign-react/issues/1972
- feat(Message): 鼠标悬停时不自动关闭

feat(message): 支持鼠标悬停时不自动关闭

---

src/select/base/Select.tsx

- fix(Select): 修复多选全选初始值为空时选中报错的问题

fix(Select): checkall multiple type

---

src/dialog/Dialog.tsx

修复同名className合并异常导致高度被撑开
修复Dialog垂直居中异常
- fix(Dialog): 修复弹窗垂直居中问题

fix(Dialog): 弹窗垂直居中问题

---

CHANGELOG.md
package.json

chore: publish 1.0.3

---

src/timeline/index.ts

- fix(Timeline): 导出TimelineItem类型

fix(timeline): export TimelineItemProps(#2052)

---

src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/defaultProps.ts
src/date-picker/hooks/useRange.tsx
src/date-picker/hooks/useSingle.tsx
src/date-picker/type.ts

feat(datepicker): 支持 size 属性

---

src/color-picker/components/panel/format/inputs.tsx

fix(colorpicker): react format input 无法输入的问题

---

src/color-picker/components/panel/format/inputs.tsx

fix(colorpicker): color picker 输入框不能完全删除的问题

---

src/form/FormList.tsx

- fix(Form): 修复 formList 初始数据获取问题

fix: 修复 formList 初始数据获取问题

---

src/watermark/Watermark.tsx

- fix(watermark): fix document undefined in nextjs

fix(watermark): fix watermark document undefined in nextjs

---

src/color-picker/__tests__/color-picker.test.tsx
src/color-picker/components/panel/index.tsx

fix(color-picker): 修复颜色不能删除的问题

---

CHANGELOG.md
package.json

chore: publish 1.0.5

---

src/dialog/Dialog.tsx

- fix(Dialog): 修复 Dialog onOpen 事件调用时机问题

feat: 修复 onOpen 事件调用时机问题

---

src/button/Button.tsx

- feat(Button): 支持禁用态不触发 href 跳转逻辑

feat(`Button`): 支持禁用态不触发 href 跳转逻辑

---

src/notification/NotificationList.tsx

fix: 修复 notification 获取实例问题

---

CHANGELOG.md
package.json

chore: publish 1.1.0

---

src/popup/hooks/useTrigger.tsx

fix(popup): 修复右键展示浮层触发浏览器默认事件

---

src/breadcrumb/BreadcrumbItem.tsx
src/breadcrumb/BreadcrumbProps.ts
src/link/Link.tsx

fix: 修复React 类型问题

---

src/form/useInitialData.ts

fix(form): 修复初始数据设置问题

---

src/back-top/BackTop.tsx
src/input-number/useInputNumber.tsx

- fix(InputNumber): 修复输入小数以0结尾时的功能异常问题

fix(inputnumber): decimal end of 0 

---

src/tree-select/TreeSelect.tsx
src/tree-select/__tests__/vitest-tree-select.test.jsx

fix(tree-select): 修复过滤后无法展开问题

---

src/tree/useStore.ts

https://github.com/Tencent/tdesign-react/issues/2077
tree data 属性不受控导致不刷新子组件选中状态
- fix(tree): 修复 tree 组件 data 属性不受控问题

fix(tree): 处理 tree 组件 data 属性不受控问题 (#2077)

---

CHANGELOG.md
package.json

chore: publish 1.1.1

---

src/dialog/DialogCard.tsx

fix: 修复 dialog footer渲染 null 问题

---

src/dialog/Dialog.tsx

- fix(Dialog): 修复 Dialog 设置style width 不生效问题

fix: 修复 Dialog 设置style width 不生效问题

---

src/date-picker/base/Table.tsx

- feat(datepicker): 优化周选择器高亮判断逻辑性能问题

feat(datepicker): 优化周选择器高亮判断逻辑性能问题

---

src/_util/useDrag.ts

fix(color-picker): 修复 Frame 中无法拖拽饱和度和 slider 的问题

---

CHANGELOG.md
package.json

chore: publish 1.1.2

---

src/form/hooks/useInstance.tsx

- fix(Form): 修复主动 reset 不触发 onReset 逻辑

fix(form): 修复主动 reset 不触发 onReset 逻辑

---

src/collapse/Collapse.tsx

fix #2148
https://github.com/Tencent/tdesign-react/issues/2148
fix(collapse): fix props.value uncontrolled problem

fix(collapse): fix props.value uncontrolled problem

---

src/icon/_example/IconSelect.jsx
src/icon/icon.md

在用户群，有使用者反馈导入所有图标提示报错，经过排查发现因为 vite 的原生 module 加载方式不支持 cjs。现在改用入口导出的 esm 内容。
- docs(icon): 修复 manifest 统一入口导出 esm 模块，文档为及时更新的问题

docs(icon): 更新 manifest 引入路径文档

---

src/select/base/Select.tsx

- https://github.com/Tencent/tdesign-react/issues/2149
- fix(Select): 修复多选模式`size`属性未生效的问题

fix(select): size props is not working in multiple mode

---

site/docs/getting-started.md

docs: 修复文档重复问题

---

package.json

- feat: 主题生成器升级 `1.0` 版本，支持色彩智能推荐及尺寸调整，新增腾讯云皮肤

feat: upgrade tdesign theme generator v1

---

src/date-picker/DatePicker.tsx
src/date-picker/DatePickerPanel.tsx
src/date-picker/DateRangePicker.tsx
src/date-picker/DateRangePickerPanel.tsx
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/panel/RangePanel.tsx
src/date-picker/panel/SinglePanel.tsx
src/date-picker/type.ts

- feat(DatePicker): datepicker 支持 onPresetClick 事件

feat: datepicker 支持 onPresetClick 事件

---

src/form/FormList.tsx

fix: 修复 formList onValuesChange 事件问题

---

CHANGELOG.md
package.json

chore: publish 1.1.3

---

src/hooks/useResizeObserver.ts

fix: useResizeObserver ssr error

---

src/color-picker/__tests__/color-picker.test.tsx

- 由于 https://github.com/Tencent/tdesign-common/pull/1289 增加了对渐变色 RGB和HEX输入框直接输入的支持 所以和此前测试用例不同的是 点击swatches item相当于直接输入 会直接更新选中节点的颜色 所以需要更新测试用例

chore: update colorpicker test for support gradient modify by input

---

src/select/_example/panel.jsx
src/select/_example/virtual-scroll.jsx
src/select/base/PopupContent.tsx

- feat(Select): 支持panelTopContent在虚拟滚动等需要滚动下拉框场景的使用 具体使用方式请看示例

feat(Select): support use panelTopContent together with virtual scroll

---

CHANGELOG.md
package.json

chore: publish 1.1.4

---

src/tree-select/defaultProps.ts
src/tree-select/tree-select.en-US.md
src/tree-select/tree-select.md
src/tree-select/type.ts

feat(tree-select): add tree-select new api

---

src/select-input/useSingle.tsx

fix(select-input): 修复 loading 在 disabled 状态下隐藏问题

---

src/cascader/Cascader.tsx
src/cascader/cascader.en-US.md
src/cascader/cascader.md
src/cascader/defaultProps.ts
src/cascader/type.ts
src/common.ts

- feat(cascader): 支持 `suffix`、`suffixIcon`

feat(cascader): 支持 suffix、suffixIcon

---

CHANGELOG.md
package.json

chore: publish 1.1.5

---

src/affix/Affix.tsx

remove useDefaultProps
BREAKING CHANGE: 🧨 
✅ Closes: 

fix: 🐛 remove useDefaultProps

---

src/form/hooks/useWatch.ts

fix: 修复异步渲染使用 useWatch 报错问题

---

src/select/base/Select.tsx

- https://github.com/Tencent/tdesign-react/issues/2197
- fix(Select): 修复可创建重复 label 的选项的缺陷

fix(Select): create duplicated option with same label

---

CHANGELOG.md
package.json

chore: publish 1.1.6

---

CHANGELOG.md
package.json

chore: publish 1.1.7

---

src/collapse/Collapse.tsx
src/collapse/CollapsePanel.tsx

replace defaultProps with useDefaultProps

fix: 🐛 replace defaultProps with useDefaultProps

---

src/form/FormList.tsx

fix: 修 FormList 数据透传问题

---

src/time-picker/panel/TimePickerPanel.tsx

- https://github.com/Tencent/tdesign-vue/issues/2446
- feat(TimePicker): 没有选中值时不允许点击确认按钮

feat(timepicker): disable confirm button when value is undefined

---

src/swiper/Swiper.tsx

fix #2167
2167
- fix(swiper): navigation type support dots,dots-bar

fix(swiper): navigation type support dots,dots-bar

---

src/date-picker/DatePicker.tsx
src/date-picker/DateRangePicker.tsx
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/type.ts

- feat(datepicker): 支持 onConfirm 事件

feat(datepicker): 支持 onConfirm 事件

---

src/table/BaseTable.tsx
src/table/hooks/useColumnResize.tsx
src/table/table.en-US.md
src/table/table.md
src/table/type.ts

feat: 新增 onColumnResizeChange 事件

---

src/image-viewer/ImageViewerMini.tsx
src/image-viewer/ImageViewerModel.tsx

- fix(image-viewer): 修复触控板缩放操作异常问题

fix(image-viewer): 修复触控板缩放操作异常问题

---

src/tree-select/TreeSelect.tsx

- https://github.com/Tencent/tdesign-react/issues/2257
- fix(TreeSelect): 修复`keys`属性没有透传给Tree的问题

fix(treeSelect): 修复 keys 属性没有透传给Tree的问题

---

CHANGELOG.md
package.json

chore: publish 1.1.9

---

src/input-number/useInputNumber.tsx

- fix(InputNumber): 初始值为 undefined/null，且存在 decimalPlaces 时，不再进行小数点纠正

fix(InputNumber): 初始值为 undefined/null，且存在 decimalPlaces 时，不再进行小数点纠正 

---

src/table/hooks/useRowSelect.tsx

#2238
table组件设置expandOnRowClick为true时，点击整行报错

fix: issue#2238  table组件设置expandOnRowClick为true时，点击整行报错

---

src/auto-complete/OptionList.tsx

- [ x ] 日常 bug 修复
https://github.com/Tencent/tdesign-react/issues/2270
这里利用键盘的上下键去展示列表的高亮，但是输入也会触发，这里的newIndex就是undefined，需要加个可选链去清除报错。

fix: 修复控制台报错

---

.gitignore
src/select/base/Select.tsx
src/select/select.en-US.md
src/select/select.md
src/select/type.ts

-  #2271
- fix(Select): 修复`onBlur`方法回调参数异常的问题

fix(select): onBlur function data of the select component is wrong

---

CHANGELOG.md
package.json

chore: publish 1.1.10

---

src/table/BaseTable.tsx
src/table/EditableCell.tsx
src/table/THead.tsx
src/table/_example/data-sort.jsx
src/table/hooks/useSorter.tsx

https://github.com/Tencent/tdesign-react/issues/2126
https://github.com/Tencent/tdesign-react/issues/2219
- fix(Table): 可拖拽调整列宽场景，修复 `resizable=false` 无效问题，默认值为 false
- fix(Table): 本地数据排序场景，修复异步拉取数据时，取消排序数据会导致空列表问题
- fix(Table): 修复固定表格 + 固定列 + 虚拟滚动场景，表头不对齐问题，[issue#2126](https://github.com/Tencent/tdesign-react/issues/2126)
- fix(Table): 可编辑单元格/可编辑行场景，修复数据始终校验上一个值问题，调整为校验最新输入值，[issue#2219](https://github.com/Tencent/tdesign-react/issues/2219)
- docs(Table): 修复本地数据排序，多字段排序场景，示例代码缺失问题，[issue#1966](https://github.com/Tencent/tdesign-react/issues/1966)

[Table] fix some bugs

---

src/dropdown/_example/icon.tsx

https://github.com/Tencent/tdesign/issues/356

feat(dropdown): 新增带图标的下拉菜单示例

---

CHANGELOG.md
package.json

chore: publish 1.1.12

---

src/common.ts
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/type.ts

docs(date-picker): 文案更新

---

src/tag/Tag.tsx

https://github.com/Tencent/tdesign-react/issues/2333
- fix(Tag): 修复 Tag children 为数字 0 时的渲染异常

fix(tag): 修复 Tag children 为数字 0 时的渲染异常

---

src/input/Input.tsx

- fix(Input): 修复 `limitNumber` 部分在 `disabled` 状态下的样式问题

fix(Input): disabled limitNumber style

---

src/select-input/SelectInput.tsx
src/select-input/useMultiple.tsx

- fix(TagInput): 修复前置图标的样式缺陷
- fix(SelectInput): 修复失焦时未清空输入内容的缺陷

fix(taginput): clear input value when tag input on blur

---

package.json

chore: fix ci lint

---

site/plugin-tdoc/transforms.js

chore:  修复timeline示例未正常渲染展示的问题

---

src/radio/useKeyboard.ts
src/tag-input/useTagScroll.ts

- fix: 修复 `Radio` 和 `TagInput` 服务端渲染的异常问题

fix: 修复渲染异常情况下js报错问题

---

CHANGELOG.md
package.json

chore: publish 1.1.14

---

src/date-picker/DateRangePicker.tsx
src/date-picker/hooks/useRange.tsx

- feat(DatePicker): 优化关闭浮层后重置默认选中区域

feat(datepicker): 优化关闭浮层后重置默认选中区域

---

src/grid/grid.en-US.md
src/grid/grid.md
src/grid/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/172

docs(Grid): row Props.gutterTS类型补充lg,xl,xxl

---

CHANGELOG.md
package.json

chore: publish 1.1.15

---

src/config-provider/ConfigContext.tsx
src/config-provider/ConfigProvider.tsx

fix: optimize configProvider type writting style

---

src/guide/Guide.tsx

- fix(Guide): 修复设置step为 -1 时需要隐藏组件的功能

fix(Guide): hide when current step is -1

---

src/list/ListItemMeta.tsx

https://github.com/Tencent/tdesign-react/issues/2394
- fix(list): 修复ListItemMeta组件description传递自定义元素

fix(list): behavior match description type

---

CHANGELOG.md
package.json

chore: release 1.1.17

---

src/cascader/core/helper.ts

https://github.com/Tencent/tdesign-react/issues/2404
- fix(Cascader):  传入的 value 不在 options中时会直接报错

fix(cascader): 传入的 value 不在 options中时会直接报错

---

src/menu/MenuItem.tsx

#2423 
- fix(menu): 修复同一个MenuItem多次触发onChange的问题

fix(menu): The same MenuItem triggers onChange multiple times

---

src/drawer/Drawer.tsx

https://github.com/Tencent/tdesign-react/issues/2408
- fix(Drawer): 抽屉组件在 visible 默认为 true 时，无法正常显示

fix(drawer): 抽屉组件在 visible 默认为 true 时，无法正常显示

---

src/tree/Tree.tsx

fix: 修复 tree 透传className 失效问题

---

CHANGELOG.md
package.json

chore: publish 1.2.0

---

src/menu/MenuItem.tsx
src/menu/menu.md
src/menu/type.ts

fix #2621
https://github.com/Tencent/tdesign-vue/issues/2621

feat(menu-item): onClick事件增加value返回值

---

src/common.ts
src/form/FormItem.tsx
src/form/form.en-US.md
src/form/form.md
src/form/type.ts

feat(form): formItem 新增 valueFormat 函数支持格式化数据

---

src/popconfirm/Popcontent.tsx
src/popconfirm/type.ts

- fix #2337 
无
- fix(popconfirm): invalid className and style props

fix(popconfirm): invalid className and style props

---

CHANGELOG.md
package.json

chore: publish 1.2.1

---

src/input/Input.tsx

#2437 
1.修復沒監聽拼音輸入，設置input寬度
- fix(taginput): fix when entering Chinese, it will be blocked by the previous label

fix(tag-input): fix input value was blocked when enter Chinese

---

src/tree/__tests__/tree.test.tsx

chore: update common

---

src/table/hooks/useTreeDataExpand.ts

fix: 修复 usePrevious 报错

---

CHANGELOG.md
package.json

chore: publish 1.2.3

---

tsconfig.build.json

chore: remove alias from build config

---

src/breadcrumb/type.ts

fix: fix type error

---

src/popup/hooks/useTrigger.tsx

#2473 
before:
after:
Slider init value set to 0,lead to var shouldToggle init value false,As a result, triggerRef cannot be obtained.
Slider 初始化值设置为 0,导致 變量 shouldToggle 初始值為false,導致獲取不到triggerRef.
解決方案：
判斷content初始值是否為0，是的話設為true。
- fix(Slider): 修复初始值为0 时，label位置错误的缺陷

fix(Slider): init value is set to 0, label positioning error

---

src/table/hooks/useTreeData.tsx
src/table/hooks/useTreeDataExpand.ts

fix(Table): 树形结构，修复 `tree.defaultExpandAll` 失效问题

fix(table): tree.defaultExpandAll invalid

---

.github/workflows/auto-release.yml

chore: fix auto release extra space

---

src/config-provider/config-provider.en-US.md
src/config-provider/config-provider.md
src/config-provider/type.ts
src/steps/StepItem.tsx

#2425 
全局配置添加步骤条的已完成图标自定义
- feat(steps): 全局配置添加步骤条的已完成图标自定义

feat(steps): config-provider add steps checkIcon

---

src/config-provider/ConfigContext.tsx
src/config-provider/ConfigProvider.tsx

- fix(GlobalConfig): 修复切换多语言失效的问题

fix(globalconfig): fix toggle global language

---

src/table/hooks/useEditableRow.ts

- fix(Table): 可编辑表格，修复多个可编辑表格同时存在时，校验互相影响问题

fix(table): multiple editable table

---

src/tag-input/useTagList.tsx

- fix(TagInput): 修复折叠展示选项尺寸大小问题

fix(TagInput): fix collapse item size

---

src/form/form.en-US.md
src/form/form.md
src/form/type.ts

- https://github.com/Tencent/tdesign-react/issues/2475
- feat(Form): trigger新增`submit`选项

feat: add trigger type

---

CHANGELOG.md
package.json

chore: publish 1.2.5

---

src/tree/Tree.tsx
src/tree/_example/vscroll.jsx

- feat(Tree): Tree支持通过key匹配单一value指定滚动到特定位置，具体使用方式请参考示例代码

feat(tree): scroll to support key match value

---

src/cascader/core/effect.ts

fix #2526
- fix(Cascader): hover 没有子节点数据的父节点时未更新子节点

fix(cascader): the child nodes are not updated when hovering over a node

---

CHANGELOG.md
src/form/hooks/useInstance.tsx

fix: 修复 formList 嵌套数据获取异常

---

src/date-picker/panel/PanelContent.tsx

- https://github.com/Tencent/tdesign-react/issues/2525
- fix(Datepicker): 修复 `datepicker` 切换月份失效问题

fix: 修复 datepicker 切换月份失效问题

---

CHANGELOG.md
package.json

chore: publish 1.2.6

---

src/locale/it_IT.ts
src/locale/ru_RU.ts
src/locale/zh_TW.ts

close #2541 
缺失it_IT、ru_RU、zh_TW 的语言环境
- fix(locale): 添加缺失it_IT、ru_RU、zh_TW 的语言环境

fix(locale): fix missing it_IT、ru_RU、zh_TW locale

---

src/cascader/core/effect.ts

- fix(Cascader): `change` 事件中 `source` 异常问题

fix(cascader): effect source abnormal

---

src/tree/type.ts

hotfix: recover tree defaultExpanded type

---

CHANGELOG.md
package.json

chore: publish 1.3.0

---

src/form/FormItem.tsx

fix: 修复 setFields 触发 onValuesChange 导致的死循环

---

src/tabs/TabNav.tsx

- #2586 
重复点击激活的选项卡，也会触发 onChange 事件，判断不相同时才触发onChange。
- fix(tabs): 修复重复点击激活的选项卡，也会触发 onChange 事件。

fix(tabs): fix tabs click actived tab , onchange  trigger many a time

---

src/upload/hooks/useDrag.ts

- feat(Upload): 拖拽上传文件场景，即使文件类型错误，也会触发 `drop` 事件（之前不会）

feat(upload): trigger drop event even if file type is not match

---

src/hooks/useElementLazyRender.ts

- fix(Table): 修复 `lazyLoad` 懒加载效果

fix: useElementLazyRender default value

---

.github/ISSUE_TEMPLATE/bug-report.zh-CN.yml

无
本项目是 React 版本的，我想我们应该推荐一个默认的 react 版本（（（

chore(github): update github issue tempate default framework value

---

src/statistic/statistic.en-US.md
src/statistic/statistic.md
src/statistic/type.ts

docs(statistic): update

---

src/statistic/Statistic.tsx

删除多余的控制台日志
- fix(Statistic): 删除多余的控制台日志

fix(statistic): remove redundant console log

---

src/pagination/Pagination.tsx

- fix(Pagination): 修复当 `total` 为 0 并且 `pageSize` 改变时， `current` 值为 0 的问题

fix(pagination): when total is 0 and pageSize change, current value is 0

---

CONTRIBUTING.md
README-zh_CN.md
README.md

chore: optimize docs

---

src/image-viewer/ImageViewer.tsx
src/image-viewer/ImageViewerMini.tsx
src/image-viewer/ImageViewerModal.tsx
src/image-viewer/__tests__/image-viewer.test.tsx
src/image-viewer/hooks/useIndex.ts

- refactor(ImageViewer): 修改ImageViewerModel组件名称

refactor(ImageViewer): rename ImageViewerModel to ImageViewerModal

---

src/radio/useKeyboard.ts

feat(radio): 空格键也可触发选中

---

src/dropdown/DropdownItem.tsx

Fix https://github.com/Tencent/tdesign-vue-next/issues/3693
- fix(DropdownItem): 处理禁用状态可点击的问题

fix(dropdown-item): the disabled effect is unexpected

---

src/dropdown/DropdownItem.tsx

- fix(dropdown): 修复`DropdownItem`子组件遗漏`divider`类型的缺陷

fix(dropdown): dropdown item missing divider props declaration

---

src/date-picker/hooks/useRange.tsx
src/date-picker/hooks/useSingle.tsx

#2651 
- fix(DatePicker): 修复禁用状态下点击组件边缘仍能显示`Pannel`

fix(DatePicker): fix error disabled

---

PUBLISH.md

docs: add PUBLISH.md

---

src/slider/Slider.tsx

fix: 🐛 replace defaultProps with useDefaultProp

---

src/hooks/useVirtualScroll.ts
src/table/hooks/useTreeDataExpand.ts

- fix(Table): 修复虚拟滚动场景，树节点无法展开问题

fix(table): virtual scroll table can not expand tree nodes

---

src/table/_example/tree-select.jsx
src/table/hooks/useTreeData.tsx
src/table/hooks/useTreeDataExpand.ts

- fix(Table): 修复 EnhancedTable 树节点无法正常展开问题

fix(table): enhanced tree table can not expand with expected

---

src/select/base/Select.tsx

- fix(Select): 修复`InputChange`事件在blur时trigger异常的问题

fix(Select): fix input change trigger

---

src/popup/hooks/useTrigger.tsx

- fix(Popup): 修复 `disabled` 属性未生效的缺陷

fix(Popup): fix disabled API doesn't work

---

src/table/hooks/useTreeDataExpand.ts

- fix(table):  异步获取最新的树形结构数据时，优先使用window.requestAnimationFrame函数，以防闪屏

fix(table): change setTimeout to requestAnimationFrame when get tree data

---

.github/CODEOWNERS

chore: update reviewer list

---

package.json

package.json文件添加npm run init 命令，方便用户快速初始化仓库来拉取tdesign-common
- core: package.json文件添加npm run init 命令，方便用户快速初始化仓库来拉取tdesign-common

chore(package.json): package.json add init command

---

CONTRIBUTING.md

CONTRIBUTING.md更新为使用npm run init初始化拉取tdesign-common仓库
- core: CONTRIBUTING.md更新为使用npm run init初始化拉取tdesign-common仓库

chore(contributing): contributing docs update

---

src/cascader/components/Item.tsx
src/cascader/core/effect.ts

- #2667
`before:`
https://github.com/Tencent/tdesign-react/assets/65376724/347e1528-301d-45e0-8355-c5b5434b3488
https://github.com/Tencent/tdesign-react/assets/65376724/c5401be9-cffc-46c8-8eca-1a5b8fd06e78
`after:`
https://github.com/Tencent/tdesign-react/assets/65376724/3a410fd4-5e13-469e-b9ea-bea6a8d5390f
https://github.com/Tencent/tdesign-react/assets/65376724/14abe798-357b-42ac-bfa0-2367451379d2
- fix(Cascader): 修复Cascader组件在 filter 之后进行选择操作和清除内容存在异常bug

fix(cascader): fix Cascader add filter select the bug

---

src/table/__tests__/__snapshots__/pagination.test.tsx.snap

- https://github.com/Tencent/tdesign-common/pull/1687
- fix(Pagination): 将总数单位 `项` 改为 `条` , 保持内容一致性 

fix(pagination): fix pagination text

---

package.json

chore: release 1.4.2

---

.vscode/settings.json
PUBLISH.md

更新PUBLISH.md的描述
- chore: 更新PUBLISH.md的描述

chore: Update PUBLISH.md

---

src/auto-complete/AutoComplete.tsx
src/auto-complete/OptionList.tsx

- #2298
- fix(AutoComplete): 修复`ActiveIndex=-1`没匹配时，回车会报错的问题

fix(auto-complete): fix: error when pressing enter

---

CHANGELOG.md
package.json

chore: release 1.4.3

---

src/upload/interface.ts

- #2681 
- fix(Upload): 修复Upload的 `uploadFilePercent` 类型未定义

fix(upload): type is undefined

---

site/test-coverage.js

chore: update test coverage

---

README-zh_CN.md
README.md

加上了 `yarn` 和 `pnpm` 的命令行，然后把入口文件的写法从 `React 17` 更新到 `React 18` 了：

docs: update README.md

---

src/form/hooks/useInstance.tsx

- fix(Table): 修复`Modal`里的`Form`表单，使用`shouldUpdate`卸载有时无法找到表单的方法。

fix(Table): 修复Modal里的Form表单，使用 shouldUpdate卸载有时无法找到表单的方法

---

src/select/base/Select.tsx

- #2720
添加判断多选时不触发滚动
- fix(Select): 修复`Select`多选状态下选中内容滚动的问题。

fix(Select): fix Select multiple selected trigger scroll of bug

---

src/transfer/Transfer.tsx

- fix(Transfer): 修复`disabled` API功能异常的问题
- feat(Transfer): 支持 `direction` API

fix(Transfer): fix disabled api

---

src/cascader/components/Item.tsx
src/tabs/TabNav.tsx
src/tabs/defaultProps.ts
src/tabs/type.ts
test/snap/ssr.test.jsx
test/utils/index.jsx

- https://github.com/Tencent/tdesign-common/pull/1719
- https://github.com/Tencent/tdesign-common/pull/1718
- https://github.com/Tencent/tdesign-common/pull/1717
- fix(Form): 修复计算`^`字符异常的问题
- feat(Tabs): 新增支持`action` API 自定义右侧区域
- fix(Loading): 修复未设置 `z-index` 默认值的问题 @betavs 

feat(Tabs): support action API

---

src/tree-select/TreeSelect.tsx
src/tree-select/_example/filterable.jsx

- fix(TreeSelect): 修复`onEnter`事件不触发的问题

feat(TreeSelect): add onEnter api

---

CHANGELOG.md
package.json

chore: release 1.5.1

---

src/grid/Row.tsx

#2733
- fix(Grid): 尺寸计算错误，宽度兼容异常

fix(grid): css variable not parseFloat

---

script/init-component/config.js
script/init-component/tpl/api.md.tpl
script/init-component/tpl/component.tsx.tpl
script/init-component/tpl/readme.md.tpl

chore: update init component script

---

src/guide/Guide.tsx
src/guide/__tests__/__snapshots__/vitest-guide.test.jsx.snap

自定义 content 功能失效
- fix(Guide): 修复`Guide`自定义内容功能失效

fix(guide): custom content

---

src/space/Space.tsx

- fix(Space): `Space` replace `defaultProps` with `useDefaultProp`

fix: 🐛 replace defaultProps with useDefaultProp 

---

src/select/base/PopupContent.tsx
src/select/hooks/usePanelVirtualScroll.ts

- https://stackblitz.com/edit/react-w88doo-gshi3k?file=src%2Fdemo.jsx
- fix(Select): 修复使用`size` API时，虚拟滚动的功能异常问题

fix(Select): fix virtual scroll abnormal behavior used with size

---

src/hooks/useDefaultProps.ts

- chore: `useDefaultProps` update comment link

chore: update comment link

---

src/timeline/useAlign.ts

- chore: `TimeLine` add `type`

chore: add type

---

src/tag/index.ts

- chore: `Tag` rm useless `defaultProps`

chore: rm useless defaultProps

---

src/table/BaseTable.tsx
src/table/Cell.tsx
src/table/EditableCell.tsx
src/table/EnhancedTable.tsx
src/table/PrimaryTable.tsx
src/table/TBody.tsx
src/table/TFoot.tsx
src/table/THead.tsx
src/table/hooks/useColumnResize.tsx
src/table/utils.ts

chore: type hardening

---

src/table/hooks/useFixed.ts

- 删除多余的`console.log`
- fix(Table): 删除多余的`console.log`

fix(Table): rm redundant console

---

CHANGELOG.md
package.json

chore: release 1.5.2

---

src/common/__tests__/portal.test.tsx

添加`Portal`测试用例
- test(Portal): 添加`Portal`测试用例

test(Portal): add Portal test

---

src/list/__tests__/list.test.tsx

test(list): complete list test

---

src/alert/Alert.tsx
src/alert/__tests__/alert.test.tsx

完善 `Alert` 测试，优化代码
- fix(Alert): 完善 `Alert` 测试,优化代码

fix(alert): fix bug and complete test

---

src/breadcrumb/BreadcrumbItem.tsx
src/breadcrumb/breadcrumb.en-US.md
src/breadcrumb/breadcrumb.md
src/breadcrumb/type.ts

n
- #2340
`BreadcrumbItem` support `onClick` event
- feat(Breadcrumb): `BreadcrumbItem` 支持 `onClick` 事件

feat(breadcrumb): breadcrumb item support click event

---

README-zh_CN.md
README.md
package.json

- chore: 升级`site-components` 支持分技术栈入群
- chore: 更新小程序二维码

chore: update group code

---

src/date-picker/DatePicker.tsx

- https://github.com/Tencent/tdesign-vue/issues/3068
- formatDate 方法需要Date对象来计算，部分场景下，value.value为普通字符串或时间戳，无法得出正确的结果，需统一转为Date再进行计算
- 相关PR https://github.com/Tencent/tdesign-common/pull/1746
- fix(DatePicker): 修复 `format` 与 `valueType` 不一致的场景下计算错误的问题

fix(DatePicker): value display with special format

---

site/test-coverage.js

- chore: update coverage badge

chore: update coverage badge

---

CHANGELOG.md
package.json

chore: release 1.5.3

---

src/image-viewer/ImageViewer.tsx
src/image-viewer/ImageViewerMini.tsx
src/image-viewer/ImageViewerModal.tsx
src/image-viewer/__tests__/image-viewer.test.tsx
src/image-viewer/_example/base.jsx
src/image-viewer/image-viewer.en-US.md
src/image-viewer/image-viewer.md
src/image-viewer/type.ts

- https://github.com/Tencent/tdesign-react/issues/2810
- feat(ImageViewer): 新增`imageReferrerpolicy` API，支持配合Image组件的需要配置Referrerpolicy的场景
- chore: 移除冗余的测试的dataset

feat(ImageViewer): add imageReferrerpolicy API

---

CHANGELOG.md
package.json

chore: release 1.5.4

---

src/image-viewer/ImageViewerModal.tsx

- fix(ImageViewer): 修复 `imageReferrerpolicy` 没有对顶部缩略图生效的问题

fix(imageviewer): fix imageReferrerpolicy typo and do not effect header

---

CHANGELOG.md
package.json

chore: release 1.5.5

---

src/descriptions/Descriptions.tsx

`props` lock `className` and `style` 
- fix(Descriptions): 修复 `props` 缺少 `className` 和 `style` 属性

fix(Descriptions): fix descriptions typo

---

src/common/__tests__/portal.test.tsx

删除`Portal`多余的测试用例，之前觉得可能会在`Portal`里添加lazy，现在不需要了
- test(Portal): 删除`Portal`多余的测试用例

test(portal): delete the excess test usage of the portal

---

src/input/Input.tsx
src/range-input/RangeInput.tsx

- #2320
fix in `React16` version,stopPropagation fail
- fix(Input): 修复在React16版本，阻止冒泡失败

fix(input): fix input stopPropagation of React16

---

src/date-picker/DatePicker.tsx

- fix(DatePicker): 修复`1.5.3`版本之后处理Date类型和周选择器的异常

fix(datepicker): fix datepicker week parse error

---

src/guide/Guide.tsx

`SSR`下`document`是获取不到的，目前修复找不到`document`下直接返回`null`
- fix(Guide): `SSR`下`document`是获取不到的，目前修复找不到`document`下直接返回`null`

fix(Guide): fix ssr document undefined

---

site/docs/getting-started.en-US.md
site/docs/getting-started.md

docs: optimize docs

---

src/table/hooks/useTreeDataExpand.ts

- #2836
在`effect`异步里执行获取数据时和更新数据，可能会导致一些bug，估删除`asyncCall`事件
- fix(Table): 在`effect`异步里执行获取数据时和更新数据，可能会导致一些bug

fix(Table): fix table init expand fail

---

.github/workflows/pr-spelling.template.yml
.github/workflows/typos-config.toml
src/pagination/Pagination.tsx
src/pagination/hooks/usePageNumber.tsx
src/pagination/hooks/useTotal.tsx

ci(typos): enable check filename

---

src/date-picker/DateRangePicker.tsx

Before
https://github.com/Tencent/tdesign-react/assets/26377630/215b0431-6c43-4e5d-82d8-a93d61714c58
After
https://github.com/Tencent/tdesign-react/assets/26377630/1c3a3c86-6866-4159-a309-2fdbd701dd9e
- fix(DatePicker): 修复日期选择器中月份选择回跳初始状态的异常

fix(DatePicker): fix month change

---

src/drawer/defaultProps.ts

- fix(Drawer): 修复`1.6.0` closeBtn 属性默认值丢失的问题

fix(Drawer): fix closeBtn default value

---

src/dropdown/Dropdown.tsx

- https://github.com/Tencent/tdesign-react/issues/2859
- fix(Dropdown): 修复选项长度为空仍展示浮层的问题

fix(dropdown): disable overlay visible when options length is 0

---

src/dropdown/Dropdown.tsx

- #2859
优化`Dropdown`的`children`透传`disabled`
- fix(Dropdown): 优化`Dropdown`的`children`透传`disabled`

fix(dropdown): fix Dropdown children Penetrate disabled

---

src/select-input/useOverlayInnerStyle.ts

- https://github.com/Tencent/tdesign-react/issues/2855
- fix(SelectInput): 修复非受控属性`defaultPopupVisible`不生效的问题

fix(SelectInput): fix uncontrolled popup visible

---

src/upload/_usage/props.json

- https://github.com/Tencent/tdesign-react/issues/2852
- usage demo 的 method enum values 亦需修改
- docs(upload): use options/OPTIONS in method values in demo

docs(upload): use options/OPTIONS in method values in demo

---

src/tabs/tabs.md

docs(Tabs): update docs

---

src/checkbox/checkbox.md
src/checkbox/type.ts
src/radio/radio.md
src/radio/type.ts
src/select/hooks/usePanelVirtualScroll.ts
src/table/BaseTable.tsx

chore: fix docs

---

src/select-input/_example/collapsed-items.jsx
src/select-input/select-input.en-US.md
src/select-input/select-input.md
src/select-input/type.ts
src/select-input/useMultiple.tsx
src/select-input/useSingle.tsx
src/tag-input/tag-input.en-US.md
src/tag-input/tag-input.md
src/tag-input/type.ts

`SelectInput` support `size`
- feat(SelectInput): `SelectInput` 支持 `size` 属性
- docs(TagInput): 补充`size`属性相关文档

feat(selct-input): support size

---

src/table/hooks/useRowSelect.tsx

Reverts Tencent/tdesign-react#2898

Revert "fix(Table): fix error occur when table is unmounted"

---

src/table/hooks/useRowSelect.tsx

使用动画路由切换页面时会先自动卸载表格数据，卸载时会触发 canSelectedRows，导致filter函数为 null 报错
- fix(Table): 修复卸载表格时数据为空导致报错的异常

fix(Table): fix error occur when table is unmounted 

---

src/select/base/Select.tsx
src/select/hooks/useOptions.ts

- https://github.com/Tencent/tdesign-react/issues/2895
- fix(Select): 修复`creatable`功能异常问题
- fix(Select): 修复`reserveKeyword`配合`Option Children`用法的异常问题

fix(Select): fix reserveKeyword render with Option children

---

src/avatar/Avatar.tsx
src/avatar/avatar.en-US.md
src/avatar/avatar.md
src/avatar/type.ts

无
为头像组件添加更多鼠标事件
- feat(avatar): 添加更多鼠标事件

feat(avatar): more events

---

src/menu/SubMenu.tsx

- fix(Menu): 修复二级及以下 `SubMenu`没有处理classname的缺陷

fix(Menu): fix submenu classname

---

src/upload/hooks/useUpload.ts

原来的上传成功判断了`autoUpload`为true才更新`uploadValue`,因该手动上传或者自动上传都应触发`setUploadValue`
- fix(Upload): 修复手动上传的bug

fix(upload): fix manual upload

---

CHANGELOG.md
package.json

chore: release 1.7.3

---

src/menu/SubMenu.tsx
src/select/base/Option.tsx

- fix(Select): 修复半选状态的全选选项展示样式问题

fix(Select): fix indeterminate status style

---

package.json

chore: upgrade site components version

---

.github/CODEOWNERS

chore: add ZWkang to code owners

---

src/checkbox/CheckboxGroup.tsx

#2923
- fix(checkbox): 受控状态无法被 onChange 回调中正确消费

fix(checkbox): checked set state is not last

---

src/hooks/useEventCallback.ts

feat(hooks): useEventCallback

---

CHANGELOG.md
package.json

release 1.7.4
- release: `1.7.4`

release: 1.7.4

---

src/input/input.en-US.md
src/input/input.md
src/input/type.ts

- fix(input): 补充 spellCheck 类型

feat(input): spellcheck type

---

src/tabs/TabNav.tsx

详见：[498](https://github.com/Tencent/tdesign/issues/498)

feat(tabs): supports scrolling operations via wheel or touchpad

---

src/input/input.en-US.md
src/input/input.md
src/input/type.ts

Adjust specllcheck order

---

src/table/hooks/usePagination.tsx

- #2957
fix `usePagination` the `pagination` dynamic change,not change `isPagination`
- fix(Table): 修复 `usePagination` 中 `pagination` 动态变化，不改变 `isPagination`

fix(Table): fix usePagination the isPagination issue

---

site/plugin-tdoc/transforms.js
src/image-viewer/_example/svg.tsx

chore: fix demo render

---

src/form/_example/validate-complicated-data.tsx

chore: hotfix demo

---

.vscode/settings.json

`vscode file nesting config`
- chore: `vscode` 文件嵌套配置

chore: vscode file nesting config

---

site/src/components/Demo.jsx

chore: fix single demo edit path

---

src/drawer/Drawer.tsx
src/drawer/drawer.en-US.md
src/drawer/drawer.md
src/drawer/hooks/useDrag.ts
src/drawer/type.ts

- fix(Drawer): 实现 onSizeDragEnd 参数

fix(Drawer): implement `onSizeDragEnd` prop

---

site/src/components/codesandbox/index.jsx
site/src/components/stackblitz/index.jsx

chore: fix sandbox code type

---

.vscode/settings.json

- chore: fix vscode file nesting config

chore:fix vscode config

---

src/tooltip/tooltip.en-US.md
src/tooltip/tooltip.md

- #2983 
- docs(Tooltip): add FAQ

docs(Tooltip): add FAQ

---

src/table/hooks/useColumnResize.tsx
src/time-picker/panel/SinglePanel.tsx

- fix(Table): 修复只存在一列可拖拽的表格缩小时的样式异常问题
- fix(Table): 修复部分场景下向前缩放时的报错的问题

fix(Table): fix resizable column bug

---

src/image-viewer/hooks/useList.ts

- perf(ImageViewer): optimization `useList`

perf(ImageViewer): optimize useList

---

src/config-provider/config-provider.en-US.md
src/config-provider/config-provider.md
src/config-provider/type.ts
src/dialog/Dialog.tsx
src/hooks/useAttach.ts
src/image-viewer/ImageViewer.tsx
src/image-viewer/defaultProps.ts
src/popup/Popup.tsx
src/popup/defaultProps.ts

- https://github.com/Tencent/tdesign-vue/issues/3167
- feat(ConfigProvider): 新增 `attach` API， 支持全局配置attach或全局配置部分组件的attach

feat(ConfigProvider): support global attach API

---

src/upload/upload.tsx

- fix(Upload): 修复部分图标不支持全局替换的问题

fix(Upload): fix global icon replacement

---

test/snap/csr.test.jsx

移除多余重复的节点，使用container来生成快照，减小test/snap/__snapshots__/csr.test.jsx.snap文件大小

chore: csr snapshot

---

src/timeline/timeline.md

docs(Timeline): fix typo

---

src/hooks/useDefaultProps.ts

chore: update comment

---

script/generate-usage/config.js
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/defaultProps.ts
src/date-picker/hooks/useRange.tsx
src/date-picker/type.ts
src/range-input/RangeInput.tsx
src/range-input/_usage/index.jsx
src/range-input/_usage/props.json
src/range-input/defaultProps.ts
src/range-input/range-input.en-US.md
src/range-input/range-input.md
src/range-input/type.ts
src/time-picker/TimeRangePicker.tsx
src/time-picker/_usage/time-picker-props.json
src/time-picker/_usage/time-range-picker-props.json
src/time-picker/defaultProps.ts
src/time-picker/time-picker.en-US.md
src/time-picker/time-picker.md
src/time-picker/type.ts

- https://github.com/Tencent/tdesign-vue-next/pull/4442
- feat(borderless): `RangeInput` `DateRangePicker`  `TimeRangePicker` 支持无边框模式
- docs(RangeInput): 增加`liveDemo`

feat(range-input): support borderless mode

---

.github/workflows/pr-comment-ci.yml

chore(ci): pr branch duplicate name

---

src/common.ts
src/descriptions/Descriptions.tsx
src/descriptions/Row.tsx

- https://github.com/Tencent/tdesign-vue-next/pull/3939
- feat(Description): layout 类型定义调整为字符串多类型

feat(descriptions): make layout type to be multiple type

---

src/tabs/_example/drag-sort.tsx

- docs(Tabs): 修复拖拽的事件传递，不要传防抖和节流，这会导致内部 `draggingIndex` 错乱

docs(tabs): fix usage example

---

src/dropdown/DropdownItem.tsx

- https://stackblitz.com/edit/react-cxy4xy-dz5dxn?file=src%2Fdemo.tsx
由于`pointer-events`的设置，导致组件内渲染的内容的事件响应也丢失，如内部若使用tooltip，会导致tooltip的效果丢失。
所以移除此配置，针对dropdownitem本身的动画的阻塞改为代码逻辑内实现
期望效果
- 关联PR https://github.com/Tencent/tdesign-common/pull/1853
- fix(Dropdown): 修复`DropdownItem`的禁用状态影响子组件本身响应行为的缺陷

fix(dropdown): fix item disabled status effects content behavior

---

src/button/_usage/props.json
src/upload/_example/image.tsx

- https://github.com/Tencent/tdesign-react/issues/3004
- https://github.com/Tencent/tdesign-vue-next/issues/4449
- docs: 优化`Button`和`Upload`的文档展示和调整问题

chore: update demo

---

src/date-picker/_example/date-presets-alt.tsx

- docs(DatePicker): 修复presets示例代码错误

chore: fix datepicker presets demo

---

CHANGELOG.md
package.json

chore: release 1.8.0

---

src/tag/Tag.tsx
src/tag/defaultProps.ts
src/tag/tag.en-US.md
src/tag/tag.md
src/tag/type.ts

title现在时默认显示children || content，hover时，有部分用户不需要显示title,所以加上title api让用户自己选择是否显示
- feat(Tag): 支持`title` api

feat(tag): add title api

---

src/time-picker/panel/SinglePanel.tsx

- https://github.com/Tencent/tdesign-vue/pull/3280
- https://github.com/Tencent/tdesign-common/pull/1906
- fix(TimePicker): 修复format 仅支持 HH:mm:ss 格式的问题

fix: resolve TIME_FORMAT RegExp

---

src/hooks/useMutationObserver.ts

optimization `useMutationObserver`
- perf(useMutationObserver): 优化 `useMutationObserver`

perf(useMutationobserver): optimiza performance

---

src/tag/Tag.tsx
src/tag/__tests__/vitest-tag.test.jsx
src/tag/tag.en-US.md
src/tag/tag.md

- https://github.com/TDesignOteam/tdesign-api/pull/407

test(tag): add title & color test case

---

src/statistic/Statistic.tsx

- https://github.com/Tencent/tdesign-react/issues/3088
- fix(Statistic):  修复`Statistic`组件 `classname` 和 `style` 未透传功能异常的问题

fix(statistic): custom className & style  not working

---

src/rate/Rate.tsx

refactor(Rate): delete unnecessary code

---

src/hooks/useControlled.ts

- refactor(hooks): correct ts type spell error

refactor(hooks): correct ts type spell error

---

src/cascader/Cascader.tsx
src/cascader/__tests__/cascader.test.tsx
src/cascader/cascader.en-US.md
src/cascader/cascader.md
src/cascader/type.ts

cascader support panel content
- feat(Cascader): 支持面板顶部和底部内容

feat(Cascader): support panel content

---

src/menu/SubMenu.tsx

- fix(menu): 修复二级菜单展开收起状态没有关联右侧箭头变化的问题

fix(menu): fix submenu arrow rotate status

---

src/tree-select/TreeSelect.tsx
src/tree/TreeItem.tsx

TreeSelect mutual logic optimiza
- fix(TreeSelect): 修改多选状态下默认点击父节点选项的行为为选中，如果需要点击展开，请配置`treeProps.expandOnClickNode`

fix(TreeSelect): fix tree-select mutual logic

---

src/color-picker/components/panel/index.tsx

fix(colorpicker): fix re-render

---

CHANGELOG.md
package.json

Release 1.9.1
- chore: release 1.9.1

chore: release 1.9.1

---

site/docs/getting-started.en-US.md
site/docs/getting-started.md

- docs: update usage docs for nextjs

docs: update usage docs for nextjs

---

src/time-picker/TimeRangePicker.tsx
src/time-picker/defaultProps.ts
src/time-picker/time-picker.en-US.md
src/time-picker/time-picker.md
src/time-picker/type.ts

- https://github.com/Tencent/tdesign-vue/issues/3355
- feat(TimePicker): 新增 `autoSwap` API，支持`1.9.0` 版本之后仍可以保持选定的左右侧时间大小顺序

feat(timepicker): support autoswap API

---

package.json

chore: remove deprecated dep

---

package.json
site/vite.config.js

https://github.com/Tencent/tdesign-react/issues/3157

fix: change of sideEffects leads to 1.9.2 lib bundle contains style file

---

.gitignore

chore: ignore generated javascript demo

---

CHANGELOG.md
package.json

chore: release 1.9.3

---

src/form/hooks/useFormItemInitialData.ts

#3182
- fix(Form): 修复`1.9.3`版本 `FormItem` 在`Form`外设置了`name`属性有异常的问题

fix(Form): fix warning when form-item is used out of form

---

package.json

- chore: fix `happy-dom` security under version 15

chore: fix dependencies security

---

src/table/hooks/useTreeData.tsx

- https://stackblitz.com/edit/react-t3ff2v-x8iqec?file=src%2Fdemo.tsx
- fix(Table): 修复动态设置`expandTreeNode`没有正常展示子节点的问题

fix(Table): fix expandedTreeNodes change effect

---

src/tree/hooks/useStore.ts

- https://stackblitz.com/edit/react-2e49gr-jndsmj?file=src%2Fdemo.tsx
- fix(Tree): 修复动态切换`expandAll`的功能异常问题

fix(tree): fix expandAll dynamic change behavior

---

src/avatar/type.ts
src/common.ts

chore(avatar): move ShapeEnum to common.ts

---

CHANGELOG.md
package.json

release 1.10.0
- chore: release 1.10.0

chore: release 1.10.0

---

.vscode/settings.json
src/textarea/Textarea.tsx

fix TextArea event type
- fix(TextArea): 修復 `TextArea` 事件類型問題

fix(TextArea): fix TextArea event type

---

package.json
site/src/App.jsx

docs: version list should follow semver standard

---

src/notification/config.ts
src/notification/notification.md

修改前：
修改后：
新增：
fix(notification): 修改NotificationPlugin的offset属性默认值，使其更符合常规习惯

fix(notification): fix NotificationPlugin offset x value

---

src/tree/Tree.tsx

- fix(Tree): 修复`scrollTo`方法滚动的异常行为

fix(Tree): fix scrollto behavior

---

src/drawer/drawer.md

fix: drawer api typo

---

src/menu/SubMenu.tsx

https://github.com/Tencent/tdesign-react/issues/3237
将SubMenu的onClick事件绑定从li更换到title所在的div
- fix(menu): change trigger element of  onClick event

fix(menu): change trigger element of  onClick event

---

src/checkbox/CheckboxGroup.tsx

https://github.com/Tencent/tdesign-react/issues/3250
健壮性修复，增加可选链
- fix(CheckboxGroup): robustness

fix(CheckboxGroup): robustness

---

src/checkbox/CheckboxGroup.tsx

fix CheckoutGroup displayName
- fix(CheckoutGroup): 添加可选链判断

fix(CheckoutGroup): fix CheckoutGroup displayName

---

src/date-picker/DatePicker.tsx
src/date-picker/__tests__/date-picker.test.tsx
src/date-picker/__tests__/date-range-picker.test.tsx
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/hooks/useRange.tsx
src/date-picker/type.ts
src/range-input/range-input.en-US.md
src/range-input/range-input.md
src/range-input/type.ts
src/time-picker/TimePicker.tsx
src/time-picker/TimeRangePicker.tsx
src/time-picker/__tests__/time-picker.test.tsx
src/time-picker/time-picker.en-US.md
src/time-picker/time-picker.md
src/time-picker/type.ts

- feat(DatePicker): 新增支持`label` API
- feat(TimePicker): 新增支持`label` API
- feat(RangeInput): 新增支持`label` API

feat: support label

---

src/date-picker/base/Table.tsx

https://github.com/Tencent/tdesign-react/issues/3274
更新前：
更新后：

fix(DateRangePicker):  fix week selected style when crossing the year

---

tsconfig.json

- chore: fix `tsconfig.json` test-utils

chore: fix tsconfig.json test-utils

---

src/textarea/Textarea.tsx

- https://github.com/Tencent/tdesign-common/pull/2003
优化 `TextArea` 初始加载设置 `autosize` 的高度抖动问题
- perf(TextArea): optimize `TextArea` init load `autosize` height

perf(TextArea): optimize TextArea init load autosize

---

CHANGELOG.md

- https://github.com/Tencent/tdesign-react/actions/runs/12410423614

chore: fix build

---

site/src/components/stackblitz/content.js
site/src/components/stackblitz/index.jsx
src/form/_example/form-field-linkage.tsx

- https://github.com/Tencent/tdesign-react/issues/3296
- docs: 调整`stackblitz`示例的启动方式，并修复部分示例无法使用`stackblitz`或`codesandbox`运行的问题

chore: fix box demo start up

---

src/select/util/helper.ts

fix(Select): fix checkall default value

---

src/form/FormItem.tsx

优化`Form` setField 相同值时，使用Lodash `isEqual`来处理 `Rerender`
- feat(form): optimize setField same not rerender

feat(Form): optimize setField same not rerender

---

src/select/base/Select.tsx
src/select/util/helper.ts

- fix(Select): 修复`onChange`回调context中的全部选项的值没有包含选项本身全部内容的问题

fix: select onchange params

---

src/descriptions/descriptions.en-US.md
src/descriptions/descriptions.md

https://github.com/TDesignOteam/tdesign-api/pull/504

docs: fix typo

---

src/auto-complete/AutoComplete.tsx
src/auto-complete/OptionList.tsx
src/auto-complete/auto-complete.en-US.md
src/auto-complete/auto-complete.md
src/auto-complete/type.ts
src/config-provider/config-provider.en-US.md
src/config-provider/config-provider.md
src/config-provider/type.ts

feat(auto-complete): support empty api

---

src/color-picker/components/panel/index.tsx

https://github.com/Tencent/tdesign-react/pull/3120
https://github.com/Tencent/tdesign-common/pull/1962
useRef缓存导致state和ref保存的颜色未同步，引发的一系列问题
- fix(color-picker): 修复innerValue和colorInstanceRef不同步导致的问题

fix(color-picker): coloerInstanceRef value is not updated, causing re-render problems

---

src/form/FormItem.tsx

Reverts Tencent/tdesign-react#3302

Revert "feat(Form): optimize setField same not rerender"

---

.eslintrc.js
src/hooks/useDebounce.ts

改lodash-es 后，npm 安装 ，lodash 可能存在于幽灵依赖，会被误用使用，项目启用eslint 规则 禁止使用lodash

chore(eslint): restricted import lodash

---

src/date-picker/hooks/useRangeValue.ts
src/date-picker/hooks/useSingleValue.tsx

fix: import extractTimeFormat path

---

src/card/Card.tsx

- #3368
修復`Card`在React19 控制台的錯誤
- fix(Card): fix Card React19 console error

fix(Card): fix Card React19 console error

---

src/dropdown/DropdownItem.tsx

- fix(Dropdown): 修复点击事件回调context参数返回不符合文档描述的问题

fix(Dropdown): fix dropdown click callback context format

---

src/config-provider/config-provider.en-US.md
src/config-provider/config-provider.md
src/config-provider/type.ts
src/layout/Layout.tsx
src/layout/layout.en-US.md
src/layout/layout.md
src/layout/type.ts

- docs(ConfigProvider): 增加 `globalConfig` API文档 
- feat(Layout): 子组件 `Content` 新增  `content` API 

feat(Content): support content api

---

CHANGELOG.md
package.json

Release: 1.11.1

---

.github/workflows/auto-release.yml
.github/workflows/pr-compressed-size.yml
.github/workflows/tag-push.yml

chore: adjust publish ci

---

packages/tdesign-react/site/src/components/codesandbox/content.js
packages/tdesign-react/site/src/components/stackblitz/content.js

fix site path import error
- fix(site): 修复网站导入 `package.json` 路径错误

fix(site): fix site path import error

---

.github/workflows/pr-comment-ci.yml

ci(pr-comment-ci): use pnpm

---

packages/tdesign-react/site/src/App.jsx

delete development mode request event
- chore(Docs): 删除开发时无效接口请求

chore(docs): delete development mode request event

---

packages/components/transfer/utils.ts

https://github.com/user-attachments/assets/060a059e-9058-4445-b018-c39eef49fd64
- fix(transfer): 删除在自定义 tree 节点时对于 tree 子节点的不必要过滤

fix(transfer): remove unnecessary filter children in custom `tree` node

---

.github/ISSUE_TEMPLATE/bug-report.zh-CN.yml
.github/ISSUE_TEMPLATE/feature-report.zh-CN.yml

chore: add default issue labels

---

packages/components/card/card.en-US.md
packages/components/card/card.md

docs(card): fix card api documentation text

---

packages/tdesign-react/site/package.json
packages/tdesign-react/site/src/components/codesandbox/content.js
packages/tdesign-react/site/src/components/stackblitz/content.js

- chore: fix codesandbox and stackblitz setup in develop branch

chore: fix sandbox run after refactoring dir

---

packages/components/table/_example/editable-row.tsx

https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-fznm4j?file=%2Fsrc%2Fdemo.tsx%3A61%2C45
- 点击保存按钮，会出现校验失败的问题，原因是通过dataset等方式获取的rowkey是字符串类型，但是由于设置进ruleMap是通过rowKey设置的，存在map.get获取不到的情况，进而导致后续无法正常进行检验的结果。
- docs(Table): 优化可编辑表单的示例代码

chore: update table demo

---

packages/tdesign-react/package.json

- chore: validate publish workflow

chore: release 1.11.2-beta.1 based on mono repo

---

script/utils/bundle-override.js

chore: fix esm

---

packages/components/input/Input.tsx
packages/components/transfer/utils.ts
packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.11.2

---

package.json
script/rollup.config.js

- fix(lib): 修复 `1.11.2` 版本中 `lib` 产物冗余样式导致next使用异常及版本号缺失的问题

chore: fix lib bundle

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: Release 1.11.3

---

packages/components/select/_example/remote-search.tsx

Related https://github.com/Tencent/tdesign/issues/610
1. 将示例只保留远程搜索
2. 当选中值数量为 0 个时永远不存在选中情况发生。
- fix(Select): 修复远程搜索示例错误

fix(Select): remote search scene error

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.11.4

---

packages/components/tag/Tag.tsx
packages/components/tag/__tests__/vitest-tag.test.jsx

- fix(Tag): 修复 style 优先级低于color计算结果导致无法强制覆盖标签样式的场景

fix(Tag): fix custom style priority when color is set 

---

packages/components/common.ts
packages/components/common/PluginContainer.tsx
packages/components/config-provider/ConfigProvider.tsx
packages/components/config-provider/config-provider.en-US.md
packages/components/config-provider/config-provider.md
packages/components/config-provider/type.ts
packages/components/loading/plugin.tsx
packages/components/message/Message.tsx

新增全局配置属性,message,loading组件支持全局属性配置
- feat(config-provider): 新增全局配置属性,message,loading组件支持全局属性配置

feat(config-provider): support global-config affect plugin usage

---

packages/components/radio/RadioGroup.tsx

之前PR https://github.com/Tencent/tdesign-react/pull/3446 的一些遗留问题，条件检查疏忽了，导致 `style` 为 `{}` 的时候 Observer  也被清除了。

fix(RadioGroup): improve bar style condition check

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.11.6

---

packages/components/dialog/plugin.tsx
packages/components/notification/NotificationList.tsx
packages/components/popup/PopupPlugin.tsx

函数调用支持全局上下文配置
- feat(Dialog): Pouup,Notification,Dialog函数调用支持全局上下文配置

feat(Dialog): function calls support global context config

---

packages/components/drawer/_example/plugin.tsx
packages/components/drawer/plugin.tsx

Drawer函数调用支持全局上下文配置
- feat(Drawer): Drawer函数调用支持全局上下文配置

feat(Drawer): function calls support global context config

---

packages/components/input-number/useInputNumber.tsx

- fix(input-number): 修复组件未受 value 属性控制的问题

fix(input-number): fix controlled status

---

packages/components/slider/Slider.tsx

>[!WARNING]
> merge https://github.com/Tencent/tdesign-react/pull/3499 first
- fix(Slider): 修复打开了输入框模式下，使用 `theme` 为 `col` 的输入框的场景下没有限制大小的问题

fix(Slider): limit the `max` and `min` of `InputNumber`

---

packages/components/date-picker/date-picker.en-US.md
packages/components/date-picker/date-picker.md
packages/components/date-picker/hooks/useRange.tsx
packages/components/date-picker/type.ts

feat(DatePicker): DateRangePicker add clear event

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.11.7

---

packages/components/message/Message.tsx

Message函数调用代码优化
- feat(Message): 函数调用支持全局上下文配置

feat(Message): function calls support global context config

---

packages/components/select/util/helper.ts

- https://stackblitz.com/edit/7sezpzox-mwlsicqh?file=src%2Fdemo.tsx
- fix(Select): 修复`1.11.2` 版本后使用子组件方式回调函数中缺失完整 option 信息的缺陷

fix(Select): fix change callback context option

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.11.8

---

packages/components/drawer/Drawer.tsx
packages/components/drawer/defaultProps.ts
packages/components/drawer/drawer.en-US.md
packages/components/drawer/drawer.md
packages/components/drawer/type.ts

- feat(Drawer): 新增 `lazy` 属性，其与 `forceRender` 功能一致，`forceRender` 已声明废弃未来版本将被移除

feat(Drawer): implemented lazy

---

packages/components/dialog/Dialog.tsx
packages/components/dialog/defaultProps.ts
packages/components/dialog/dialog.en-US.md
packages/components/dialog/dialog.md
packages/components/dialog/type.ts

- feat(Dialog): 新增 `lazy` 属性，其与 `forceRender` 功能一致，`forceRender` 已声明废弃未来版本将被移除

feat(Dialog): implemented lazy 

---

packages/components/chat-actionbar/index.ts
packages/components/chat-message/index.ts
packages/components/chat-sender/index.ts
packages/components/chatbot/_example/ComponentsBuild.tsx
packages/components/chatbot/chatbot.md
packages/components/chatbot/index.ts
packages/components/chatbot/useChat.ts

feat(chatbot): 添加拼装组件示例

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.12.1

---

packages/tdesign-react/site/site.config.mjs

docs(guide): add English component import

---

packages/components/_util/scroll.ts
packages/components/dialog/hooks/useLockStyle.ts

perf(dialog): reduce initial render time

---

.github/workflows/pkg-pr-new.yml
script/workflows/pkg-pr-new-generate-template.mjs

chore(ci): generation react pkg template

---

packages/components/menu/MenuGroup.tsx

- fix(MenuGroup): support className and style

fix(MenuGroup): support className and style

---

packages/components/list/List.tsx

https://github.com/Tencent/tdesign-react/pull/3363
@HaixingOoO  帮我看看这部分需要处理 `undefined` / `null` 吗？
- fix(List): 空子节点导致获取子节点 `props` 失败

fix(List): empty child node cannot get child node `props`

---

packages/components/guide/Guide.tsx

- #2952
fix Guide screen resize update layer position
- fix(Guide): 优化组件在屏幕大小变化时没有重新计算位置的问题

fix(Guide): fix Guide screen resize update layer position

---

packages/components/form/FormItem.tsx

优化setFields的逻辑
- perf(Form): optimize Form setFields

perf(Form): optimize Form setFields

---

packages/components/form/FormItem.tsx

chore: fix form item single usage

---

packages/components/date-picker/DatePicker.tsx

https://github.com/Tencent/tdesign-react/issues/3575
- fix(DatePicker): 修复 onFocus 事件触发时机问题

fix(datepicker): fixed the trigger timing for onFocus event

---

packages/components/form/FormItem.tsx
packages/components/select/base/Select.tsx

- https://github.com/Tencent/tdesign-react/issues/3574
- fix(Select): 修复option为空时搜索异常的问题
- fix(Form): 兼容 1.12.0 版本前单独使用 FormItem 的场景

chore: fix undefined

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.12.2

---

packages/components/table/hooks/useColumnController.tsx

sync  https://github.com/Tencent/tdesign-vue-next/pull/5546
- fix(Table): 优化关闭列配置弹窗时，选择列数据与所展示列数据不一致的问题

fix(Table): sync columnCheckboxKeys on close

---

packages/components/tabs/TabPanel.tsx

- fix(Tabs): 修复 TabPanel 通过 style 设置 display 属性无法正常生效的问题

fix(Tabs): fix tab panel custom style

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json
packages/tdesign-react/site/docs/getting-started.en-US.md
packages/tdesign-react/site/docs/getting-started.md

chore: release 1.12.3

---

packages/tdesign-react/CHANGELOG.md

chore: Update CHANGELOG.md

---

packages/components/table/BaseTable.tsx
packages/components/table/hooks/useFixed.ts

https://github.com/Tencent/tdesign-react/issues/3598
useFixed里有相关TODO，因Affix组件已支持了handleScroll方法，所以放开注释
- fix(table): 高度变化时affix重新计算位置

fix(table): update affix position when table height changed

---

packages/components/table/hooks/useFixed.ts

https://github.com/Tencent/tdesign-react/issues/3632
<details>
<summary>复现例子</summary>
```tsx
import React, { useState } from 'react';
import { CheckCircleFilledIcon, CloseCircleFilledIcon, ErrorCircleFilledIcon } from 'tdesign-icons-react';
import { Button, Space, Table, Tag } from 'tdesign-react';
import type { TableProps } from 'tdesign-react';
const data: TableProps['data'] = [];
const total = 5;
for (let i = 0; i < total; i++) {
data.push({
index: i + 1,
applicant: ['贾明', '张三', '王芳'][i % 3],
status: i % 3,
channel: ['电子签署', '纸质签署', '纸质签署'][i % 3],
detail: {
email: ['w.cezkdudy@lhll.au', 'r.nmgw@peurezgn.sl', 'p.cumx@rampblpa.ru'][i % 3],
},
matters: ['宣传物料制作费用', 'algolia 服务报销', '相关周边制作费', '激励奖品快递费'][i % 4],
time: [2, 3, 1, 4][i % 4],
createTime: ['2022-01-01', '2022-02-01', …
```

fix(Table): handle potential null value when `showHeader={false}`

---

packages/components/locale/LocalReceiver.ts
packages/components/pagination/hooks/useTotal.tsx

https://github.com/Tencent/tdesign-common/issues/2119
支持复数国际化
- feat(locale): add i18n plural for pagination.total

feat(locale): add i18n plural for pagination.total

---

packages/components/dropdown/DropdownMenu.tsx

- fix(Dropdown): 修复部分场景下拉菜单节点获取异常导致的错误问题

fix(dropdown): fix error when dropdown menu is hidden

---

packages/components/table/BaseTable.tsx
packages/components/tree/tree.md

https://github.com/Tencent/tdesign-react/issues/3668
- fix(Table): `EnhancedTable` 使用 `tree` API ，动态初始化 `columns` 时不存在 unique key

fix(Table): ensure unique keys for dynamic column elements

---

packages/components/table/hooks/useTreeDataExpand.ts

之前这个 [PR#3638](https://github.com/Tencent/tdesign-react/pull/3638)，解决 `defaultExpandAll` 失效问题，但引发了异步设置 `EnhancedTable` 的 `data` 时，数据为空。
- fix(EnhancedTable): 解决 `1.13.0` 版本中引入的修复，导致异步场景下 `data` 更新失败的问题

fix(EnhancedTable): optimize expandAll function

---

packages/components/upload/hooks/useUpload.ts

- fix(Upload):  确保在 `beforeUpload` 完成之后，再执行上传动作

fix(Upload): delay the upload until after beforeUpload

---

packages/tdesign-react/site/plugins/plugin-tdoc/demo.js
packages/tdesign-react/site/plugins/plugin-tdoc/md-to-react.js
packages/tdesign-react/site/src/components/newwindow/index.jsx

docs: demo of opening a new window

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.13.2

---

packages/tdesign-react/CHANGELOG.md

fix(changelog): correct typo in component name

---

packages/components/skeleton/_usage/props.json
packages/components/skeleton/skeleton.en-US.md
packages/components/skeleton/skeleton.md
packages/components/skeleton/type.ts

docs(Skeleton): update doc

---

packages/tdesign-react/site/src/App.jsx
packages/tdesign-react/site/src/components/Demo.jsx

- fix: 确保单独 Demo 页面在开发模式可以热更新，方便调试

fix(Demo): ensure HMR works in development mode

---

packages/components/form/FormList.tsx
packages/tdesign-react/CHANGELOG.md

- 相关 PR：https://github.com/Tencent/tdesign-react/pull/3684
- fix(FormList): 解决 `1.13.2` 引入的通过 `initData` 设置初始值后新增数据异常的问题

fix(FormList): prevent undefined defaultValue from being set

---

packages/components/table/PrimaryTable.tsx

https://github.com/Tencent/tdesign-react/issues/3687
- fix(Table): 修复 `dragSort='row-handler-col'` 时，列拖拽不生效的问题

fix(Table): update `dragSort` handling to support `row-handler-col`

---

packages/components/upload/hooks/useUpload.ts

- feat(Upload): 支持在非自动上传场景下上传指定文件

feat(upload): support upload specified files

---

packages/components/form/FormItem.tsx
packages/components/form/__tests__/form.test.tsx

- DEMO: https://stackblitz.com/edit/r2rma5gf?file=src%2FDemo.tsx,src%2FNestedForm.tsx,src%2Fmain.tsx
- feat(Form): `rules` 支持配置嵌套字段进行校验
- fix(Form): 修复嵌套表单中内层表单受外层表单影响校验结果字段的问题

fix(Form): fix form validate result in nested form

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.14.1

---

packages/tdesign-react/site/package.json
packages/tdesign-react/site/src/App.jsx
packages/tdesign-react/site/src/main.jsx

chore: @tdesign/site-components instead of tdesign-site-components

---

packages/components/dialog/hooks/useDialogDrag.ts
packages/components/hooks/useMouseEvent.ts

- fix(Dialog): 修复 `1.14.0` 引入的新特性导致 `draggable` 禁用失败的问题

fix(Dialog): ensure `draggable` functionality

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.14.2

---

packages/tdesign-react/site/src/components/stackblitz/index.jsx

docs(site): stackblitz support pkg-pr-new

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.14.3

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.14.4

---

packages/components/hooks/useVariables.ts

- fix(Watermark):  完善水印组件在 SSR 场景的兼容问题

fix(Watermark): fix watermark in ssr

---

packages/tdesign-react/site/src/components/Demo.jsx

- fix(Demo): 确保 flex 不影响 demo 本身的布局

fix(Demo): wrap page in an additional div for better layout control

---

README-zh_CN.md
README.md
packages/tdesign-react/README-zh_CN.md
packages/tdesign-react/README.md

- https://github.com/Tencent/tdesign/pull/715

chore: update group code path

---

packages/components/message/Message.tsx

`content` 为 `''` / `undefined` / `null` 时进入了 else 分支，导致渲染的 `content` 为对象 `{ content: "" } `
```tsx
if (isConfig(content)) {
config = {
duration,
...content,
};
} else {
config = {
content,
duration,
};
}
```
- fix(MessagePlugin): 修复 `content` 为 `''` / `undefined` / `null` 时产生的报错 

fix(MessagePlugin): improve content creation

---

packages/components/table/table.md
packages/components/table/type.ts

- https://github.com/TDesignOteam/tdesign-api/pull/711

docs(Table): fix `asyncLoading` state description

---

packages/tdesign-react/site/src/components/Demo.jsx
packages/tdesign-react/site/src/components/DraggableButton.jsx

单组件 DEMO 页面新增一个重置按钮，省得每次本地复现初始化状态时，都要手动刷新页面，时间久 ➕ 产生一堆网络报错的 log

feat(Demo): implement reset button for demo state management

---

packages/components/cascader/Cascader.tsx
packages/components/cascader/hooks.tsx

#3789
- fix(Cascader): 修复启用 `multiple` 与 `valueType='full'` 时，`valueDisplay` 渲染异常的问题

fix(Cascader): fix `selectedOptions` param in `valueDisplay`

---

packages/components/table/hooks/useSorter.tsx

https://github.com/Tencent/tdesign-react/issues/3190
- fix(Table): 修复开启 `multipleSort` 但没有声明 `sort` 或 `defaultSort` 时，`onSortChange` 始终返回 `undefined` 的问题

fix(Table): handle undefined callback in `onSortChange`

---

packages/components/date-picker/DateRangePicker.tsx
packages/components/date-picker/DateRangePickerPanel.tsx

https://github.com/Tencent/tdesign-react/issues/3793
- fix(DateRangePickerPanel): 修复 `preset` 涉及跨年份的日期时，点击面板后无法同步的问题

fix(DateRangePicker): enhance panel synchronization for preset

---

packages/components/select/base/Option.tsx
packages/components/select/base/PopupContent.tsx

- `content` 作为 `label`：https://github.com/Tencent/tdesign-react/issues/2981
- `content` 作为 `value`：https://github.com/Tencent/tdesign-vue-next/issues/5088
- fix(Select): 修复使用 `keys`  配置  `content` 作为 `label` 或 `value` 无法生效的问题

fix(Select): ensure keys props with content/children work correctly

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.15.3

---

packages/components/hooks/useVirtualScroll.ts
packages/components/list/List.tsx
packages/components/list/_example/scroll.tsx
packages/components/list/list.md
packages/components/menu/SubMenu.tsx
packages/components/select/base/PopupContent.tsx
packages/components/table/_example/filter-controlled.tsx
packages/components/tree/__tests__/tree.test.tsx
packages/tdesign-react/CHANGELOG.md

相关 PR：https://github.com/Tencent/tdesign-react/pull/3836
- fix(List): 移除 `1.15.2` 版本引入的冗余代码造成开启虚拟滚动时初始化卡顿的问题
- fix(Select): 移除 `1.15.2` 版本引入的冗余代码造成开启虚拟滚动时初始化卡顿的问题

fix(useVirtualScroll): optimize visibleData rendering logic

---

packages/tdesign-react/CHANGELOG.md
packages/tdesign-react/package.json

chore: release 1.15.5
