- src/menu/_example/multi-side.jsx
- src/tooltip/_example/trigger.jsx
1. `menu`组件[demo](https://tdesign.tencent.com/react/components/menu#%E5%B9%B3%E9%93%BA%E5%BC%8F%E4%BE%A7%E8%BE%B9%E5%AF%BC%E8%88%AA)暗黑模式 收起后无法展开
2. `tooltip`组件[demo](https://tdesign.tencent.com/react/components/tooltip#%E4%B8%8D%E5%90%8C%E8%A7%A6%E5%8F%91%E6%96%B9%E5%BC%8F%E7%9A%84%E6%96%87%E5%AD%97%E6%8F%90%E7%A4%BA)鼠标右键事件不生效
> fix(menu & tooltip): 修复部分示例不生效

- src/popup/hooks/useTriggerProps.ts
修复`popup`的错误展示逻辑。具体如下：
设置`trigger`为`hover`模式，当hover展示一次之后，再hover到弹出窗的位置，弹出层将会展示。
只在`triggerNode`时触发展示
> fix(popup): fix popup wrong display logic when using hover mode

- src/time-picker/TimePicker.tsx
- src/time-picker/TimeRangePicker.tsx
- src/time-picker/panel/TimePickerPanel.tsx
- src/time-picker/panel/TimePickerRangePanel.tsx
> fix(TimePicker): timePicker confirm event is invalid

- src/select/base/Select.tsx
修复当添加select组件添加clearable以及filterable的时候, 第二次以后点击清除按钮的显示值不对
> fix(Select): add filterable attribute, the value of click the clear button is not show correctly

- src/avatar/AvatarContext.tsx
- src/dialog/plugin.tsx
- src/input-number/InputNumber.tsx
- src/input-number/StepHandler.tsx
- src/notification/Notification.tsx
- src/notification/NotificationList.tsx
来源此：https://github.com/Tencent/tdesign-react/pull/83#issuecomment-1001113226 ，统一了 React 导入形式，保证代码风格统一
> refactor: 统一 React 导入方式

- src/popconfirm/PopConfirm.tsx
- src/popconfirm/__tests__/PopConfirm.test.tsx
- src/popup/hooks/usePopupCssTransition.ts
- src/tooltip/Tooltip.tsx
- src/tooltip/__tests__/tooltip.test.tsx
1. fix https://github.com/Tencent/tdesign-react/issues/131
2. fix https://github.com/Tencent/tdesign-react/issues/133
3. fix default value of destroyOnClose API of tooltip and popconfirm
> fix(popup): dynamic height

- src/drawer/Drawer.tsx
我认为 && 和三目运算符的使用规范需要统一，根据条件判断是否展示元素，最好是使用 &&。
> refactor(drawer): use '&&' to replace ternary operator

- src/cascader/Cascader.tsx
- src/cascader/__tests__/__snapshots__/cascader.test.tsx.snap
use input full width
before
after
> feat: cascader inputwidth

- src/dialog/_example/plugin.jsx
`dialog`组件的`plugin`调用时，示例无法正常关闭。[refer](https://tdesign.tencent.com/react/components/dialog#%E6%8F%92%E4%BB%B6%E5%87%BD%E6%95%B0%E5%BC%8F%E8%B0%83%E7%94%A8)
> fix(dialog): fix dialog example can't be closed when using plugin mode

- site/src/App.jsx
当我给tdesign-vue修复一个版本选择的bug的时候( https://github.com/Tencent/tdesign-vue/pull/239 )，参考了tdesign-react的处理，看了版本切换的源码部分，发现了这个拼写错误，tdesign-vue和这里的代码基本是一致的，只是tdesing-vue这里拼的是正确的，所以有统一拼写的考虑
> fix(site): spell fault

- package.json
icon size的枚举`middle` 应该为`medium`
> fix(icon): medium size

- src/cascader/components/Item.tsx
- 修复cascader组件斜八度动画过渡时覆盖选项的问题
- fix: https://github.com/Tencent/tdesign-react/issues/80
- 修复前
https://user-images.githubusercontent.com/26377630/151312070-09b6882d-aa60-4b82-921b-4f7ada7262cc.mp4
- 修复后
https://user-images.githubusercontent.com/26377630/151312093-6831ccb9-daa0-4a03-87d1-80ba380e69e0.mp4
> fix(cascader): ripple cover panel item

- src/form/FormItem.tsx
> fix: 修复 form reset 后首次更改值不触发校验

- src/menu/hooks/useMenuContext.ts
- src/select/base/Select.tsx
- src/select/util/helper.ts
- 修改 lodash 引入方式
- lodash 默认导出 UMD 模块，并不支持 ESM
- build size: 修改前 dist/tdesign.js 1.9M，修改后 dist/tdesign.js 1.4M
修改 lodash 引入方式为文件引入
> chore(util): 修改 lodash 引入方式

- src/upload/upload.tsx
- src/upload/util.ts
https://github.com/Tencent/tdesign-react/issues/353
1.  修复requestMethod返回fail时，图片依然回显问题
- fix(upload): 修复requestMethod返回fail时，图片依然回显问题
> fix: 修复requestMethod返回fail时，图片依然回显问题

- src/notification/NotificationList.tsx
日常 bug 修复.
修复 notification 在 https://codesandbox.io/s/tdesign-react-demo-forked-69g589?file=/src/demo.jsx:0-1062 环境下的使用异常问题
当前修复为临时修复版本，notification 组件将尽量在本周末进行重构以避免未来有类似奇怪的问题发生。
notification 组件，删除部分代码。
删除代码的功能为: 
notification 根据位置（左上 左下 ...） 分为九个区块，每个区块会存在一个容器以放置 notification 。当前代码的作用为，当存在部分数据变动时，检测每个容器内是否依然存在正在展示的 notification，如不存在则将容器一起销毁（容器销毁后，会在新增对应 notification 时重新创建）。
删除代码后：
容器一经创建将不会被销毁（极端情况下页面上会多出九个空 div 标签）
删除代码的原因：
https://codesandbox.io/s/tdesign-react-demo-forked-69g589?file=/src/demo.jsx:0-1062
在上述场景下，会出现控制台异常，暂未排查出异常的具体代码原因，但测试发现只要容器不销毁就不会发生。
> fix: notification 组件临时修复特殊用法下的报错问题

- site/plugin-tdoc/md-to-react.js
> docs: 修复 form api 文档样式错乱

- src/checkbox/CheckboxGroup.tsx
> fix(checkbox): 修复checkbox组件options为空数组时的问题

- src/cascader/Cascader.tsx
- src/cascader/components/Panel.tsx
- src/cascader/utils/cascader.ts
- src/cascader/utils/inputContent.ts
#371 
#304 
代码逻辑改动点：
1. options的动态更新使用treestore.reload 重构逻辑，调用后使用 treeStoreExpendEffect，treeNodesEffect 两个hook与初始化逻辑保持一样
2. panel 子组件渲染 item的key使用index
3. treeStoreExpendEffect 中无匹配值时也需要refreshNode，渲染面板，且input中展示出值。
- fix(cascader): 修复异步设置数据不生效
- fix(cascader): 修复无匹配值不渲染面板
> fix(cascader): fix cascader issue 371&&304

- src/dialog/RenderDialog.tsx
多个弹窗关闭一个后出现滚动条
fix #382
日常 bug 修复
dialog 组件
再关闭一个弹窗时仙判断是否还有未关闭的弹窗，再选择是否还原滚动条
- fix(dialog): 多个弹窗关闭一个后出现滚动条
> fix(dialog): 多个弹窗关闭一个后出现滚动条

- package.json
eslint-plugin-react 7.29.0 修改了jsx-key的规则导致lint检查失败 先处理一下 避免阻塞PR
> chore: eslint test fail

- src/_util/useDialogEsc.ts
- src/dialog/RenderDialog.tsx
dialog 支持Esc关闭
dialog  新特性提交,
支持Esc关闭, 支持嵌套的dialog逐个按ESC关闭  
将打开的dialog逐个存到Set对象中，将最后打开的dialog设置为focus, 即可接收到按下ESC的键盘事件  
- fix(dialog): 支持Esc关闭, 支持嵌套的dialog逐个按ESC关闭
- [] 本条 PR 不需要纳入 Changelog
> feat(dialog): dialog 支持Esc关闭

- src/select/base/Select.tsx
> fix: 优化 select 多余padding

- src/_util/useRipple.ts
- src/affix/__tests__/__snapshots__/affix.test.tsx.snap
- src/badge/__tests__/__snapshots__/badge.test.tsx.snap
- src/button/__tests__/__snapshots__/button.test.tsx.snap
- src/calendar/__tests__/__snapshots__/calendar.test.tsx.snap
- src/checkbox/__tests__/__snapshots__/checkbox.test.tsx.snap
- src/comment/__tests__/__snapshots__/comment.test.tsx.snap
- src/dialog/__tests__/__snapshots__/modal.test.tsx.snap
- src/drawer/__tests__/__snapshots__/drawer.test.tsx.snap
- src/form/__tests__/__snapshots__/form.test.tsx.snap
- src/input-number/__tests__/__snapshots__/input-number.test.tsx.snap
- src/layout/__tests__/__snapshots__/layout.test.tsx.snap
- src/loading/__tests__/__snapshots__/Loading.test.tsx.snap
- src/menu/__tests__/__snapshots__/menu.test.tsx.snap
- src/notification/__tests__/__snapshots__/Notification.test.tsx.snap
- src/steps/__tests__/__snapshots__/steps.test.tsx.snap
- src/swiper/__tests__/__snapshots__/swiper.test.tsx.snap
- src/table/__tests__/__snapshots__/table.test.tsx.snap
- src/tabs/__tests__/__snapshots__/tabs.test.tsx.snap
- src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
- src/transfer/__tests__/__snapshots__/transfer.test.tsx.snap
- src/tree/__tests__/__snapshots__/tree.test.tsx.snap
- src/upload/__tests__/__snapshots__/upload.test.tsx.snap
- 日常 bug 修复, 组件样式/交互改进
- fix https://github.com/Tencent/tdesign-react/issues/461
- 此前实现斜八度动画做了一个提前改动元素position的处理 移动到点击事件之后可以少去不必要的渲染 同时避免类似issue中的异常 
- fix(inputnumber): dialog中使用样式异常
> chore: remove extra position style

- src/slider/Slider.tsx
fix: slider still can be drag when the disabled attr is true.
issue: https://github.com/Tencent/tdesign-react/issues/497
> fix: slider disabled bug

- src/dialog/RenderDialog.tsx
closeOnOverlayClick work in dialog
fix: #532
- fix(dialog): dialog支持closeOnOverlayClick属性
> fix(dialog): closeOnOverlayClick work in dialog

- src/dialog/RenderDialog.tsx
before:
Dialog header 渲染重复包裹了 `t-dialog__header` DOM 结构，修复后 header 将只有一层：
after:
- fix(Dialog):  修复 Dialog Header 渲染了多余 DOM 层级的问题
> fix: remove dialog duplicated header dom

- src/popconfirm/PopConfirm.tsx
- src/popconfirm/PopContent.tsx
PopConfirm 中没有引入 Popup 组件的样式，按需引入 PopConfirm ESM 构建产物时会导致弹窗没有样式：
修复后：
- fix(PopConfirm): 修复按需引入 ESM 产物时弹窗样式丢失的问题
> fix: popconfirm import

- src/select/_example/remote-search.jsx
- src/select/base/Select.tsx
- 日常 bug 修复 修复onSearch触发时机的错误 
- #555 
每次focus在select上的同时 filterable的情况下，会清空SelectInput的value 进而触发onInputChange 携带参数为原来的selectLabel 所以加一下判断是否是原来的值 如果是就不要触发onSearch 
- fix(Select): 修复onSearch触发时机的问题
> fix(Select): stop trigger onSearch when focus

- src/cascader/Cascader.tsx
修复 #581 
tree node 的 label 和 value 只在初始化的时候会被赋值，原本是想改 tree node，在update的时候，更新 label 和 value，但是也会涉及到 children的变更，所以干脆在 key or options 变更时，去重新构建 treeStore.nodes
不过涉及到 tree-store 的 removeAll 方法，我的理解是 removeAll 应该联通 children 一并清除，不清楚这算不算之前设计的一个小缺陷
- fix(cascader): 定制数据字段别名时数据展示问题
> fix(cascader): 定制数据字段别名 label 不展示问题

- src/popup/__tests__/popup.test.tsx
- src/popup/hooks/useTriggerProps.ts
当点击嵌套浮层的浮层时，会导致第一个浮层关闭
https://codesandbox.io/s/tdesign-react-demo-forked-tsjvyj?file=/src/demo.jsx
通过浮层中监听 onMouseDown 来阻止 clickOutSide 事件触发
- fix(popup): 嵌套浮层内触发 mouseDown、click 时不应该关闭上一级的浮层
> fix(popup):  嵌套浮层内触发 mouseDown、click 时不应该关闭上一级的浮层

- src/popup/Popup.tsx
TreeSelect 组件 autoWidth 属性变化时因为triggerRef的宽度变化会导致宽度计算错误
在显示隐藏时重新计算一次宽度
- fix(popup): render incorrect width when triggerRef style changed
> fix(popup): render incorrect width when triggerRef style changed

- src/cascader/_example/ellipsis.jsx
- src/cascader/components/Item.tsx
- src/cascader/utils/item.ts
#604 
- fix(Cascader): 多选或筛选时，文本过长展示提示
> fix(cascader): 多选或筛选时文本过长的展示

- src/breadcrumb/Breadcrumb.tsx
- src/breadcrumb/BreadcrumbItem.tsx
(cherry picked from commit 2d260ea7ac0fcd4c8373cab87c320f86d47db6b6)
- fix(breadcrumb): 面包屑初始样式被覆盖
> fix(breadcrumb): 面包屑初始样式被覆盖

- src/dialog/Dialog.tsx
- src/dialog/RenderDialog.tsx
- src/dialog/plugin.tsx
修复 dialog destroy 功能
解决destroy时重复创建portal的问题
解决destroy时重复创建portal的问题
- fix(dialog): 修复 dialog destroy 功能
> feat(dialog): 修复 dialog destroy 功能

- src/cascader/utils/helper.ts
- src/cascader/utils/inputContent.ts
#622 
原因是点击 inputContent时触发 setVisible(true)，后面执行 outerClick 判断时 inputContent已经被移除，所以又判断为 true
目前的做法是，在判断outerClick时加多个判断当前触发的element 是否存在 body 中。
- fix(Cascader): filterable情况下，点击非空白区域展示问题修复
> fix(cascader):  filterable visible

- src/table/hooks/useFixed.ts
- 日常 bug 修复 处理table hooks在node环境中存在`getBoundingClientRect`为null的场景
> fix(table): getBoundingClientRect attribute is null

- src/input-number/InputNumber.tsx
- src/input-number/utils/numberUtils.ts
https://github.com/Tencent/tdesign-react/issues/727
**问题背景**
因为`internalInputValue`这个状态是组件内用于储存输入框展示的，它是 `string | number` 类型。但是在输入时会调用`strToNumber` 尝试把输入数字，所以 0.0 这样的输入就直接被转化成0然后展示到输入框里了
**解决方案**
参考vue侧的实现，`strToNumber`返回类型改为 `string | number`。emit值时再用`Number`转换为`number`（这样应该是安全的，在emit之前会调用`checkInput`检查数字合法性）
- fix(input-number): 无法输入小数
> fix: unable to input demical

- src/upload/type.ts
- src/upload/upload.md
- 其他 uploadFile 参数除url改为非必填
- feat(Upload): 修改uploadFiles类型参数除url外为非必填
> chore: uploadFile type required ctx

- src/upload/hooks/useSizeLimit.ts
> fix: 修复 Upload 组件value undifined 场景校验失败问题

- src/tabs/TabPanel.tsx
> feat(tabs): panel 支持 className 透传

- package.json
- src/table/FilterController.tsx
- src/table/PrimaryTable.tsx
- src/table/hooks/useFilter.tsx
- 日常 bug 修复
- 临时处理table过滤输入失焦问题 本质问题是table在输入时一直重复渲染 需要再提个PR处理这个问题
- fix(Table): 处理table过滤输入失焦问题
> fix: 处理table过滤输入失焦问题

- src/time-picker/TimeRangePicker.tsx
修复前
修复后
- fix(TimePicker): 修复`RangePicker`的聚焦样式丢失的问题
> fix(timepicker): fix range focus style

- src/tag-input/TagInput.tsx
onCompositionstart时 标记isComposition为true
onEnter时 判断如果当前为isComposition时不触发添加tag
onCompositionend时 标记isComposition为false
> fix(taginput): 修复中文输入法enter时，既触发添加tag也input框有输入的字母的问题

- CHANGELOG.md
- package.json
> chore: publish 0.34.4

- src/input-number/StepHandler.tsx
https://github.com/Tencent/tdesign-react/issues/854
第二次后点击减少按钮，onChange 触发发两次。
补上了 `return;`
- fix(input-number): trigger onChange twice when clicking reduce button
> fix(input-number): trigger onChange twice when clicking reduce button

- src/drawer/Drawer.tsx
> fix: 修复 drawer cancelBtn 传入字符串无效

- src/affix/Affix.tsx
- src/anchor/anchor.md
- src/anchor/type.ts
-  #880
修复`Anchor ` `Affix`组件类型定义问题
- fix(Anchor): 修复affix参数类型问题
> fix: fix anchor & affix props type error

- CHANGELOG.md
- package.json
> chore: publish 0.36.0

- src/color-picker/components/panel/index.tsx
[897](https://github.com/Tencent/tdesign-react/issues/897)
问题原因：react中使用useRef声明color，color.update时不触发组件更新
问题解决：update时触发setUpdateId，强制组件更新
- ffix(colorPicker): 修复在ColorTrigger输入色值时，自动format输入值并回填的问题
> fix(colorpicker): 修复在ColorTrigger输入色值时，自动format输入值并回填的问题

- src/dialog/RenderDialog.tsx
- src/dialog/_example/base.jsx
> fix(Dialog): 修复滚动失效问题

- src/space/Space.tsx
- fix(Space): 更改Space组件children属性为React.ReactNode
> SpaceProps property children should include array

- src/form/FormItem.tsx
- https://github.com/Tencent/tdesign-react/issues/850
- fix(`Form`): 修复 React 18 useEffect触发两次导致表单自动校验问题
> fix: 修复 React 18 useEffect触发两次导致表单自动校验问题

- src/table/hooks/useRowSelect.tsx
修复可选中行table组件，data为空数据时，默认全选按钮会选中的问题
目前
修复后
原因
对空数据没进行判断
解决方案
对空数据做处理
- fix(table): 修复可选中行table组件，data为空数据时，默认全选按钮会选中的问题
> fix: 🐛 修复可选中行table组件，data为空数据时，默认全选按钮会选中的问题

- src/table/hooks/useColumnController.tsx
- src/table/hooks/useColumnResize.tsx
- fix(table): 列宽拖拽调整到边界时无法重新调整
- fix(table): 多级表头场景下的列配置，无法全选
> 列宽拖拽调整到边界时无法重新调整；多级表头场景下的列配置，无法全选

- src/color-picker/components/panel/index.tsx
> fix(component): 修复切换渐变节点 hue 饱和度未更新的问题

- src/drawer/Drawer.tsx
https://github.com/Tencent/tdesign-react/issues/1115
原逻辑：开启destroyOnClose时，初次visible为false时，加载了dom且translateX为100%，当visible设置为true时style的translateX更改为0，所以初次有动效；当再次visible设置为false时，dom完全清除，再次visible设置为true，导致dom和translateX(0)同时生效（因为style计算逻辑直接写在了fc内，没有使用setState），所以动效消失
解决：在visible生效后，使用setState更新translateX，时间上先渲染dom，后设置样式
- fix(drawer): 修复开启 destroyOnClose 时多次打开关闭时动效丢失问题
> fix(drawer): 修复开启 destroyOnClose 时多次打开关闭时动效丢失问题

- CHANGELOG.md
- package.json
> chore: publish 0.37.1

- src/tree/useStore.ts
"fix #1140"
[#1140](https://github.com/Tencent/tdesign-react/issues/1140)
1、更新tree组件的data时，需要保持展开、高亮及check选中的状态
[问题还原链接](https://codesandbox.io/s/tdesign-react-demo-forked-j7jq8f?file=/src/demo.jsx:999-1007)
2、更改了tree组件useStore中的hook
3、实现的改动：
-fix(Tree):更改data、expanded、actived或checked选项时，会保留原始的状态
> perf(tree): inherit props status while changing the data

- src/select-input/useOverlayStyle.ts
> feat: 二次点击select调整为关闭面板

- src/color-picker/components/panel/index.tsx
- src/date-picker/hooks/useSingleValue.tsx
- src/hooks/useControlled.ts
更新`useControlled`方法类型定义，更多类型自动推导
```ts
type A = {
popupVisible: boolean;
onPopupVisible: (visible: boolean, ctx: any) => void;
};
const props: A = {
popupVisible: false,
onPopupVisible: () => {},
};
const [visible, setVisible] = useControlled(props, 'popupVisible', props.onPopupVisible, {
defaultPopupVisible: false,
a: '123',
});
```
> feat(hooks): update useControlled hook types

- src/dropdown/Dropdown.tsx
#1184 
1、dropdown声明overlayClassName时，未继承t-dropdown属性
声明overlayClassName时，继承t-dropdown属性
> fix(dropdown): 继承dropdown样式

- CHANGELOG.md
- package.json
> chore: publish 0.38.0

- src/popup/Popup.tsx
- src/popup/__tests__/popup.test.tsx
- src/popup/hooks/useTriggerProps.ts
https://stackblitz.com/edit/react-c1z3gk?file=src%2Fdemo.jsx
content内容为空时 不应该有弹窗
> fix(popup): popup should not visible when content is empty

- src/table/hooks/useEditableRow.ts
- fix(table): 行内有多条规则时，只生效第一条规则
> fix(table): 行内有多条规则时，只生效第一条规则

- src/upload/upload.tsx
- fix(`Upload`): 修复 `onRemove` 失效问题
> fix(`Upload`): 修复 `onRemove` 失效问题

- src/layout/Aside.tsx
- src/layout/Layout.tsx
https://github.com/Tencent/tdesign-react/issues/1285
> fix(layout): fix layout custom width and height not work

- site/site.config.mjs
- src/index.ts
- src/link/Link.tsx
- src/link/README.md
- src/link/__tests__/link.test.tsx
- src/link/_example/base.jsx
- src/link/_example/disabled.jsx
- src/link/_example/hover.jsx
- src/link/_example/icon.jsx
- src/link/_example/size.jsx
- src/link/_example/theme.jsx
- src/link/_example/underline.jsx
- src/link/defaultProps.ts
- src/link/index.ts
- src/link/link.en-US.md
- src/link/link.md
- src/link/style/css.js
- src/link/style/index.js
- src/link/type.ts
> feat(Link): 新增 link 组件

- CHANGELOG.md
- package.json
> chore: publish 0.40.0

- src/form/FormItem.tsx
- src/form/form.en-US.md
- src/form/form.md
- src/form/hooks/useFormItemStyle.tsx
- src/form/type.ts
> fix: 修复 FormItem status 受控问题

- src/table/BaseTable.tsx
- src/table/PrimaryTable.tsx
- src/table/hooks/useFixed.ts
- fix(Table): [吸顶表头，最后一列有 1px 未对齐](https://github.com/Tencent/tdesign-vue-next/issues/1434)
- feat(Table): BaseTable 新增组件实例方法 `refreshTable`，用于父组件在特殊场景刷新表格 DOM 信息
- feat(Table): PrimaryTable 新增 BaseTable 的全部组件实例方法
- fix(Table): 窗口变动时，固定列阴影效果更新
> fix(table): affixed header 1px

- src/cascader/core/helper.ts
- fix(Cascader): 修复 `value` 不是 options 的健值会报错 ([issue #1293](https://github.com/Tencent/tdesign-react/issues/1293))
> fix: cascader getFullPath robust

- CHANGELOG.md
- package.json
> chore: publish 0.40.4

- src/dropdown/__tests__/dropdown.test.tsx
https://github.com/Tencent/tdesign-react/issues/1280
test(dropdown): add dropdown test
> test(dropdown): add dropdown test

- src/alert/Alert.tsx
- src/alert/__tests__/alert.test.tsx
- src/alert/_example/operation.jsx
- src/alert/alert.md
- src/alert/type.ts
fix #1333
- [] 日常 bug 修复
#1333 
- fix(Alert): 增加关闭动画 && 修复 onClosed 回调事件
> fix(alert): 修复 onClosed 事件回调

- src/collapse/CollapsePanel.tsx
- src/collapse/__tests__/collapse.test.tsx
#1359 
#1280 
在测试过程中发现 infinite loops bug 提出修复方案。
只在 CollapsePanel 组件渲染时因 defaultExpandAll 触发一次 updateCollapseValue 即可。
- fix(collapse): fix defaultExpandAll lead to infinite loops #1359
> test(collapse): add collapse related tests #1280

- src/table/THead.tsx
- src/table/hooks/useColumnResize.tsx
1. 鼠标hover在表头分割线上的时候也是能显示拖拽光标的
1. 新增左侧判定距离，并调整对应列
- fix(table): 允许在表头分割线一定范围内触发列宽调整逻辑
> fix(table): 允许在表头分割线一定范围内触发列宽调整逻辑

- src/transfer/Transfer.tsx
- src/transfer/TransferList.tsx
#1380 
#1380 
- fix(Transfer): 修复 showCheckAll 属性
> fix(Transfer): fix show check all props

- src/input-adornment/InputAdornment.tsx
- fix(InputAdornment): 修复formItem 包裹 inputAdornment 组件 onChange 冲突问题
> fix: 修复formItem 包裹 inputAdornment 组件 onChange 冲突问题

- src/input/Input.tsx
- src/input/index.ts
- src/tag-input/TagInput.tsx
优化`Input` `TagInput`组件的`ref`属性类型提示
> perf(input): pref input & tag-input ref types

- src/table/BaseTable.tsx
- src/table/THead.tsx
- src/table/hooks/useColumnResize.tsx
- src/table/hooks/useFixed.ts
https://github.com/Tencent/tdesign-vue/issues/1428
1. 允许多级表头调整列宽
2. 抽离公共代码
3. 计算列宽时需要考虑列的minWidth设置
- fix(table): 优化列宽调整策略
> fix(table): 优化列宽调整策略

- src/tag-input/TagInput.tsx
- fix(TagInput): 修复清除按钮处罚后未调用 `onClear ` 事件
> fix: tag input clear

- src/date-picker/date-picker.md
- src/date-picker/type.ts
- src/dialog/RenderDialog.tsx
- src/image-viewer/ImageViewerModel.tsx
- src/input-number/useInputNumber.tsx
- src/range-input/range-input.md
- src/range-input/type.ts
- src/tag-input/useTagList.tsx
- fix(`TagInput`): 修复 react 16 版本 event 对象缺失 code 属性键盘导致事件判断错误
- fix(`DatePicker`): 修复 disabled 文档问题
> fix: 修复 react 16 版本 event 对象缺失 code 属性判断错误

- CHANGELOG.md
- package.json
> chore: publish 0.42.1

- src/dialog/RenderDialog.tsx
- fix(Dialog): 修复初次点击内容区域移到 mask 区域后关闭弹窗问题
> fix: 修复初次点击内容区域移到 mask 区域后关闭弹窗问题

- CHANGELOG.md
- package.json
> chore: publish 0.42.2

- src/cascader/hooks.tsx
- src/input/Input.tsx
- src/input/_example/format.jsx
- src/input/_example/max-length-count.jsx
- src/input/_example/status.jsx
- src/input/defaultProps.ts
- src/input/input.en-US.md
- src/input/input.md
- src/input/type.ts
- src/input/useLengthLimit.ts
- fix(Input): 输入框达到数量 `maxlength` 时，无法删除且无法修改输入框内容，[issue#1633](https://github.com/Tencent/tdesign-react/issues/1633)
- fix(Input): `format` 实现效果有误，聚焦的时候应当恢复 format 之前的值，[issue#1634](https://github.com/Tencent/tdesign-react/issues/1634)
- feat(Input): 支持在输入框实时显示数字限制
- fear(Input): 支持对 `unicode` 字符长度的判定
> [Input] support `showLimitNumber`

- src/table/BaseTable.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1934
1. 表格在resizable=false是，基础表格的表头读取用户设置进来的默认宽度
- fix(table): 当禁用resizable时，基础表格表头默认使用用户定义的列宽
> fix(table): 当禁用resizable时，基础表格表头默认使用用户定义的列宽

- src/tree-select/TreeSelect.tsx
fix #1668
https://github.com/Tencent/tdesign-react/issues/1668
当 `valueDisplay` 和 `filterable` 同时开启时（单选模式下），输入框的值没有清空，且输入的值无法感知。
开启 `filterable` 和 `valueDisplay` 时，如果处于选择（输入状态）则不传 `valueDisplay`。
```
const internalInputValueDisplay = useMemo(() => {
// 只有单选且下拉展开时需要隐藏 valueDisplay
if (filterable && popupVisible) {
return undefined;
}
return normalizedValueDisplay;
}, [filterable, popupVisible, normalizedValueDisplay]);
```
且 `placeholder` 优先展示 `valueDisplay` 内容。
- fix(tree-select): 修复 valueDisplay 和 filterable 同时设置时的显示问题
> fix(tree-select): 修复 valueDisplay 和 filterable 同时设置时的显示问题

- src/input/Input.tsx
- src/pagination/Pagination.tsx
- src/table/TR.tsx
- fix(Input): 修复在输入框进行预渲染处于 `display: none` 状态时，宽度计算不正确问题，[tdesign-vue#1678](https://github.com/Tencent/tdesign-vue/issues/1678)
- fix(Pagination): 修复 `selectProps` warn
> fix(input): autowidth

- CHANGELOG.md
- package.json
> feat: publish 0.42.6

- src/tree-select/TreeSelect.tsx
fix #1695
https://github.com/Tencent/tdesign-react/issues/1695
支持配合自定义字段和 `TreeInstanceFunctions.getItem` 方法，解决重复节点问题。
- feat(tree-select): 暴露 treeRef 的方法
> feat(tree-select): 暴露 treeRef 的方法

- src/popconfirm/_example/describe.jsx
[#251](https://github.com/Tencent/tdesign/issues/251)
问题：官网上，带有描述文案的demo气泡框里描述字体的颜色不对
解决方案和效果：
- fix(popconfirm): 修复官网demo气泡框描述文案字体颜色
> fix: popconfirm describe text color

- src/tree-select/TreeSelect.tsx
- src/tree/TreeItem.tsx
- feat(tree-select): 优化`checkable`时点击非叶子节点也选中的问题
> feat(TreeSelect): 优化`checkable`时点击非叶子节点选中的问题

- src/table/BaseTable.tsx
- src/table/Cell.tsx
- src/table/PrimaryTable.tsx
- src/table/TBody.tsx
- src/table/TR.tsx
- src/table/_example/pagination-ajax.jsx
- src/table/_example/pagination.jsx
- src/table/_example/single-sort.jsx
- src/table/_example/style.jsx
- src/table/defaultProps.ts
- src/table/hooks/usePagination.tsx
- src/table/hooks/useRowSelect.tsx
- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
- feat(Table): 选中行功能，新增 `reserveSelectedRowOnPaginate`，用于支持在分页场景中，仅选中当前页数据，切换分页时清空选中结果，全选仅选中当前页数据
- fix(Table): 修复本地数据分页场景中，切换分页大小，`onPageChange` 事件参数返回的数据不正确问题
- fix(Table): 序号列支持跨分页显示，[issue#1726](https://github.com/Tencent/tdesign-react/issues/1726)，[tdesign-vue-next#2072](https://github.com/Tencent/tdesign-vue-next/issues/2072)
- fix(Table): 修复分页场景下，设置 max-height 和 bordered 之后，边框线位置不正确 [tdesign-vue-next#2062](https://github.com/Tencent/tdesign-vue-next/issues/2062)
> [Table] Some features and bugs

- src/dialog/defaultProps.ts
- src/dialog/dialog.en-US.md
- src/dialog/dialog.md
- src/dialog/type.ts
- src/drawer/__tests__/drawer.test.tsx
- src/drawer/defaultProps.ts
- src/drawer/drawer.en-US.md
- src/drawer/drawer.md
- src/drawer/type.ts
- src/message/message.en-US.md
- src/message/message.md
- src/message/type.ts
- src/notification/defaultProps.ts
- src/notification/notification.en-US.md
- src/notification/notification.md
- docs: 更新 Drawer/Message/Notification/Dialog 等组件文档 
- feat(Drawer): 默认不显示关闭按钮，有取消和确认按钮足矣，同其他框架保持一致
- [] 本条 PR 不需要纳入 Changelog
> 更新 Drawer/Message/Notification/Dialog 等组件文档 

- src/select-input/useSingle.tsx
- src/select/_example/custom-selected.jsx
> fix(tree-select): 修复 valueDisplay 清空按钮不展示问题

- src/popup/Popup.tsx
修复 https://github.com/Tencent/tdesign-react/issues/1750 ，排查下来问题的过程大概是这样：
1. 用户修改 input 内容，触发 input 事件
2. bitwarden 插件监听到 input 事件（捕获），同步修改 dom 属性
3. popup 监听到 mutation，执行 popper 的 update 方法
4. popper update 方法会调用 flushSync方法，强制更新一次视图
5. input 内容被刷掉，出现无法输入的问题
想了一下，Popup 同步的优先级没有那么高，加一个 setTimeout 来解决这个问题。
> fix(selectinput): 修复某些场景下select-input 无法输入的问题

- CHANGELOG.md
- package.json
> feat: publish 0.44.0

- src/form/FormContext.tsx
- src/form/hooks/useForm.ts
- src/form/type.ts
> fix: 修复 form ts 类型警告

- src/color-picker/_example/trigger.jsx
- src/color-picker/color-picker.en-US.md
- src/color-picker/color-picker.md
- src/color-picker/components/panel/index.tsx
- src/color-picker/defaultProps.ts
- src/color-picker/type.ts
- feat(ColorPicker): 新增`showPrimaryColorPreview` API 控制色彩选择条右侧主色区块的展示
> feat(ColorPicker): add showPrimaryColorPreview API

- src/common.ts
- src/input-number/_example/status.jsx
- src/input-number/defaultProps.ts
- src/input-number/input-number.en-US.md
- src/input-number/input-number.md
- src/input-number/type.ts
> fix: 修复 input-number status 默认值缺失

- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useRangeValue.ts
- fix(DatePicker): 修复右侧面板月份展示错误
> fix: 修复右侧面板月份展示错误

- src/table/FilterController.tsx
- src/table/PrimaryTable.tsx
- src/table/_example/data-sort.jsx
- src/table/_example/filter-controlled.jsx
- src/table/_example/select-multiple.jsx
- src/table/_example/select-single.jsx
- src/table/hooks/useFilter.tsx
- src/table/hooks/useRowSelect.tsx
- src/table/hooks/useSorter.tsx
同步 Vue2/Vue3 已实现 Feature，https://github.com/Tencent/tdesign-vue/pull/1891
- feat(Table): 可筛选表格，新增 `filter.popupProps` ，支持透传 Popup 组件全部属性，[tdesign-vue-next#2088](https://github.com/Tencent/tdesign-vue-next/issues/2088)
- feat(Table): 选中行表格，新增 `selectOnRowClick`，支持点击行选中，[tdesign-vue-next#1954](https://github.com/Tencent/tdesign-vue-next/issues/1954)
- feat(Table): 本地排序功能，支持对默认数据进行排序
> feat(table): some features

- src/form/FormItem.tsx
- src/form/FormList.tsx
- src/form/hooks/useInstance.tsx
> fix: 修复 formList 嵌套赋值问题

- src/table/_example/pagination.jsx
- src/table/hooks/usePagination.tsx
fix(Table): 修复本地数据分页功能中，onPageChange 参数 newData 数值不正确问题
> [Table] newData of onPageChange is not correct

- src/date-picker/hooks/useDisableDate.ts
- fix(`DatePicker`): 修复年份面板样式禁用问题
> fix: 修复 datepicker 禁用样式问题

- src/dropdown/_example/multiple.jsx
- src/tree-select/_example/base.jsx
- src/tree/TreeItem.tsx
- https://github.com/Tencent/tdesign-vue/issues/2003
- https://github.com/Tencent/tdesign-vue/issues/1997
- fix(TreeSelect): 修复选项文案过程样式的异常
- chore: 修改 dropdown 和 tree-select 相关展示示例
> fix(tree-select): label overflow

- CHANGELOG.md
- package.json
> chore: publish 0.45.3

- src/color-picker/__tests__/color-picker.test.tsx
- [#1280](https://github.com/Tencent/tdesign-react/issues/1280)
- test(color-picker): 补充测试用例
> test(color-picker): add test for color-picker

- src/color-picker/ColorPicker.tsx
哈喽，大佬们好。最近给 `color-picker` 加测试用例时发现个小问题如下：
在点开 `color-picker` 的 `popup` 后，再点开选择色值 `mode` 下拉框，然后将鼠标移出整个 `color-picker-popup`，点击一下后色值下拉框没有隐藏。可以在 [官方文档中复现](https://tdesign.tencent.com/react/components/color-picker#%E5%B8%A6%E8%A7%A6%E5%8F%91%E5%85%83%E7%B4%A0%E7%9A%84%E9%A2%9C%E8%89%B2%E9%80%89%E6%8B%A9%E5%99%A8)。
看了下源码，`color-picker` 组件中对 `popup` 进行 **显隐控制**，其中的 `useClickOutside` 的处理逻辑跟 `popup` 组件中 `useTrigger` 的处理类似。并且 `picker` 组件中传递给 `ColorPanel` 组件的 `togglePopup={setVisible}` 也没有用上，所以大佬们看看是不是可以**不用在 `picker` 组件中对 `popup` 进行显隐控制**，将控制交还给 `popup` 自己。如果可以的话，那上面的问题就能解决了。但是一定要在 `picker` 中控制 `popup` 显隐逻辑的话，可能需要将 `visible` 带进去色值选择的下拉中来正确处理隐藏逻辑了。
> fix(color-picker): 选择色值mode的popup隐藏问题

- src/hooks/useResizeObserver.ts
- src/table/EditableCell.tsx
- [] 日常 bug 修复
- fefactor(Table): 可编辑单元格，去除非必要路径比较代码
- feat: useResizeObserver 支持元素变化
> [Table] remove editable-cell useless code; useResizeObserver support container change

- src/cascader/__tests__/cascader.test.tsx
- [ ☑️] 测试用例
[#1280](https://github.com/Tencent/tdesign-react/issues/1280) 
> test(cascader): add test for cascader

- src/table/BaseTable.tsx
大佬们好，在虚拟列表的使用中发现点问题如 `gif` ：
操作路径描述（可在官网文档复现）：
1. 将虚拟表格滚动到一定高度
2. 稍微快速的用鼠标拖拽滚动条置顶再松开，表格内容白屏
调试代码时发现这个判断条件会导致上述问题，也就是 `top` 为 `0` 且又等于 `lastScrollY` 时就没有执行表格展示的逻辑函数 `handleScroll`。
> fix(table): 拖拽滚动条回到顶部白屏问题

- src/switch/__tests__/switch.test.tsx
> test(switch): coverage

- postcss.config.js
> fix: 修复 csscano 导致css文件丢失末尾分号问题

- src/cascader/Cascader.tsx
- src/select/base/Select.tsx
- src/tree-select/TreeSelect.tsx
- https://github.com/Tencent/tdesign-react/issues/1987
- fix(TagInput): 修复0.45.4版本后TagInput增加blur行为导致Select/Cascader/TreeSelect无法过滤多选的问题
> fix(Select): fix multiple filterable

- CHANGELOG.md
- package.json
> chore: publish 1.0.1

- src/dialog/Dialog.tsx
- src/dialog/_example/modal.jsx
- src/dialog/_example/plugin.jsx
[https://github.com/Tencent/tdesign-react/issues/2075](https://github.com/Tencent/tdesign-react/issues/2075)
[DialogPlugin] onCloseBtnClick参数无效
- fix(Dialog): 修复`onCloseBtnClick`事件无效的问题
> fix(dialog): onCloseBtnClick props

- src/tag-input/TagInput.tsx
- src/tag-input/useTagList.tsx
- #2112
输入一个字符，按退格会删除最后一个tag
输入多个字符，字符全部删除后按两次退格才会删除tag
判断删除tag的逻辑有问题
- fix(TagInput): 修复基于`TagInput`的组件使用筛选时删除关键词时会删除已选值的问题
> fix(Select): 修复输入字符按退格键删除tag的bug

- src/image/Image.tsx
Image support ref props
BREAKING CHANGE: 🧨 none
✅ Closes: #2193
- close #2193
> fix: 🐛 Image support ref props

- src/back-top/BackTop.tsx
- src/hooks/useDefaultProps.ts
remove backTopDefaultProps
BREAKING CHANGE: 🧨 none
✅ Closes: none
> refactor: support ref props & remove backTopDefaultProps

- src/menu/MenuContext.ts
- src/menu/MenuItem.tsx
https://github.com/Tencent/tdesign-vue-next/issues/2318
- feat(Menu): 侧边导航菜单收起时，Tooltip 展示菜单内容
> feat: support show tooltip when side menu collapsed

- src/tree/TreeItem.tsx
fix #2181
修复当label传入为 ReactNode时， 页面item hover 会渲染出 [object Object]的bug
> fix(tree-select): fix the bug in rendering when the label is Reactnode

- src/dialog/hooks/useLockStyle.ts
- src/drawer/hooks/useLockStyle.ts
- https://github.com/Tencent/tdesign-react/issues/2279
Dialog 组件和 Drawer 组件在 SSR 环境下报错
解决方案：在 useLayoutEffect 里进行 dom 创建
- fix(Dialog): 修复 Dialog 在 SSR 环境下报错
- fix(Drawer): 修复 Drawer 在 SSR 环境下报错
> fix: useLockStyle 在 SSR 环境下报错

- src/color-picker/components/panel/format/index.tsx
- src/color-picker/components/panel/index.tsx
- src/color-picker/type.ts
- https://github.com/Tencent/tdesign-vue-next/issues/2904
- https://github.com/Tencent/tdesign-vue-next/issues/2903
- https://github.com/Tencent/tdesign-vue/issues/2498
- fix(ColorPicker): 初始化为渐变模式时 支持空字符串作为初始值
- fix(ColorPicker): 修复 `recentColors` 等字段的类型问题
- fix(ColorPicker): 修复内部下拉选项未透传 `popupProps` 的缺陷
> fix(ColorPicker): 初始化为渐变模式时 支持空字符串作为初始值

- CHANGELOG.md
- package.json
> chore: publish 1.1.11

- src/input/input.en-US.md
- src/input/input.md
- docs(Input): 输入框的值 类型移除 Number
> docs(Input): value type remove Number

- src/popconfirm/Popcontent.tsx
- src/popconfirm/__tests__/popconfirm.test.tsx
https://github.com/Tencent/tdesign-react/issues/2360
当 `confirmBtn/cancelBtn` 值类型为 `Object` 时未透传。
修改后测试结果：
```js
<Popconfirm theme={'default'} 
content={'您确定要提交吗'} 
confirmBtn={'确认提交'} 
// object 透传
cancelBtn={{onClick: ()=>{console.log("test")}, content: "test", theme: "danger"}}
>
<Button theme="default" variant="outline">
按钮样式（属性-字符串）
</Button>
</Popconfirm>
```
- fix(Popconfirm): 当 `confirmBtn/cancelBtn` 值类型为 `Object` 时未透传
> fix(Popconfirm): button props propagation

- src/table/EditableCell.tsx
- src/table/hooks/useEditableRow.ts
- fix(Table): 可编辑表格场景，支持设置 `colKey` 值为链式属性，如：`a.b.c`
> fix(table): editable cell table support setting colKey to be like `a.b.c`

- src/time-picker/panel/SinglePanel.tsx
- src/time-picker/time-picker.en-US.md
- src/time-picker/time-picker.md
- src/time-picker/type.ts
- feat(TimePicker): disableTime回调新增毫秒参数
- feat(TimePicker): 优化展示不可选时间选项时滚动到不可选选项的体验
> feat(timepicker): disabletime callback add ms params

- src/popup/Popup.tsx
> fix: 🐛 replace defaultProps with useDefaultProps

- CHANGELOG.md
- package.json
> chore: publish 1.1.16

- src/tree/Tree.tsx
- src/tree/hooks/useTreeConfig.ts
- src/tree/hooks/useTreeVirtualScroll.ts
- fix(Tree): 修复开启虚拟滚动时部分场景下节点回滚的交互异常问题
> fix(Tree): virtual nodes  rescroll again when wrapped in css transition

- src/date-picker/DatePicker.tsx
- src/date-picker/base/Header.tsx
- src/date-picker/panel/PanelContent.tsx
#2439
由于 DateTable 接受的 onMouseEnter 事件（在顶部 DatePicker 中声明）会触发 set inputValue，从而导致hover 日期 Cell 后，所有子组件重新渲染。
使用 `memo` 缓存 `DatePickerHeader`，使用 `useCallback` 缓存传入 `DatePickerHeader` 的三个函数
- fix(date-picker): hover cell 造成不必要的渲染
> fix(date-picker): hover cell 造成不必要的渲染

- src/dialog/Dialog.tsx
css 的样式是加在最内层的 dom 上的，也就是 DialogCard 这个 Component 上，但是由于 内层的 CSSTransition 没有绑定 onExited 事件，因此在 transition 内部的 removeClass 中就会删掉 class，但是组件还没有被 display 为 false，要等到外层的这个 setState 触发完成后才会触发 onExited 设置 display。导致组件闪烁
- fix(Dialog): 修复 dialog 闪烁的问题
> fix(dialog): 修复 tdesign react dialog 闪烁的问题

- src/select/_example/remote-search.jsx
- src/select/_example/scroll-bottom.jsx
- src/select/base/Option.tsx
- src/select/base/Select.tsx
- fix(Select): 修复多选丢失title的问题
- fix(Select): 开启远程搜索时不执行内部过滤
> fix(Select): add title for multiple option

- src/table/PrimaryTable.tsx
- src/table/hooks/useColumnResize.tsx
- fix(Table): 点击行展开/点击行选中，修复 `expandOnRowClick`和 `selectOnRowClick` 无法独立控制行点击执行交互问题 [issue#3254](https://github.com/Tencent/tdesign-vue-next/issues/3254)
> [Table] fix expandOnRowClick and selectOnRowClick can not control reaction alone

- src/form/FormList.tsx
- src/form/__tests__/form-list.test.tsx
https://github.com/Tencent/tdesign-react/issues/2403
- fix(FormList): 
- 忽略首次执行，避免setFieldsValue异常
- 修复form reset无效
> fix(FormList): 修复FormList组件使用form setFieldsValue、reset异常

- CHANGELOG.md
- package.json
> chore: publish 1.2.2

- CHANGELOG.md
- package.json
> chore: publish 1.2.4

- src/table/EditableCell.tsx
- fix(Table): 单元格在编辑模式下，保存的时候对于链式的colKey处理错误，未能覆盖原来的值
> fix(Table): 链式colKey在可编辑表格保存的时候设值错误

- src/tabs/Tabs.tsx
- [#2497](https://github.com/Tencent/tdesign-react/issues/2497)
- fix(Tabs): 修复使用 list 传 props 且 destroyOnHide 为 false 下， 会丢失 panel 内容的问题
> fix(Tabs):  When using list props and destroyOnHide is false, the panel content is lost (#2497)

- src/menu/HeadMenu.tsx
- src/menu/__tests__/menu.test.tsx
- src/tabs/TabNav.tsx
#2349 
修复菜单expandType默认模式下menuitem传递onClick不触发的问题
- fix(menu): 修复菜单expandType默认模式下menuitem传递onClick不触发的问题
> fix(Menu): fix menu expandType default mode the menuitem to pass onClick not trigger

- src/timeline/TimelineItem.tsx
- src/timeline/timeline.en-US.md
- src/timeline/timeline.md
Close #2495 .
Timeline.Item 新增点击事件回调
- feat(Timeline): TimelineItem添加点击事件。
> feat(Timeline): timelineitem add trigger on click

- src/rate/Rate.tsx
#2550 
要解决的具体问题: [Rate] 组件鼠标快速移动，会出现多个text显示的问题
解决办法: 把 `RateIcon` 组件移动到 `Rate` 组件外面
- fix(rate): 修复鼠标快速移动，会出现多个text显示的问题
> fix(rate): #2550 鼠标快速移动，会出现多个text显示的问题

- CHANGELOG.md
- package.json
> chore: publish 1.2.7

- src/tree/Tree.tsx
- #2553 
`Before:`
Tree组件默认下不添加activable参数，会导致不触发onClick事件
`After:`
修复不添加activable参数也可触发onClick事件
- fix(Tree): 修复不添加activable参数也可触发onClick事件
> fix(Tree): fix Tree don't use activable, onClick not trigger

- src/table/_example/editable-row.jsx
- #2558 
修复可编辑表格编辑组件之间的联动不生效。
- docs(Table): 修复可编辑表格编辑组件之间的联动不生效。
> docs(table): the linkage between editable table editing components es not take effect

- src/popup/Popup.tsx
fix popup ref types
问题比较小，就不另外提 issue 了，直接修复下。
之前那个 pr，提交信息忘记脱敏了。用这个吧
PopupRef 的方法只定义了三个，然而实际上有五个。这里帮补充一下。
另外 PopupRef 的方法注释原本是用 // 的，这样会导致在调用时不能鼠标 hover 时显示出来。现改为 /** */。
- fix(Popup): 修复PopupRef的类型缺失问题
> fix(popup):  fix ref types

- src/notification/NotificationList.tsx
https://github.com/Tencent/tdesign-react/assets/65376724/4c5bdf27-dc8c-41c2-a3ed-8f9e51f9f5af
- 连续弹两个notification,第一次实际只显示一个。
- fix(Notification): 修复连续弹两个Notification,第一次实际只显示一个。
> fix(notification): fix Notification triggered for the first time in React 18 concurrent mode

- src/notification/NotificationList.tsx
- src/notification/NotificationPlugin.ts
使用flushSync在useEffect中会警告，现在替换flushSycn，改用循环setTimeout来处理。
- fix(Notification): 使用flushSync在useEffect中会警告，现在替换flushSycn，改用循环setTimeout来处理。
> fix(notification): fix notification, replace flushSync

- src/select/base/Select.tsx
- fix(Select): 修复`inputchange`事件context参数异常的问题
> fix(Select): fix select input change params

- src/date-picker/DatePicker.tsx
- src/date-picker/panel/PanelContent.tsx
日期选择器面板，右上角的这三个快速切换的按钮。只能切到当前月份/上一月/下一月，无法继续往前或往后切换。
原因在于 onJumperClick 没有及时更新，PaginationMini 持有的 onChange 还是老的 onJumperClick（持有的老的 year 和 month），所以每次点击都在以当前 year 和 month 做加减。这里的 useCallback 需要根据 year 和 month 来更新
> fix(date-picker): 🐛 date picker PaginationMini select

- CHANGELOG.md
- package.json
> chore: publish 1.3.1

- src/pagination/__tests__/paginationMini.test.tsx
add pagination paginationMini component test
> add pagination paginationMini component test

- src/popup/Popup.tsx
- #2391 
上次pr的prevVisible，只有显示日期时触发，后面滚动时无法触发updateScrollTop，导致滚动到底部会跳到顶部的bug。 
- fix(date-picker): 修复选择年份的时候滚动到底部会闪回顶部。
> fix(date-picker): fix date-picker scroll the bottom jump scrollTop the bug

- src/tree/TreeItem.tsx
- src/tree/__tests__/tree.test.tsx
无
树结点自定义 icon 的时候，如果不控制 expand state 的状态由子节点来得到的话，则会导致所有的图标颜色全部切换为 primary 的蓝色。
- fix(tree): 树组件结点的 open class 状态控制逻辑错误导致的样式异常
> fix(Tree): node open state class condition error

- src/common.ts
- src/tree/_example/vscroll.jsx
- fix(Tree): 指定滚动到特定节点API中的`key`和`index`应为可选
> fix: index and key of ScrollToElementParams should be optional

- CHANGELOG.md
- package.json
> chore: release 1.4.0

- src/auto-complete/HighlightOption.tsx
- src/auto-complete/OptionList.tsx
- src/auto-complete/_example/filter.jsx
> fix(auto-complete): using lodash escapeRegExp transform keyword text 

- src/select-input/useOverlayInnerStyle.ts
- #2642 
修复popup内容宽度计算问题
- fix(SelectInput): 修复SelectInput的popup内容宽度计算问题
> fix(select-input): fix select-input popup content width calculation problem

- src/image-viewer/ImageViewer.tsx
- src/image-viewer/ImageViewerModal.tsx
- src/image-viewer/__tests__/image-viewer.test.tsx
- src/image-viewer/defaultProps.ts
- src/image-viewer/hooks/useImageScale.ts
- src/image-viewer/hooks/useScale.ts
- src/image-viewer/image-viewer.en-US.md
- src/image-viewer/image-viewer.md
- src/image-viewer/type.ts
- https://github.com/TDesignOteam/tdesign-api/pull/215
图片预览添加默认的缩放比例和按下 ESC 时是否触发图片预览器关闭事件
- fix(ImageViewer): 图片预览添加默认的缩放比例和按下 ESC 时是否触发图片预览器关闭事件
> feat(image-viewer): feat add defaultScale and closeOnEscKeydown

- src/dropdown/DropdownMenu.tsx
1. 跟进大部分用户反馈 不希望left direction的场景下将展开箭头与文案位置互换 去掉这部分特殊处理
处理前
处理后
2. 更新common
- feat(Dropdown): 移除对left的item样式特殊处理
- fix(DatePicker): 修复日期选择禁用后，后缀图标颜色改变的问题 @HaixingOoO 
> feat(dropdown): remove dropdown left special style

- CHANGELOG.md
- package.json
> chore: release 1.4.1

- src/cascader/components/Item.tsx
由于上次修复的是多选的，没考虑到单选是`li`的onClick事件触发选中，现修复Cascader单选过滤不触发选中
- fix(Cascader): 修复`1.4.2` Cascader单选过滤下不触发选中的缺陷
> fix(Cascader): fix Cascader single filter not trigger selected

- src/cascader/components/Item.tsx
- src/cascader/core/effect.ts
- #2674
修复Cascader的`trigger=hover`过滤之后，选择操作存在异常bug
- fix(Cascader): 修复Cascader的`trigger=hover`过滤之后，选择操作存在异常bug
> fix(Cascader): fix Cascader trigger of hover the bug

- src/cascader/hooks.tsx
- src/cascader/interface.ts
- src/tree-select/useTreeSelectUtils.ts
- src/tree/Tree.tsx
- src/tree/TreeItem.tsx
- src/tree/hooks/TreeDraggableContext.tsx
- src/tree/hooks/useDraggable.tsx
- src/tree/hooks/useStore.ts
- src/tree/hooks/useTreeVirtualScroll.ts
- src/tree/interface.ts
因为改动后的common Tree Store 影响部分React Tree的正常操作, React 目前使用的还是原版本的Tree , 此前一直使用另一个临时分支，影响部分更新common的PR的正常运作,暂时修改 common tree 的路径 后续同步了common tree的改动后再做恢复 此PR合并后可以正常同步最新的common develop分支
> chore: use common tree v1 temporarily

- src/dialog/Dialog.tsx
- src/dialog/type.ts
- Tencent/tdesign-react#2619
Tencent/tdesign-react#2619
`Dialog` 组件的 className 存在实现问题，导致其会被挂在到多个节点。
- fix(Dialog): 修复了 Dialog 的 `className` 引入时的多次节点挂载实现错误
添加了 `dialogClassName` 用于处理内部 dialog 样式，`className` 将仅被挂载至 ctx 元素上。建议之前通过 `className` 直接修改弹窗本体样式的用户切换使用为 `dialogClassName`。
> fix(dialog): resolve `styledProps` pass frame wrong

- CHANGELOG.md
- package.json
> chore: release 1.5.0

- src/tree/Tree.tsx
- src/tree/TreeItem.tsx
- https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-jvj76h?file=%2Fsrc%2Fdemo.jsx%3A49%2C3
- fix(Tree): 修复设置 `keys.children` 后展开图标没有正常变化的问题
> fix(Tree): fix tree expand icon status when keys.children is set

- src/dialog/hooks/useDialogPosition.ts
- #2748 
- fix(Dialog): 修复`useDialogPosition`渲染多次绑定事件
> Fix(Dialog): fix render multiple binding events

- src/sticky-tool/StickyItem.tsx
- src/sticky-tool/StickyTool.tsx
- fix(StickyTool): `StickyTool` replace `defaultProps` with `useDefaultProp`
> fix: 🐛 replace defaultProps with useDefaultProp

- src/tree/TreeItem.tsx
- src/tree/__tests__/tree.test.tsx
- #2609 
修复`Tree` 自定义label `setData` 没有渲染的问题
- fix(Tree): 修复`Tree` 自定义label `setData` 没有渲染的问题
> fix(Tree): fix setData not render tree-item

- src/popup/Popup.tsx
- src/select/base/Select.tsx
- 选中值后 会因为滚动触发更新 导致滚动加载无法正常完成
- updateScrollTop只在popup visible变为true 执行即可 目前因为updateScrollTop会多次重复执行 
- fix(Select): 修复通过滚动加载选项选中后滚动行为异常的问题
> fix(select): auto scroll behavior

- src/form/FormList.tsx
- #2040
- #2787 
- before
多个`FormList` `fieldsTaskQueueRef.current` 在后续pop()删掉第一个数组，`fields`改变会一直进入`useEffect`，循环里会调用`callback`，`fieldsTaskQueueRef.current`会持续添加，然后导致内存爆掉，页面卡死
- after
然后 `fieldsTaskQueueRef.current` 在前面pop()可修复多个`FormLIst`卡死的问题
修复多个`FormList` 卡死的问题
- fix(FormList): 修复多个`FormList` 卡死的问题
> fix(FormList): fix multiple FormList stuck

- .vscode/settings.json
- src/select/_example/multiple.jsx
- src/select/base/Select.tsx
- src/select/type.ts
- #2789
- fix(select): 修复 `onRemove` 不工作的问题
> fix(select): fix onRemove method does not work

- src/image/Image.tsx
#2810
参数未传递到正确的节点上
- fix(image): referrerpolicy 参数被错误传递到外层 div 上，实际传递目标为原生 image 标签
> fix(image): forget pass referrerpolicy to real image tag props #2810

- src/guide/Guide.tsx
- createPortal 在 SSR 场景不会执行，在 SSR 中使用 Guide 初始化时会找不到节点，导致高亮渲染位置错位，调整为useLayoutEffect 保证在 Client 运行
- fix(Guide): 修复`Guide`组件在`SSR`场景初始化渲染位置异常的问题
> fix(Guide): fix guide initial position in ssr

- CHANGELOG.md
- package.json
> chore: release 1.6.0

- CHANGELOG.md
- package.json
> chore: release 1.7.0

- package.json
- src/tag-input/__tests__/vitest-tag-input.test.jsx
- src/tag-input/useTagList.tsx
- fix(TagInput): 修复没有透传`tagProps`到折叠选项的问题
> fix(tag-input): tag props should effect collapsed tag

- src/color-picker/hooks/useStyles.ts
修复方案：将原来 left 的 px 调整为百分比
- fix(color-picker): 修复切换预览颜色时，通道按钮位置不变的问题
> fix(color-picker): 修复切换预览颜色时，通道按钮位置不变的问题

- src/pagination/Pagination.tsx
- src/pagination/__tests__/pagination.test.tsx
- fix(Pagination): 修复当前页输入小数后没有自动调整的问题
> fix(pagination): auto truncate number after entering

- src/table/hooks/useRowSelect.tsx
卸载表格时由于 currentData 先卸载，导致后续 select 报错
- fix(Table): 修复卸载表格时数据为空导致报错的异常
> fix(Table): fix error occur when table is unmounted

- src/tree-select/TreeSelect.tsx
- #2257 
- fix(TreeSelect): 修复需要通过 `treeProps` 设置 `keys` 属性才生效的问题
> fix(treeselect): fix keys not pass pass through to default tree store

- src/upload/hooks/useUpload.ts
- #2893
- `before`:
之前手动自定义上传百分比进度只是修改`uploadValue`里面的值，没触发更新`displayFiles`
- `after`:
后面添加个一个`forceUpdate`来手动更新时，强制触发更新`displayFiles`
- fix(Upload): 修复手动修改上传进度的bug
> fix(Upload): fix manual uploadFilePercent not update display

- src/form/FormItem.tsx
- src/form/hooks/useWatch.ts
上一次修复 [issue](https://github.com/Tencent/tdesign-react/issues/2809) 在`useWatch`判断name是否相等 [PR](https://github.com/Tencent/tdesign-react/pull/2853) ，导致监听`FormList`不会触发
解决方案:
`FormItem`添加`name`依赖来触发`notify`,然后在`useWatch`的存的值转换成`string`来对比可以解决`setState`在一些数组或者
对象中的导致的re-render问题
- fix(Form): `FormItem`的修改，没有触发监听`FormList`的`useWatch`
> fix(Form): formitem change not trigger useWatch of formlist

- src/cascader/components/Item.tsx
- src/cascader/core/className.ts
- src/cascader/core/effect.ts
- src/cascader/hooks.tsx
- #2910
`checkStrictly`模式下，`filterable`列表的父节点不显示,是在`treeNodesEffect`的函数里判断父节点都不显示
所以在`treeNodesEffect`的函数修复
- fix(Cascader): 修复 `Cascader` 搜索时 `checkStrictly` 模式父节点不显示
> fix(cascader): fix Cascader filterable checkStrictly parent node not display

- src/checkbox/CheckboxGroup.tsx
- src/checkbox/__tests__/checkbox.test.tsx
- fix(checkbox): 无法渲染为值为 0 的选项
> fix(checkbox): render `0` number option as string

- src/form/FormItem.tsx
- src/form/FormList.tsx
fix #2942
https://github.com/Tencent/tdesign-react/issues/2942
- fix(form): resolve shouldUpdate circular trigger problem
> fix(form): resolve shouldUpdate circular trigger problem

- src/table/hooks/useColumnResize.tsx
- #2928
修复阻止鼠标右键表格列宽拖拽
- fix(Table): 修复阻止鼠标右键表格列宽拖拽
> fix(Table): fix table resize drag prevent right click

- CHANGELOG.md
- package.json
- src/table/hooks/useColumnResize.tsx
> chore: release 1.7.6

- src/popup/popup.en-US.md
- src/popup/popup.md
- #2983
- docs(Popup): add FAQ
> docs(Popup): add FAQ

- src/input/Input.tsx
- src/input/__tests__/input.test.tsx
- https://github.com/Tencent/tdesign-vue/issues/3228
- fix(Input): 修复禁用状态下仍可以切换明文密文的问题
> fix(input): disable password toggle when input disabled

- src/image-viewer/ImageViewer.tsx
- src/image-viewer/ImageViewerModal.tsx
- src/image-viewer/__tests__/image-viewer.test.tsx
- src/image-viewer/defaultProps.ts
- src/image-viewer/image-viewer.en-US.md
- src/image-viewer/image-viewer.md
- src/image-viewer/type.ts
- https://github.com/Tencent/tdesign-vue-next/pull/4405
- feat(Imageviewer): Imageviewer support attach
> feat(Imageviewer): Imageviewer support attach

- src/table/TBody.tsx
- 修复前未正常居中
- 修复后正常居中
- props.tableWidth是 MutableRefObject，current才是具体的number，此前直接使用 tableWidth 导致部分width 设置无法正常生效
- fix(Table): 修复空数据下展示内容没有居中展示的问题
> fix(Table): fix empty content center position

- src/icon/icon.en-US.md
- src/icon/icon.md
> chore: fix icon page render

- src/date-picker/DatePicker.tsx
- src/date-picker/DatePickerPanel.tsx
- src/date-picker/base/Footer.tsx
- src/date-picker/date-picker.en-US.md
- src/date-picker/date-picker.md
- src/date-picker/defaultProps.ts
- src/date-picker/panel/ExtraContent.tsx
- src/date-picker/panel/RangePanel.tsx
- src/date-picker/panel/SinglePanel.tsx
- src/date-picker/type.ts
- src/hooks/useUpdateEffect.ts
- https://github.com/Tencent/tdesign-vue-next/pull/4411
- feat(DatePicker): 新增 `needConfirm` API，支持日期时间选择器不需要点击确认按钮保存选择时间
> feat(DatePicker): add needConfirm api

- src/hooks/useDragSorter.tsx
- fix([TagInput](https://tdesign.tencent.com/react/components/tag-input)): 如文档 [demo](https://tdesign.tencent.com/react/components/tag-input) 拖拽示例，新增数据拖拽会后丢失，因为 useRef 导致无法更新 onDragSort 函数，但是函数上下文已经被改变，旧的 onDragSort 函数上下文拿旧数据 tags1 ，导致拖拽调整顺序无法拿到最新的数据 tags1 进行正确的操作，还存在有时候拖拽无法交换的小问题，但起码不会丢失用户输入的内容
> fix(TagInput): onDragSort capture context error caused by useRef

- src/hooks/useUpdateLayoutEffect.ts
- src/tree/hooks/useStore.ts
最近升级的版本，tree 如果用了 icon 自定义图标，tree 的点击展开会出问题，单点图标去展开，第一次还能生效展开/收起，后面就不生效了。
https://codesandbox.io/p/sandbox/tdesign-react-demo-n6mxjv
- fix(Tree): `Tree` 的数据更新需要使用 `useLayoutEffect` ,现在使用 `useUpdateLayoutEffect` 来修复上次更新使用 `useUpdateEffect` 的Bug
> fix(Tree): use useUpdateLayoutEffect fix bug

- src/hooks/useDrag.ts
https://github.com/Tencent/tdesign-react/issues/3041
- fix(ColorPicker): 修复 `slider` 部分在鼠标移入移出的缺陷
> fix(ColorPicker): fix slider mouse move behavior bug 

- src/popup/Popup.tsx
https://jsfiddle.net/c6zn73ws/16/
当trigger元素为`display:none`时，会导致hide时popup定位闪烁隐藏；
修复方法:
1.`visible=true`时才更新`popup`定位
2.判断trigger元素为`display:none`时不更新定位
- fix(Popup): 修复`popup`某些场景下，隐藏时定位会闪烁
> fix(Popup): fix popup invisible position bug

- src/select/_example/base.tsx
- src/select/base/Option.tsx
- fix(Select): 修复自定义`content`时的渲染的问题
> fix(Select): fix option title

- src/popup/Popup.tsx
- src/select-input/useMultiple.tsx
- src/select-input/useSingle.tsx
- fix(Popup): 修复`panel` 为 null 场景下的部分事件回调缺失和错误的问题
> fix(Popup): fix panel null bug

- CHANGELOG.md
- package.json
> chore: release 1.8.1

- src/card/Card.tsx
fix #2997
https://github.com/Tencent/tdesign-react/issues/2997
- fix(card): loading属性增加TNode支持
- [x 文档已补充或无须补充
> fix(card): loading属性增加TNode支持

- src/button/button.en-US.md
- src/button/button.md
- src/button/defaultProps.ts
- src/button/type.ts
- src/form/Form.tsx
- src/form/defaultProps.ts
- src/form/form.en-US.md
- src/form/form.md
- src/form/type.ts
- https://github.com/TDesignOteam/tdesign-api/pull/409
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
`Form` support attribute `id`,`Button` support attribute `form`
- feat(Form and Button): `Form`支持原生属性`id`,`Button` 支持原生属性`form`
> feat(form button): form and button support native attribute

- src/popup/Popup.tsx
fix #3090
https://github.com/Tencent/tdesign-react/issues/3090
> fix(popup): popup useMutationObservable watch #text node problem

- src/tree/Tree.tsx
- src/tree/TreeItem.tsx
- src/tree/_example/draggable.tsx
- src/tree/hooks/TreeDraggableContext.tsx
- src/tree/hooks/useDraggable.tsx
- src/tree/tree.en-US.md
- src/tree/tree.md
- src/tree/type.ts
- feat(Tree): 新增 `allowDrop` API，用于限制拖拽的场景使用
> feat(Tree): support allowDrop API

- CHANGELOG.md
- package.json
> chore: release 1.9.0

- src/dropdown/DropdownMenu.tsx
- src/dropdown/_example/child.tsx
- https://github.com/Tencent/tdesign-react/issues/3105
- fix(dropdown): correct the top of the dropdown menu when has panelTopContent
> fix(dropdown): correct the top of the dropdown menu when has panelTopContent

- src/image-viewer/hooks/useRotate.ts
要解决的问题：修复图片预览旋转多次之后，点击重置后，图片旋转太多次的问题
实现方案：修改 useRotate 这个 hooks， 旋转多次之后， 寻找到离整除 360° 最近的角度，进行旋转， 而不是强制的将角度设置为 0
修改前: 
[screencast-tdesign_tencent_com-2024_09_18-17_41_37.webm](https://github.com/user-attachments/assets/81f307b2-f2e5-4121-bfef-878a14668af9)
修改后：
[screencast-localhost_15000-2024_09_18-17_42_35.webm](https://github.com/user-attachments/assets/ae8ecc7f-ec28-4d32-aa24-df37e36b745e)
1. 修复图片预览旋转多次之后，点击重置后，图片旋转太多次的问题
- fix(组件名称): ImageViewer
> fix: fix the error of image rotating too many times after reseting image

- src/date-picker/panel/RangePanel.tsx
- src/time-picker/TimeRangePicker.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4566
- https://github.com/Tencent/tdesign-vue-next/issues/4427
- https://github.com/Tencent/tdesign-vue-next/issues/4382
- fix(DateRangePicker): 修复日期区间选择器配置时间相关格式时，没有正确处理`defaultTime`的问题
- fix(DatePicker): 修复周选择器下，年份边界日期返回格式错误的问题
- feat(TimePicker): 支持时间区间选择器自动调整左右区间
> fix(datepicker): range picker default time bug

- src/tabs/TabBar.tsx
- src/tabs/TabNav.tsx
- #3132
- fix(Tabs): 修复`TabPanel` 的`label`改变时，激活的选项卡底部横线没更新
> fix(Tabs): fix tabs tabPanel label change tabbar not update

- src/_util/helper.ts
- src/select/base/Select.tsx
fix #3135
https://github.com/Tencent/tdesign-react/issues/3135
修正计算 `firstSelectedNode` 到顶部节点的问题
- fix(select): initially scroll to the active item in OptionGroup
> fix(select): initially scroll to the active item in OptionGroup

- CHANGELOG.md
- package.json
> chore: release 1.9.2

- src/select/_example/custom-selected.tsx
- src/select/base/Select.tsx
- https://github.com/Tencent/tdesign-react/issues/3151
- fix(Select): 修复`valueDisplay`下的`onClose`回调问题
> fix(Select): fix valueDisplay onClose callback

- src/typography/ellipsis/Truncate.tsx
- #3152 
目前发现个问题，就是每个字符切割的话，会导致英文单词换行时是单个字符换行，需要考虑一下
- fix(Typography): fix `Typography` Ellipsis bug
> fix(Typography): fix Typography Ellipsis bug

- src/form/hooks/useInstance.tsx
- src/form/utils/index.ts
- #3129
fix form getFieldsValue in formList or formItem data 
- fix(Form): 修复 `formList` 或 `formItem` 数据中的 `getFieldsValue` 问题
> fix(Form): fix form getFieldsValue bug

- src/tag-input/__tests__/vitest-tag-input.test.jsx
- src/tag-input/useTagList.tsx
- fix(tag-input):修复在`readonly`模式下仍可以通过Backspace按键删除已选项的缺陷
> fix(tag-input): prevent backspace event in readonly mode

- src/cascader/core/effect.ts
- feat(Cascader): 单选模式下当`trigger`为`hover`时，选中选项后自动关闭面板
> feat(cascader): click item to close panel when trigger is hover

- src/drawer/Drawer.tsx
- src/drawer/__tests__/drawer.test.tsx
- fix(Drawer):  无法使用 `FooterButton` 属性自定义`confirmBtn` 和 `closeBtn`
> fix(Drawer): use `FooterButton` props define `confirmBtn` and `closeBtn` are invalid

- src/select/__tests__/select.test.tsx
- src/select/base/Select.tsx
https://github.com/Tencent/tdesign-react/issues/3212
1、处理onCheckAllChange方法中getSelectedOptions返回空的问题
2、将入参values从SelectOption[]修改为SeletValue[]
- fix(select): 多选下拉框全选功能失效
- [] 本条 PR 不需要纳入 Changelog
> fix(select): 多选下拉框全选功能失效

- src/color-picker/components/panel/header.tsx
- src/color-picker/const.ts
#3219 
添加 ColorPicker 组件中颜色模式文案的多语言适配
> fix(color-picker): add locale support for color mode switch

- src/select/__tests__/select.test.tsx
- src/select/base/Select.tsx
对于 https://github.com/Tencent/tdesign-react/pull/3185 pr 的修复
- fix(Select): 修复 `collapsedItems`  的参数  `collapsedSelectedItems`
> fix(Select): `collapsedItems`'s parameter `collapsedSelectedItems`

- src/form/FormItem.tsx
- src/form/__tests__/form.test.tsx
- fix(Form): 修复`setFieldsValue`和`setFields` 没有触发`onValuesChange`的问题
> fix(Form): setFieldsValue and setFields should trigger onValuesChange

- CHANGELOG.md
- package.json
> chore: release 1.10.1

- src/image-viewer/ImageViewer.tsx
- src/image-viewer/__tests__/image-viewer.test.tsx
- #3238 
when the fix is ​​uncontrolled, onClose is always triggered
- fix(ImageViewer): 修复不受控时，`visable`改变时都会触发`onClose`
> fix(ImageViewer): when the fix is ​​uncontrolled, onClose is always triggered

- src/checkbox/CheckboxGroup.tsx
fix intervalOptions not is Checkbox,Leading to extra undefined values
- fix(CheckboxGroup): 修复复选框组的子元素不是复选框导致的问题
> fix(CheckboxGroup): fix intervalOptions not is Checkbox

- src/config-provider/config-provider.en-US.md
- src/config-provider/config-provider.md
- src/config-provider/type.ts
- src/drawer/Drawer.tsx
- #3266
`ConfigProvider` 的 `attach` 支持 `Drawer`
- feat(ConfigProvider): attach suppport `drawer` api
> feat(ConfigProvider): attach suppport drawer

- src/form/__tests__/form.test.tsx
- src/form/hooks/useInstance.tsx
当 FormItem prop.name 是数组时，使用 setFieldsValue 赋值无效
如果 props.name 是数组，遍历 formMapRef.current.entries()，使用 lodash/isEqual 比较两个数组内容是否一致
- fix(Form): 修复`1.9.3`版本后多级表单字段使用 `setFieldValues` 功能异常的问题
> fix(Form): fixed setFieldsValue is invalid when prop.name type is array

- src/alert/Alert.tsx
- src/alert/__tests__/alert.test.tsx
When message's length is less than maxLine prop, it will not show the collapse button.
暂无
1. 当maxLine数量 >= 传入的message数量时，依然会展示【展开更多/收起】按钮，但点击无效果，如图，仅仅是按钮文字变化
优化：当maxLine数量 < 传入的message数量时，即具备折叠条件时，才显示折叠按钮“
（注：图中示例的 maxLine 改为了 5）
2. 代码中的 **collpased** 布尔值用反了，collpased应该是【已折叠】的状态，根据组件的行为，初始应该为true
3. 增加了代码中的 maxLine 变量的健壮性处理
4. 补充了对应的单元测试，修正了单元测试代码中 message 误写为 massage 的错误
- feat(Alert): 在 maxLine >= message 数组长度时，不再展示【展开更多/收起】按钮
> feat(alert): optimize collapse behavior

- src/alert/__tests__/alert.test.tsx
- test(Alert): 优化测试用例代码类型和添加对于 `className`、`style` 的测试
> test(Alert): add unit tests for className and style 

- src/form/__tests__/form.test.tsx
- src/form/formModel.ts
经过排查发现 当前，当规则验证的数字为 0 时，会跳过规则验证
`rulelkey]` 为 0 ，则 `(validateRule && rulelkey])` 为 `false` ，实际需求为 `true`
- fix(form):  修复当规则为 `value: [{ min: 0 }]` 时，验证不生效的问题 
> fix(form):  `value: [{ min: 0 }]` invalid rules and add test

- src/select/base/PopupContent.tsx
- src/select/base/Select.tsx
- src/select/util/helper.ts
- fix(Select): 修复 `valueType` 为 `object`选中全选的展示异常及回调参数缺少的问题
> fix(Select): fix object type select all and callback params

- src/tree/Tree.tsx
- src/tree/hooks/useTreeVirtualScroll.ts
- src/tree/type.ts
`Tree` support `onScroll` api
- feat(Tree):  support `onScroll` api
> feat(tree): add Tree onScroll api

- src/tooltip/TooltipLite.tsx
fix #3225
https://github.com/Tencent/tdesign-common/pull/1996
https://github.com/Tencent/tdesign-react/issues/3225
让 `tooltip-lite` 的内容跟随鼠标
feat(tooltip): tooltip-lite mouse 模式跟随鼠标位置
> feat(tooltip): tooltip-lite mouse 模式跟随鼠标位置

- CHANGELOG.md
- package.json
> chore: release 1.10.3

- CHANGELOG.md
- package.json
- src/select/util/helper.ts
> chore: release 1.10.4

- src/date-picker/DateRangePicker.tsx
from https://github.com/Tencent/tdesign-vue-next/issues/4867
- fix(DateRangePicker): 开始结束值同时存在的逻辑判断错误问题
> fix(date-range-picker): logical judgment error when start and end values exist at the same time

- site/src/App.jsx
依赖项缺失问题修复：React Hook useEffect has a missing dependency，eslint-disable-next-line react-hooks/exhaustive-deps
无相关issue,查看源码过程中发现依赖项确实，添加了禁止检测规则
> chore(site): fix effect deps lint

- src/statistic/Statistic.tsx
https://github.com/Tencent/tdesign-react/issues/3325
fix(statistic): decimalPlaces=0时数值动画期间精度错误
> fix(statistic): decimalPlaces=0时数值动画期间精度错误

- CHANGELOG.md
- package.json
> Release 1.10.5

- src/checkbox/CheckboxGroup.tsx
- src/checkbox/type.ts
checkbox.group的onChange的context参数缺少option
- fix(CheckboxGroup): 修复onChange的context参数缺少option
> fix(Checkbox): fix checkboxGroup onChange context option param

- src/cascader/Cascader.tsx
- src/cascader/_example/multiple.tsx
- feat(Cascader):  支持在打开菜单时滚动到首个已选项所在节点的能力
> feat(cascader): support auto scroll to first selected element

- src/textarea/Textarea.tsx
- src/textarea/__tests__/textarea.test.tsx
- #3355
fix `autofocus`,`value` cursor not at the end bug
修复`autofocus`，`value`有值时的光标不在内容后面的问题
- fix(Textarea): 修复`autofocus`，`value`有值时光标不在内容后面的问题
> fix(Textarea): fix autofocus cursor at the end

- src/radio/RadioGroup.tsx
- #3359
在`React19`下，`mutationObserver` 会监听到`input`的`attributes` 属性变化，导致死循环
- fix(Radio): 修复`RadioGroup` 在 React 19 版本下异常的问题
> fix(Radio): fix React19 radio-group stuck

- src/table/hooks/useFixed.ts
- src/table/utils.ts
-  #3365
* 这个问题已经定位到原因了，table在初始化后，会调用useEffect，动态计算表格滚动高度等变量，来动态设置isFixedHeader变量（暂且叫它悬浮变量），
* 如果悬浮变量为true的时候，会在表格页脚（footer）上增加fixed定位的样式，这样咱们就能看到底部的总数表页脚了。
* 现在的问题是，第二个TabPanel下的table在useEffect执行的时候，滚动高度为0（因为内容尚未初始化），导致悬浮变量是false，所以就看不到页脚。
* 此刻点击排序就能看到页脚汇总行，是因为排序会引起useEffect重新执行，此刻滚动高度是正常的数值（大于0），所以悬浮变量的值为true。
- fix(Table): 修复配合`Tabs`使用，切换tab时，Table的footer可能不显示的问题
> fix(table):  table footer may not be displayed when switching tabs

- CONTRIBUTING.md
- docs(CONTRIBUTING.md): CONTRIBUTING.md 文件更新
> docs: update submodule content of contributing.md

- CHANGELOG.md
- package.json
> chore: release 1.11.0

- src/_util/react-render.ts
- src/notification/NotificationList.tsx
- #3375 
- #3378
React18和19导出createRoot是在`react-dom/client`中的；
为了兼容React17的reactRender，导出createRoot是在`react-dom`中的；
是否还要兼容React17及以下的渲染？
现在这种写法是为了兼容的，不兼容的话就改成react-dom/client现代的写法来处理
- fix(reactRender): fix `React19` `reactRender` error
> fix(reactRender): fix React19 reactRender error

- packages/components/message/Message.tsx
Message组件,关闭消息实例时,从全局的消息列表中移除该实例
message组件，函数式调用， 每次自动close后，MessageList 中push进去的实例没有删除，引用还在，有内存泄漏的风险
- fix(Message): 关闭消息实例时，从全局的消息列表中移除该实例，避免潜在的内存泄漏
> fix(message): message组件,关闭消息实例时,从全局的消息列表中移除该实例

- packages/components/drawer/hooks/useDrag.ts
解决Drawer抽屉在拖拽改变大小的时候获取宽度可能不正确的问题
在 `useDrag.ts` 文件中， handleMouseup 函数中的 dragSizeValue 每次取值不正确的问题，是由于 dragSizeValue 的状态更新不及时导致的。 useState 的更新是异步的，因此在 handleMouseup 中直接使用 dragSizeValue 会导致获取到的值不是最新的。
解决方案是使用 useRef 来存储最新的 dragSizeValue ，这样可以确保在 handleMouseup 中获取到的值是最新的。
- fix(Drawer): 解决Drawer抽屉在拖拽改变大小的时候获取宽度可能不正确的问题
> fix(drawer): fix drawer width value when dragging 

- package.json
- script/pnpm-dev-preinstall.js
https://github.com/Tencent/tdesign-common/actions/runs/14008551849/job/39225878584
common 仓库 集成 ui 仓库测试流程
1. 检出 UI 仓库代码，不初始化 common 子模块
2. 检出 common 仓库 PR 代码到 UI 仓库的 common 子模块代码位置
3. 进行 lint 、test、build 进行测试
UI 仓库加了 pnpm:devPreinstall，在运行 pnpm install 会初始化一次 common 子模块，破坏 common 仓库集成测试的第二步流程，把 common 子模块代码重置还原为 UI 仓库记录的 commit id
解决方式 :
判断是否为 CI 环境，如果是 pnpm:devPreinstall 运行不初始化 common 子模块
> chore: add preinstall script to skip init submodule in common repo

- packages/components/guide/__tests__/__snapshots__/vitest-guide.test.jsx.snap
- packages/components/popup/Popup.tsx
- packages/components/popup/PopupPlugin.tsx
解决popup组件修饰符arrow属性设置不生效的问题
fix #3340
https://github.com/Tencent/tdesign-react/issues/3340
对于arrow修饰符，options中需要显式指定element属性，如果没有指定这个属性，Popper会自动寻找“data-popper-arrow”的元素作为element，如果最终没找到element，则其它设置无法生效，例如padding。解决方案：给arrow页面元素增加data-popper-arrow属性，以便用户不需要额外编码即可支持arrow修饰符
- fix(Popup): 解决popup组件修饰符arrow属性设置不生效的问题
> fix(popup): 解决popup组件修饰符arrow属性设置不生效的问题

- packages/components/tooltip/TooltipLite.tsx
背景：
在 react 16 中，事件池机制会导致拿不到 `e.clientX` 和 `e.clientY`，导致 tooltip-lite 的位置计算不正确，导致位置闪动。
解决方案：在异步操作前，将需要的属性保存到变量中。
- fix(tooltip): 修复 react 16 下，tooltip-lite mouse 计算位置
> fix(tooltip): 修复 react 16 下，tooltip-lite mouse 计算位置

- packages/components/tree/hooks/useStore.ts
✅ Closes: 3461
https://github.com/Tencent/tdesign-react/issues/3461
前提：
1、tree的某些节点可能会被移除，比如远端拉取数据后某些节点被删掉了
2、设置了expandParent属性
3、expanded属性中包含了被移除的节点value，且在数据更新后没有被手动移除
点击移除按钮即可，即可复现白屏
组件内部冗余这种错误，在查找父节点不存在时中断后续处理逻辑。
在使用时处理这种逻辑相对较复杂,需要遍历整棵树
> fix(Tree):  getParents error when tree data update

- packages/components/table/hooks/usePagination.tsx
受控用法下，pagination修改后innerPagination数据未同步，导致序号列计算错误
- fix(Table): 修复受控方法下`pagination`状态计算错误的问题
> fix(table): 'serial-number' column calculate error

- packages/components/select/base/PopupContent.tsx
无
在初始化select组件时，options可能值为空（非预期内的空数组），会导致报错，引发白屏，
主要三种情况：
1、初始为空（非空数据），异步后才赋值
2、使用自定义渲染options，可能不会传options
兜底处理：
- fix(Select): 修复 `options`为空时会导致报错引发白屏的问题
> fix(Select): init options props error when options no data

- packages/components/radio/RadioGroup.tsx
**场景：** `ColorPickerPanel`「单色 / 渐变」的 `Ratio` 高亮异常。
**原因：** 初始化时父容器被 `hidden`，但 `Ratio` 的元素已经渲染在页面上，只是不在可视区域，所以 `calcBarStyle()` 首次获取到的 `offsetXxxx` 相关数值为 0 。后面切换显示该组件时，`calcBarStyle()` 没能触发重新计算，而是一直保留之前得到的 0。
```tsx
{navList.map((nav) => (
<div
key={nav.id}
id={nav.id}
hidden={nav.id !== activeNav}
>
{nav.component}
</div>
))}
```
（`ColorPickerPanel` 作为 `navList` 的子组件，且不在第一个）
- fix(RadioGroup): recalculate bar style on visibility change
> fix(RadioGroup): recalculate bar style on visibility change

- packages/components/color-picker/__tests__/color-picker.test.tsx
- packages/components/color-picker/components/panel/index.tsx
https://github.com/user-attachments/assets/f62162d8-5446-456f-be30-5cda6d794663
颜色模式切换的时候，必须再手动点击下面的色板，input 框才会更新色值。
- `handleModeChange` 中没有调用 `emitColorChange` 方法
- `handleModeChange` -> `setMode` -> `emitColorChange` -> `formatValue` 获取的 `mode` 是异步更新前的旧值
（Test 中的验证 ColorMode 缓存不太合理，这个场景下，切换后再切回来，颜色必然变化）
- fix(color-picker): ensure color change is emitted with updated mode
> fix(color-picker): ensure color change is emitted with updated mode

- packages/components/table/hooks/useColumnResize.tsx
- 当前拖拽单元格右侧时，计算逻辑存在错误，导致表格宽度不断变宽，实际应该在此场景下优先计算影响上一列的宽度，同时调整当前列和上一列的宽度，更符合使用习惯
- fix(Table): 修复可调整列宽表格右侧拖拽调整的异常问题
> fix(Table): fix table col resize header bug

- packages/components/date-picker/DatePicker.tsx
- packages/components/date-picker/DateRangePicker.tsx
- packages/components/date-picker/hooks/useRange.tsx
- packages/components/date-picker/hooks/useSingle.tsx
- fix(DatePicker): 确保外部组件主动关闭 Popup 的时候，能有对应的 onVisibleChange 回调
> fix(DatePicker): trigger `onVisibleChange` when manually closing Popup

- packages/components/select/base/Select.tsx
在react16版本中，editcell中使用Select多选模式，tag的onClose事件会触发单元格编辑失焦
解决方案参考：https://github.com/Tencent/tdesign-react/pull/1988/commits/dc91b33b0e9cd4988bf62211b0ef7f0fce7dcacb
> fix(select): editable cell keep edit state

- packages/components/card/Card.tsx
API 文档中标明了 `content` 和 `childen` 等同，但实际上 `Card` 内部没有调用过 `content` 这个参数。
理论上以下两种写法都可以生效（但 `childen` 优先级更高）：
```tsx
<Card>卡片内容</Card>
<Card content={<>卡片内容</>} />
```
- fix(card): `content` prop 不生效
> fix(card): `content` prop not working

- packages/components/popconfirm/Popconfirm.tsx
- packages/components/popconfirm/Popcontent.tsx
1、confirmBtn和cancelBtn的children属性不生效，只能用content代替
2、onVisibleChange事件有时候没有第二个参数
- fix(Popconfirm): 修复 confirmBtn 属性的 children 不生效的问题
> fix(Popconfirm):  attribute children of props confirmBtn&cancelBtn is not effective

- packages/components/form/Form.tsx
- packages/components/form/FormItem.tsx
- packages/components/form/__tests__/form-list.test.tsx
- packages/components/form/__tests__/form.test.tsx
- packages/components/form/hooks/interface.ts
- packages/components/form/hooks/useForm.ts
- packages/components/list/List.tsx
> [!CAUTION]
> 需要严格测试这样修改是否不会影响其他的设置值的问题
- fix(Form): 修复`Form setFields`导致的`Rerender`
> fix(form): fix form setFields rerender

- packages/components/drawer/Drawer.tsx
- packages/components/textarea/Textarea.tsx
#3542
- fix(Textarea): 修复输入中文被中断的问题
- fix(Drawer): `TNode` 重新渲染导致输入光标错误
> fix(textarea): handle composing input value correctly

- README-zh_CN.md
- README.md
Hi Tencent/tdesign Community
tdesign-react is a vibrant open-source community where its products and frameworks are loved by lots of users and developers. As people use it, they contribute by raising issues, engaging in discussions, or directly contributing code, all of which help in continuously improving tdesign-react.
However, GitHub's default contributor list simply enumerates users who have committed code, failing to proportionately reflect the broader range of community contributors.
Therefore, we have designed a new chart that showcases active contributors from three perspectives: issues, PRs, and discussions. This is similar to embedding star-history within the README:
By clicking on the link, you can view the specific contributions made by each individual: …
> docs: A new contributor graph that evaluates community activities from all dimensions

- packages/components/drawer/drawer.en-US.md
- packages/components/drawer/drawer.md
- packages/components/drawer/type.ts
Sync https://github.com/Tencent/tdesign-vue-next/pull/5555
- fix(drawer):  修复 `cancel-btn` 和 `confirm-btn` 的类型缺失`null` 声明的问题
> fix(drawer): `cancel-btn` and `confirm-btn` type supports `null`

- packages/components/menu/SubMenu.tsx
- packages/components/menu/_example/multiple.tsx
- 内部 visible 是受控的，结合了 mouse 事件，强行把它 open了，导致 `delay` 失效
- 顺便修复了一些英语语法，`childrens` -> `children` 已经是复数；索尼的名字不太对
- fix(Menu): `popupProps` 的 `delay` 属性在 `SubMenu` 中无法生效
> fix(Menu): `popupProps.delay` in `SubMenu` not working

- packages/components/image-viewer/ImageViewerMini.tsx
- packages/components/image-viewer/ImageViewerModal.tsx
- packages/components/image-viewer/_example/album.tsx
- packages/components/image-viewer/_example/albumIcons.tsx
- packages/components/image-viewer/_example/base.tsx
- packages/components/image-viewer/_example/block.tsx
- packages/components/image-viewer/_example/button.tsx
- packages/components/image-viewer/_example/error.tsx
- packages/components/image-viewer/_example/multiple.tsx
- packages/components/image-viewer/_example/svg.tsx
- packages/components/image-viewer/hooks/useScale.ts
- packages/components/tooltip/TooltipLite.tsx
- ***`Fix 1`***：工具栏的 `onMirror`、`onRotate` 等方法是直接绑定在 `Icon` 上面，导致点击 `Icon` 边缘的时候无法触发操作，因此改为绑定在 `Icon` 外层的 `div`。
- ***`Fix 2`***：主题生成器的 `zIndex` 过高了，于是调整了 `ImageViewer` Demo 的 `zIndex`，却又发现了 `TooltipLite` 层级过低。因此给 `TooltipLite` 新增一个 `zIndex` Prop，将当前 ImageViewer 的 `zIndex + 1` 传给 `TooltipLite`。
- 还有一条相关的修复，可以等 https://github.com/Tencent/tdesign-common/pull/2179 合并后，顺便在这条 PR 下 `/update-common`
- fix(ImageViewer): 修复点击工具栏的图标边缘时无法触发对应的操作
- fix(ImageViewer): 修复由于 `TooltipLite` 引起的 `z-index` 层级关系异常
- feat(ImageViewer): 移动端支持通过双指进行缩放图片
> fix(ImageViewer): ensure toolbar icons reliably trigger actions

- packages/components/color-picker/components/panel/index.tsx
https://github.com/Tencent/tdesign-react/issues/3622
**点击上面的渐变点时，下面的色板没有同步颜色**（Ref 无法触发 UI 刷新）
上次重构 https://github.com/Tencent/tdesign-react/pull/3503 的时候被我改坏了 🤧
- fix(ColorPicker): 确保点击渐变点时，色版能同步更新
> fix(ColorPicker): update `SaturationPanel` on gradient point click

- packages/components/guide/__tests__/__snapshots__/vitest-guide.test.jsx.snap
- packages/components/popup/Popup.tsx
- packages/components/popup/PopupPlugin.tsx
https://github.com/Tencent/tdesign-react/pull/3437
箭头位置在左右两侧时，无法居中（[官网 Plugin](http://localhost:15000/react/components/popup?tab=demo#%E9%80%9A%E8%BF%87%E6%8F%92%E4%BB%B6%E6%96%B9%E5%BC%8F%E8%B0%83%E7%94%A8popup) 可复现）：
- 当用户启用 `popperOptions.modifiers`，且 `name = "arrow"`  时，再给 div 赋予 `data-popper-arrow` 属性，否则会和 styles 冲突（根据 [popper.js 文档](https://popper.js.org/docs/v2/modifiers/)，modifiers 有多种，但实际上只有当启用 `arrow` 时，需要额外设置这种[特殊属性](https://popper.js.org/docs/v2/modifiers/arrow/#element)）
```tsx
import React from 'react';
import { Button, Popup } from 'tdesign-react';
export default function BasicUsage() {
return (
<Popup
showArrow
trigger="hover"
content="这是一个弹出框"
placement="right"
popperOptions={{
modifiers: [
{
name: 'arrow',
options: {
// padding: 5, // 箭头偏上
// padding: 15, // 差不多居中 …
```
> fix(Popup): enhance arrow modifier support for popper.js

- packages/components/statistic/Statistic.tsx
- packages/components/statistic/__tests__/statistic.test.tsx
- packages/components/statistic/statistic.en-US.md
- packages/components/statistic/statistic.md
- packages/components/statistic/type.ts
https://github.com/TDesignOteam/tdesign-api/pull/688
- refactor(Statistic): 修改 color 属性类型为字符串，以支持任何 [CSS color](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) 支持的颜色值
> refactor(Statistic): change color attribute type to string and update  docs description

- packages/components/tree/_example/draggable.tsx
- packages/components/tree/hooks/TreeDraggableContext.tsx
- packages/components/tree/hooks/useDraggable.tsx
- packages/components/tree/tree.en-US.md
- packages/components/tree/tree.md
- packages/components/tree/type.ts
- Tree 组件拖拽过程中，需要展开 dropPosition 为0的树，不中断用户操作，再往拖拽下层移动。该场景下使用 onDragOver 属性无法获取 dragNode、dropPosition 等信息，外层无法实现此交互
- 直接读取 `node.model` 会遇见 `null` 的情况...改用 `node.getModel()` 比较稳定，详见 https://github.com/Tencent/tdesign-common/blob/develop/js/tree-v1/tree-node.ts#L1393 逻辑
- feat(Tree): `onDragLeave` 与 `onDragOver` 增加 `dragNode`、`dropPosition` 参数
- fix(Tree): 修复 Drag 相关事件的回调中 `node` 为 null 的异常
> feat(Tree): add dragNode and dropPosition params for onDragOver API

- packages/components/card/Card.tsx
- packages/components/card/__tests__/card.test.tsx
- packages/components/card/card.en-US.md
- packages/components/card/card.md
- packages/components/card/type.ts
- packages/components/tooltip/_example/lite.tsx
- feat(Card): 新增 `headerClassName`、`headerStyle`、`bodyClassName`、`bodyStyle`、`footerClassName`、`footerStyle`，方便用于定制卡片组件的各部分样式
> feat: add style and class for internal dom

- packages/components/select/base/Select.tsx
- packages/components/tag-input/TagInput.tsx
<details>
<summary><strong><em>复现代码</strong></em></summary>
```tsx
import React, { useCallback, useState } from 'react';
import { Select, SelectOption, Space, Tag } from 'tdesign-react';
const options = [
{ label: '选项一', value: '1' },
{ label: '选项二', value: '2' },
{ label: '选项三', value: '3' },
{ label: '选项四', value: '4' },
{ label: '选项五', value: '5' },
{ label: '选项六', value: '6' },
{ label: '选项七', value: '7' },
{ label: '选项八', value: '8' },
{ label: '选项九', value: '9' },
];
const CustomSelected = () => {
const [value, setValue] = useState(['1', '2', '3']);
const onChange = (value: string[]) => {
setValue(value);
};
const singleSelect = ({ value }) => {
console.log('singleSelect');
return value ? `${value} 👼 ` : null;
};
const multipleSelect = useCallback(({ value, onClose }) => { …
```
> fix(TagInput): optimize value display rendering with useMemo

- packages/components/dialog/Dialog.tsx
- packages/components/drawer/Drawer.tsx
- packages/components/hooks/useDeepEffect.ts
https://github.com/Tencent/tdesign-react/issues/3796
React 19 中，`ref` 被改为一个普通的 `props`：https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop
- fix(Dialog): 修复在 React 19 环境下，由于使用 `ref` 引发的死循环问题
- fix(Drawer): 修复在 React 19 环境下，由于使用 `ref` 引发的死循环问题
> fix(Dialog/Drawer): add useDeepEffect hook

- packages/components/cascader/core/className.ts
同步 Vue Next 的解决方案 https://github.com/Tencent/tdesign-vue-next/pull/4951
- fix(Cascader): 修复 `single` 模式下，选中唯一的子节点时，父节点意外被高亮的问题
> fix(Cascader): refine selection logic for leaf node in single mode

- packages/components/tag-input/TagInput.tsx
- packages/components/tag-input/__tests__/vitest-tag-input.test.jsx
https://github.com/Tencent/tdesign-react/issues/3324
虽然 blur 的一瞬间，输入被清空，但依旧应该提供给用户之前的输入（对齐以下交互）
- Vue Next 的 `TagInput` 目前是保留输入
- React 的 `Cascader` 等组件的 blur 也是保留输入
- fix(TagInput): 修复 `onBlur` 中的 `inputValue` 始终为空的问题
> fix(TagInput): pass `inputValue` to `onBlur` callback

- packages/components/watermark/Watermark.tsx
- packages/components/watermark/__tests__/watermark.test.tsx
- packages/components/watermark/_example/layout.tsx
- packages/components/watermark/_usage/index.jsx
- packages/components/watermark/_usage/props.json
- packages/components/watermark/defaultProps.ts
- packages/components/watermark/type.ts
- packages/components/watermark/watermark.en-US.md
- packages/components/watermark/watermark.md
- script/generate-usage/config.js
- feat(Watermark): 新增 `layout` API，支持生成不同布局的水印，`watermarkText` 支持配置字体
- fix(Watermark): 修复多行图文水印图片配置了灰度时，整个画布内容也会灰度的问题
- docs(Watermark): 新增 live demo 展示
> feat(Watermark): support layout API

- packages/components/cascader/Cascader.tsx
- packages/components/select-input/SelectInput.tsx
- packages/components/select-input/useMultiple.tsx
- packages/components/select-input/useOverlayInnerStyle.ts
- packages/components/select-input/useSingle.tsx
https://github.com/Tencent/tdesign-react/issues/3837
涉及 `Select`、`TreeSelect` 、`Cascader` 等基于 `SelectInput` 二次封装的组件
- fix(SelectInput): 修复自定义 `popupVisible={false}` 时，`onBlur` 不生效的问题
- fix(SelectInput): 修复开启 `multiple` 时， `onBlur` 缺少 `tagInputValue` 参数的问题
> fix(SelectInput): ensure `onBlur` can trigger when set `popupVisible`

- packages/components/image-viewer/ImageViewer.tsx
- packages/components/image-viewer/ImageViewerModal.tsx
- packages/components/image-viewer/__tests__/image-viewer.test.tsx
- packages/components/image-viewer/_example/album.tsx
- packages/components/image-viewer/_example/albumIcons.tsx
- packages/components/image-viewer/_example/base.tsx
- packages/components/image-viewer/_example/block.tsx
- packages/components/image-viewer/_example/button.tsx
- packages/components/image-viewer/_example/error.tsx
- packages/components/image-viewer/_example/modeless.tsx
- packages/components/image-viewer/_example/multiple.tsx
- packages/components/image-viewer/_example/svg.tsx
- packages/components/image-viewer/image-viewer.en-US.md
- packages/components/image-viewer/image-viewer.md
- packages/components/image-viewer/type.ts
- packages/components/upload/themes/DraggerFile.tsx
from https://github.com/TDesignOteam/tdesign-api/pull/686
- feat(ImageViewer): 支持 `trigger` 传入图片 `index` 参数，trigger  的 `open` 方法参数可能与绑定的元素触发事件存在类型差异情况，若遇到此问题请改成 `()=> open()` 类似匿名函数使用
> fix(image-viewer): update trigger prop to accept index parameter
