- .husky/commit-msg
- .husky/pre-commit
- package.json
- site/docs/getting-started.md
- src/cascader/Cascader.tsx
- src/cascader/__tests__/__snapshots__/cascader.test.tsx.snap
- src/cascader/_example/base.jsx
- src/cascader/_example/collapsed.jsx
- src/cascader/_example/disabled.jsx
- src/cascader/_example/ellipsis.jsx
- src/cascader/_example/filterable.jsx
- src/cascader/_example/keys.jsx
- src/cascader/_example/load.jsx
- src/cascader/_example/max.jsx
- src/cascader/_example/multiple.jsx
- src/cascader/_example/show-all-levels.jsx
- src/cascader/_example/size.jsx
- src/cascader/_example/trigger.jsx
- src/cascader/_example/value-mode.jsx
- src/cascader/components/InputContent.tsx
- src/cascader/components/Item.tsx
- src/cascader/components/Panel.tsx
- src/cascader/interface.ts
- src/cascader/utils/inputContent.ts
- src/cascader/utils/panel.ts
- add getting-starter alert
- cascader feature update
common: https://github.com/Tencent/tdesign-common/pull/7
> feat: cascader sync

- src/time-picker/consts.ts
- src/time-picker/panel/SinglePanel.tsx
step more than 1 should begin from 0
> fix(timepicker): change step render logic

- .husky/prepare-commit-msg
> feat(husky): add prepare commit msg

- src/calendar/__tests__/__snapshots__/calendar.test.tsx.snap
- src/pagination/__tests__/__snapshots__/pagination.test.tsx.snap
- src/select/__tests__/__snapshots__/select.test.tsx.snap
- src/select/base/OptionGroup.tsx
- src/select/base/PopupContent.tsx
- src/select/base/Select.tsx
- src/steps/StepItem.tsx
- src/steps/__tests__/__snapshots__/steps.test.tsx.snap
- src/table/__tests__/__snapshots__/table.test.tsx.snap
- src/transfer/Transfer.tsx
- src/transfer/TransferList.tsx
- src/transfer/__tests__/__snapshots__/transfer.test.tsx.snap
- src/transfer/_example/empty.jsx
1. replace select css name
2. replace transfer css name
3. replace steps css name 
4. update snapshots
> refactor: replace select/transfer/steps css name

- globals.d.ts
- package.json
> fix: 修复avatar组件编译失败问题

- src/select/base/Select.tsx
> fix(Select): fixup  dropdown bug

- src/slider/Slider.tsx
修复`slider`组件在`vertical`模式下不对齐的样式问题。
> fix(slider): fix slider style with vertical mode

- src/select/base/Select.tsx
> fix(Select): select disabled attribute is invalid

- src/date-picker/_example/date-presets-alt.jsx
'Recent three days' should includes the day before yesterday, yesterday and today.
> DatePicker Demo fix

- src/breadcrumb/Breadcrumb.tsx
- src/breadcrumb/BreadcrumbContext.tsx
- src/breadcrumb/BreadcrumbItem.tsx
- src/breadcrumb/__tests__/__snapshots__/breadcrumb.test.tsx.snap
- src/breadcrumb/_example/base.jsx
- src/breadcrumb/_example/width.jsx
- src/breadcrumb/breadcrumb.md
> fix(Breadcrumb): breadcrumb example improvement

- src/pagination/Pagination.tsx
onMouseOver => onMouseEnter
onMouseOut => onMouseLeave
> fix: pagination more button flashing bug

- .github/workflows/preview-publish.yml
- .github/workflows/pull-request.yml
- action pr add types
- action action/comment update version
> ci: add pr type and update comment version

- src/cascader/Cascader.tsx
- src/date-picker/DatePicker.tsx
- src/dropdown/Dropdown.tsx
- src/popup/Popup.tsx
- src/popup/hooks/usePopupCssTransition.ts
- src/select/base/Select.tsx
- src/tree-select/TreeSelect.tsx
to resolve https://github.com/Tencent/tdesign-react/issues/87
> fix: popup scroll height

- src/date-picker/DatePicker.tsx
修复date-picker给defaultValue或者value传无效的时间|日期值的时候组件卡死
> fix(date-picker): trigger initialization when the value is a legal time|date type

- src/tree/Tree.tsx
- src/tree/TreeItem.tsx
- src/tree/interface.ts
> fix(tree): 修复tree 组件  disableCheck 未实现

- src/style/index.js
just like tdesign-vue fix pr: https://github.com/Tencent/tdesign-vue/pull/141
> feat: move css vars into index style

- src/config-provider/ConfigContext.tsx
- About typescript.
- File path: src/config-provider/ConfigContext.tsx
When used in multiple places, you can know which Key can
---
_Supplements: _
EG:
> fix(type): improve the locale type to get better tips

- src/time-picker/_example/show-steps.jsx
> fix(TimePicker): change example attribute

- src/progress/Progress.tsx
> fix: calculation in circle progress component

- src/comment/_example/reply-form.jsx
> fix(Comment): example notification not working

- src/dropdown/Dropdown.tsx
- src/popup/Popup.tsx
- src/select/base/Select.tsx
去掉popup中此前为了setVisible使用了useImperative暴露方法的问题。
PS: 这对某些用户是个breaking change
> refactor(popup): remove useImperative

- .vscode/extensions.json
> feat(VSCODE): add code spell checker to recommended extensions

- src/menu/HeadMenu.tsx
- src/tabs/TabNav.tsx
- src/tabs/TabNavItem.tsx
- src/tabs/Tabs.tsx
fix #161
1、menu 给 Tab 传 value 时不能把父菜单的 value 也传进来
2、Tab 支持 value 属性
> fix(component): 修复多层 menu 父菜单切换后子菜单定位失败的问题

- README.md
- site/docs/getting-started.md
> docs: 加 umd 直接引入方式安装

- src/locale/LocalReceiver.ts
https://github.com/Tencent/tdesign-react/pull/138
https://user-images.githubusercontent.com/33739877/147817034-d7b78410-28c2-42e6-8283-c93fc7a29953.mov
1. `transformLocale` 函数的入参类型的严格校验
2. 待此PR商讨后的需求
Happy New Year~ ✌️
> 【WIP】fix(type): improve the type of input and output of the useLocaleReceiver function

- src/table/_example/base.jsx
> fix(Table): base example pagination not working

- package.json
> chore: upgrade icon package version

- src/table/base/Table.tsx
关联issue: https://github.com/Tencent/tdesign-react/issues/152
> table支持传入className,style

- src/loading/gradient.tsx
- src/loading/loading.tsx
1. 复用loading公共逻辑
2. 修复此前style没有透传的问题
> refactor(loading): extract adapt logic

- src/time-picker/InputItems.tsx
- 限制timepicker键盘输入只允许数字；
- 修复连续输入计算错误问题
> fix(timepicker): only allow number input

- src/popup/Popup.tsx
> fix(popup): fix issue #231

- src/dialog/RenderDialog.tsx
> fix(dialog): mask 动画缺失问题

- src/affix/Affix.tsx
- src/affix/affix.md
- src/affix/index.ts
TDesign Affix 组件用起来有几个问题：
- `zIndex` 参数没实现
- 另外 `offsetTop` 为 0，`container` 恰好是 `window`，导致 `!!fixedTop` 零值判断错误，触发回调给值给错，本来应该 `affixed` 是 `true`，但是回调 `!!0` 依然是 `false`
- 文档里 offsetTop 对应的是“顶部”，offsetBottom 对应的是”底部“，写反了
- 导出 AffixRef 供外部使用
> fix: 修复 Affix 组件 zIndex 参数无效和 offsetTop 为 0 无法固定的问题

- src/popup/Popup.tsx
- src/popup/popup.md
- src/popup/type.ts
`popup`增加`onScroll` API，用于用户在`Select`等组件中，增加滚动底部加载数据等场景使用。
> feat(popup): support onScroll API

- package.json
- site/src/main.jsx
- src/select/base/OptionGroup.tsx
- src/select/base/PopupContent.tsx
> fix: 修复官网样式问题

- .github/workflows/workflows/issue-help-wanted.temp.yml
- .github/workflows/workflows/issue-mark-duplicate.temp.yml
- .github/workflows/workflows/issue-reply.temp.yml
- .github/workflows/workflows/issue-stale-close.temp.yml
从主仓同步Actions到仓库
- ci: 从主仓同步Actions到仓库
> ci: update files "/.github/workflows" from "Tencent/tdesign"

- src/select/base/PopupContent.tsx
相关issue https://github.com/Tencent/tdesign-common/pull/170
> feat: 优化 select 样式

- site/site.config.js
- site/src/components/codesandbox/main.js
> feat: 优化 loading展示

- src/select/util/helper.ts
- 修复由于component.type.name在正式环境中丢失引发的错误
- 同步部分common中对组件样式的修复
> fix(select): item type name missing

- src/table/base/TableCell.tsx
> fix(table): 固定列不指定colKey header错位

- package.json
- site/src/App.jsx
- src/popup/Popup.tsx
> fix: popup zIndex 设置错误

- src/table/enhanced/style/css.js
- src/table/enhanced/style/index.js
> fix(table): enchanced新目录下增加style文件

- src/table/_example/tree-select.jsx
- src/table/_example/tree.jsx
- src/table/base/Table.tsx
- src/table/base/TableCell.tsx
- src/table/enhanced/useTree.tsx
> feat(table): 补充单元格省略时tooltip提示;修复分页器非受控切换pageSzie时消失

- README.md
文档改进
[issue 338](https://github.com/Tencent/tdesign-react/issues/338)
完善了README文档的改进，让一个小白充满着激情clone代码时，能够看完文档一次性启动成功。
- fix-update-README: 完善README文档指引
> docs: 完善README文档参与贡献指引

- src/input/Input.tsx
- src/input/__tests__/input.test.tsx
- src/input/input.md
- src/input/type.ts
> feat: input 支持 onWheel、onCompositionstart、onCompositionend 事件

- src/table/base/TableRow.tsx
> fix: 兼容colkey 未指定导致 undefined key 重复问题

- src/skeleton/Skeleton.tsx
日常 bug 修复
- fix(skeleton): row col not working
> fix(skeleton): row col not working

- src/progress/Progress.tsx
- src/progress/_example/circle.jsx
- src/progress/_example/line.jsx
- src/progress/_example/plump.jsx
- https://github.com/Tencent/tdesign-vue/issues/412
- 修复前
- 修复后
- fix(progress): 修复percentage为0时仍然渲染的问题
> fix(progress): render dot when percentage is 0

- src/time-picker/panel/SinglePanel.tsx
- 日常 bug 修复
- https://github.com/Tencent/tdesign-vue/issues/107
- 改onmousewheel事件为scroll事件
- fix(time-picker): 修复部分鼠标滚动选择出现偏差的问题
> fix(timepicker): panel scroll when use mouse

- src/table/base/TableCell.tsx
日常 bug 修复 
table固定列滚动时，定位错误问题修复
#334 
- fix(table): 固定列横向滚动时，定位错误
> fix(table): #334 固定列定位计算问题

- src/layout/Layout.tsx
bug 修复
无 issue，Layout 的 children 存在 null 或者 undefined 时，child.type 容错不够
> fix(component): layout dynamic children

- src/common.ts
- src/tag-input/tag-input.md
- src/tag-input/type.ts
日常 bug 修复，文档改进
taginput
- fix(taginput): ondragsort参数类型完善，文档完善
> taginput类型问题修复

- site/src/App.jsx
- src/_util/useAnimation.ts
- src/_util/useRipple.ts
- src/config-provider/ConfigContext.tsx
- src/config-provider/ConfigProvider.tsx
- src/config-provider/config-provider.md
- src/config-provider/type.ts
- src/popup/Popup.tsx
- src/popup/utils/getTransitionParams.ts
- https://github.com/Tencent/tdesign-react/issues/287
- feat(全局配置): 支持配置animation关闭指定动画
> feat(animation): 新增animation全局配置，支持关闭指定动画

- src/select-input/SelectInput.tsx
- src/select-input/select-input.md
- src/select-input/type.ts
- src/select-input/useMultiple.tsx
- src/select-input/useSingle.tsx
日常 bug 修复
- fix(select-input): 支持loading&修复点击弹框输入框不高亮
> fix(select-input): 支持loading&修复点击弹框输入框不高亮

- src/input-number/InputNumber.tsx
- 日常 bug 修复
- 修复当存在最小值且空值时 直接加step的时候会出现小于最小值的情况，依赖于onBlur之后的矫正，
- 修复空值时减少按钮为禁用的问题
- 复现 https://stackblitz.com/edit/angular-utzmpd?file=src%2Fdemo.jsx
- 如`<InputNumber max={15} min={5} />`
- fix(input-number): 修复无初始值情况下点击增加存在小于min值的问题
> fix(input-number): 修复无初始值情况下点击增加存在小于min值的问题

- src/alert/Alert.tsx
日常 bug 修复
#424
- fix(alert): classname自定义被覆盖问题
> fix(alert): classname自定义被覆盖问题

- src/loading/loading.tsx
- 日常 bug 修复
- fix(loading): 修复全屏下loading加载后的问题
> fix(loading): 修复全屏下loading加载后的问题

- src/table/_example/base.jsx
- src/table/base/TableBody.tsx
- fix(table): 鼠标事件参数未按RowEventContext定义输出
> fix(table): 鼠标事件参数未按RowEventContext定义输出

- src/table/base/TableBody.tsx
- src/table/base/TableRow.tsx
- chore(table): 还原TableBody中的rowEvents
> chore(table): 还原TableBody中的rowEvents

- src/_util/useDragSorter.tsx
> fix: useDragSorter 中补充 onDragOverCheck 容错

- src/select/base/Select.tsx
日常 bug 修复
value 非受控时再次选中不高亮
- fix(组件名称): Select
- [ ☑️] 文档已补充或无须补充
- [ ☑️] 代码演示已提供或无须提供
- [ ☑️] TypeScript 定义已补充或无须补充
- [ ☑️] Changelog 已提供或无须提供
> Select 组件 value 非受控时再次选中不高亮

- src/message/MessageClose.tsx
https://github.com/Tencent/tdesign-react/issues/474
> fix: Message 组件，onCloseBtnClose 函数逻辑支持

- src/form/FormItem.tsx
https://github.com/Tencent/tdesign-react/issues/482
- fix( FormItem):  补充 FormItemProps children 属性
> fix: 修复 FormItemProps 缺少 children 属性 (#482)

- src/dialog/RenderDialog.tsx
修复DialogPlugin关闭后滚动问题
fix #484
- fix(dialog): 修复DialogPlugin关闭后滚动问题
> fix(dialog): 修复DialogPlugin关闭后滚动问题

- src/date-picker/DatePicker.tsx
> fix: 修复 datepicker placeholder 失效问题

- src/slider/Slider.tsx
- src/slider/SliderHandleButton.tsx
- src/slider/_example/base.jsx
- src/slider/slider.md
- src/slider/type.ts
feat: slider label suppor ReactNode function
> feat: slider label support function

- src/form/FormItem.tsx
- fix(form): reset失败如果initialdata是undefined
> fix(form): reset失败如果initialdata是undefined

- .gitmodules
> feat: 调整submodule clone 方式为 https

- src/select/base/PopupContent.tsx
> style(component): select style

- src/select/base/Select.tsx
> fix(select): 修复 select overlayClassName 丢失的问题

- src/loading/__tests__/Loading.test.tsx
- src/loading/_example/delay.jsx
- src/loading/loading.tsx
- src/table/style/index.js
- 日常 bug 修复 Loading部分场景下设置loading=false无效的问题
- 日常 bug 修复 Loading单独引用丢失旋转样式的问题
- fix(Loading): 修复 Loading部分场景下设置loading=false无效的问题
- fix(Loading): 修复 Loading单独引用丢失旋转样式的问题
> fix(loading): loading props false not working is normal status

- src/dropdown/dropdown.md
> chore: modify dropdown minColumnWidth description

- src/upload/themes/image-card.tsx
fix #584
#584 
-fix image-card . progrees value display error 
> fix: (upload) image-card progress value display error

- src/progress/__tests__/__snapshots__/progress.test.tsx.snap
- src/progress/__tests__/progress.test.tsx
- src/tabs/__tests__/tabs.test.tsx
- src/tag/__tests__/tag.test.tsx
无
无
补充如下组件的单测：
Tabs: 补充 TabNav events 测试，Tab placement 测试
Tag: 修复 content 测试不传 maxWidth 有个 Branches 条件没有覆盖到
Progress: 增加 snapshots，补充 theme 和 size 测试
> test: 补充 Tabs，Tag，Progress 组件的单测

- src/slider/Slider.tsx
fix:  slider add default value
> fix: slider default value

- src/menu/_example/group-side.jsx
fix: change menu demo image when collapsed
> fix: menu demo bug

- site/vite.config.js
n
- test(): 暂时屏蔽vite istanbul测试覆盖率统计插件
> test(e2e): 暂时屏蔽vite istanbul测试覆盖率统计插件

- src/_util/number.ts
> fix: 修复 slider max 数值过大性能问题

- README.md
> docs: readme add codecove

- src/_util/useConfig.ts
- src/config-provider/ConfigContext.tsx
- src/config-provider/ConfigProvider.tsx
- src/config-provider/type.ts
- src/locale/LocalReceiver.ts
- 日常 bug 修复 修复类型错误
- fix(全局配置): 修复TS类型问题
> fix(全局配置): 修复TS类型问题

- package.json
> feat: upgrade icon version

- src/upload/upload.tsx
- [☑️] 日常 bug 修复
https://github.com/Tencent/tdesign-react/issues/578
- fix(组件名称):  Upload
- [ ☑️] 文档已补充或无须补充
- [ ☑️] 代码演示已提供或无须提供
- [ ☑️] TypeScript 定义已补充或无须补充
- [ ☑️] Changelog 已提供或无须提供
> fix: draggable custom theme 同时存在组件不渲染

- src/form/FormItem.tsx
> fix: 修复 formItem 包裹组件 onChange 其他参数丢失问题

- src/upload/type.ts
- src/upload/upload.tsx
> fix(upload): 修复上传参数丢失问题

- src/menu/MenuGroup.tsx
> fix(menu): menuGroup类型修复

- src/select/util/helper.ts
fix #654
#654 
- fix(select): fix multiple tag remove
> fix(select): fix multiple tag remove

- src/form/__tests__/form-list.test.tsx
- src/form/_example/form-list.jsx
无
无
补充如下组件的单测：
Form: 补充 FormList 测试
> test(form): add form FormItem test

- src/dialog/RenderDialog.tsx
解决dialog在destroyOnClose为true时 的问题
解决dialog在destroyOnClose为true时的问题
解决dialog在destroyOnClose为true时 的问题
> fix(dialog): 解决dialog在destroyOnClose为true时 的问题

- src/card/README.md
- src/layout/Layout.tsx
> fix: layout type error

- src/dialog/dialog.md
- src/dialog/type.ts
- fix(dialog): 修复 `alert` 类型错误
> fix: dialog ts error

- CHANGELOG.md
- src/table/hooks/useFixed.ts
- 日常 bug 修复 处理table hooks在node环境中存在`getBoundingClientRect`为null的场景
> fix(table): getBoundingClientRect is null

- src/upload/_example/draggable.jsx
- src/upload/dragger.tsx
- src/upload/type.ts
- src/upload/upload.md
- src/upload/upload.tsx
> fix(upload): onDrop api call

- src/dialog/RenderDialog.tsx
- src/dialog/plugin.tsx
- https://github.com/Tencent/tdesign-react/issues/691
- fix(Dialog): 修复组件销毁后body样式不重置问题 
> fix: 修复 dialog 组件销毁后body样式不重置问题 & 移除多余 div 渲染

- script/rollup.config.js
- tsconfig.json
> feat: 过滤 live demo 代码编译

- src/date-picker/DatePicker.tsx
> fix: 修复 datepicker 空数组确定事件报错问题

- src/pagination/Pagination.tsx
- src/pagination/hooks/usePageNumber.tsx
- src/pagination/hooks/useTotal.tsx
- src/pagination/pagination.md
- src/pagination/type.ts
- src/pagination/usage/props.json
- feat(Pagination): 新增 showPageSize、showPageNumber API
> feat: 新增 showPageSize、showPageNumber API

- src/form/Form.tsx
> fix: 修复 textarea 换行问题

- CHANGELOG.md
- src/common.ts
- src/table/table.md
- src/table/type.ts
> 更新 Table API 文档及 CHANGELOG 说明

- src/slider/Slider.tsx
`value`默认设置为`min`导致非受控模式异常
- fix(slider): 修复`slider`在非受控模式下行为异常
> fix(slider): fix uncontrolled mode can't change value

- src/card/Card.tsx
fix [723](https://github.com/Tencent/tdesign-react/issues/723)
- fix(Card):  修复未添加header属性，Card组件布局错误
> fix: 修复没有header属性时， 样式错误

- src/table/interface.ts
- 日常 bug 修复 Table的`renderExpandedRow`改为非必填
- fix(Table): `renderExpandedRow`改为非必填
> fix(Table)：`renderExpandedRow`改为非必填

- CHANGELOG.md
- package.json
> chore: publish 0.32.3

- site/plugin-tdoc/md-to-react.js
- src/form/form.md
> docs: 完善 Form 文档，添加 FAQ

- CHANGELOG.md
- package.json
- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/base/Table.tsx
- src/date-picker/index.ts
- src/date-picker/panel/DatePickerPanel.tsx
- src/date-picker/panel/DateRangePickerPanel.tsx
- src/date-picker/panel/ExtraContent.tsx
- src/date-picker/panel/PanelContent.tsx
- src/date-picker/panel/useTableData.tsx
> chore: 发布 0.33.0

- CHANGELOG.md
- package.json
> chore: publish 0.33.1

- site/site.config.mjs
> chore: components order

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- src/popup/Popup.tsx
> fix: 修复 datepicker 宽度计算问题

- src/tabs/TabPanel.tsx
- fix(TabPanel): Update TabPanelProps
> update(types): TabPanelProps

- src/form/hooks/useInstance.tsx
> feat: form 支持嵌套数据结构

- CHANGELOG.md
- package.json
> chore: publish

- site/src/App.jsx
- site/src/components/stackblitz/content.js
- site/src/components/stackblitz/index.jsx
> chore: 优化 stackblitz 启动速度

- src/anchor/_example/container.jsx
- 场景：不想在点击的时候在连接上增加锚点信息
- feat(anchor): 演示代码使用 onClick 去阻止默认事件
> feat(anchor): 增加 demo 演示功能

- src/form/FormList.tsx
- src/form/__tests__/form-list.test.tsx
- feat(form): form-list 支持手动赋值
> feat: form-list 支持手动赋值

- src/table/hooks/usePagination.tsx
- https://github.com/Tencent/tdesign-react/issues/711
- fix(Table): 修复异步加载数据时，分页非受控展示错误行数的问题
> fix(table): row num is total when async loading

- src/time-picker/TimePicker.tsx
- src/time-picker/TimeRangePicker.tsx
- fix(TimePicker): 修复`TimePicker`展开宽度问题
> fix(timepicker): popup width

- CHANGELOG.md
- package.json
> feat: publish 0.34.0

- .github/workflows/pr-compressed-size.yml
- src/swiper/style/index.js
- 组件样式/交互改进 替换swiper样式路径
- 关联Common改动 https://github.com/Tencent/tdesign-common/pull/476
> chore: replace swiper style path

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
> fix(datepicker): 修复 popupProps 透传优先级问题

- CHANGELOG.md
- package.json
> chore: 0.34.1

- src/form/defaultProps.ts
> fix: 修复 form-item rules失效问题

- CHANGELOG.md
- package.json
> chore: 0.34.2

- src/form/FormItem.tsx
- src/form/useInitialData.ts
> fix: 修复构建报错

- CHANGELOG.md
- package.json
> chore: 0.34.3

- package.json
- src/loading/plugin.tsx
- https://github.com/Tencent/tdesign-react/issues/803
- fix(Loading): 修复loading plugin类型缺失style和class的问题
> fix(Loading): plugin type

- src/addon/Addon.tsx
> fix: 修复addon 在form表单下数据劫持失败问题

- site/plugin-tdoc/md-to-react.js
> fix: 修复 windows 下usage 路径报错问题

- src/menu/_util/checkMenuType.ts
- src/menu/_util/checkSubMenuChildExpanded.ts
> fix: 兼容 menu 子元素为 null 场景报错问题

- package.json
- site/src/App.jsx
- site/src/main.jsx
- 新特性提交 主题配置生成器
- 关联PR https://github.com/Tencent/tdesign-common/pull/487
- 解决用户自定义组件库主题的困难
- 新增主题配置生成器web component挂件
- feat: 新增主题配置生成器 
> feat: 新增主题配置生成器

- src/card/__tests__/card.test.tsx
> test(card): add card component unit tests

- CHANGELOG.md
- package.json
> chore: publish 0.35.0

- src/table/BaseTable.tsx
- src/table/__tests__/__snapshots__/table.test.tsx.snap
- fix(table): 修复table透传loading size为枚举无效的问题
> fix(table): loading enum size

- package.json
> chore: 移动设备上隐藏主题生成器

- src/common.ts
- src/date-picker/DatePickerPanel.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/date-picker.md
- src/date-picker/defaultProps.ts
- src/date-picker/hooks/useRange.tsx
- src/date-picker/type.ts
> [DatePicker]: 完善 panel 事件逻辑

- src/time-picker/TimePicker.tsx
- src/time-picker/TimeRangePicker.tsx
- src/time-picker/panel/SinglePanel.tsx
- src/time-picker/panel/TimePickerPanel.tsx
- feat(time-picker): 优化滚动方式 首次渲染滚动方式改为`auto`快速完成面板滚动
> feat(timepicker): auto scroll when first mount

- src/skeleton/Skeleton.tsx
> fix(skeleton): skeleton ts type error

- src/anchor/Anchor.tsx
- src/badge/Badge.tsx
- src/collapse/Collapse.tsx
部分组件新增`ref`参数
涉及组件：`Anchor`,`Badge`,`Collapse`
`Anchor` `Badge` `Collapse`新增`ref`属性
> feat(anchor,collapse,badge): add some components ref props

- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useFormat.ts
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useRangeValue.ts
> feat: 优化 datepicker 交互

- src/affix/Affix.tsx
- https://github.com/Tencent/tdesign-react/issues/880
- fix(affix): children类型改为optional
> fix(affix): children is optional

- src/tabs/TabNav.tsx
> fix: 修复 Tabs 左右切换渲染问题

- package.json
> fix: 修复package 缺失字段

- CHANGELOG.md
- package.json
> feat: publish 0.35.1

- site/docs/getting-started.md
> docs: beta release

- src/layout/_example/aside.jsx
- src/layout/_example/combine.jsx
- src/layout/_example/top.jsx
> chore: demo code

- src/select/base/Select.tsx
…acters
https://github.com/Tencent/tdesign-react/issues/906
- fix(Select): 修复输入部分特殊符号过滤时组件崩溃的问题
> fix(select): fix regexp error when filter value contains special characters

- src/range-input/RangeInput.tsx
- src/range-input/RangeInputPopup.tsx
- src/range-input/type.ts
- src/time-picker/type.ts
> fix: 修复 range-input disabled失效问题

- package.json
- site/src/App.jsx
- src/time-picker/style/index.js
> chore: rename tdesign-theme-generator as td-theme-generator

- src/space/Space.tsx
`flex-wrap`属性会导致有`warning`，切换成`flexWrap`修复告警
> fix(space): 修复inline-css导致的react warning问题

- .vscode/settings.json
…info
`vscode`设置新增`code spell`配置 某些属性和框架名称避免认为是警告信息
> style(vscode): add some words to setting.json & avoid plugin warning info

- src/space/space.md
- src/space/type.ts
> feat: 调整 space type

- src/form/FormItem.tsx
> feat: 调整error信息展示 label 字段

- site/site.config.mjs
- src/locale/ja_JP.ts
- src/locale/ko_KR.ts
> feat: 新增日文韩文翻译

- src/upload/types.ts
- src/upload/upload.tsx
> fix: 增加className和style支持

- src/select/__tests__/__snapshots__/select.test.tsx.snap
- src/select/_example/custom-options.jsx
- src/select/base/Option.tsx
- src/select/base/Select.tsx
[Select] Option label 支持 Node 类型
- fix(组件名称): Select
> [Select] Option label support TNode type

- src/watermark/_example/base.jsx
- src/watermark/_example/graylevel.jsx
- src/watermark/_example/image.jsx
- src/watermark/_example/movingImage.jsx
- src/watermark/_example/movingText.jsx
- src/watermark/_example/multiline.jsx
> style(watermark): format example code with prettier

- src/form/formModel.ts
- 
- https://github.com/Tencent/tdesign-react/issues/971
- fix: 修复 number 类型检测错误
> fix: 修复 number 类型检测错误

- script/rollup.config.js
> feat: 支持 reset 样式文件单独构建

- src/table/BaseTable.tsx
- src/table/hooks/useAffix.ts
- fix(table): 表头吸顶显示问题
- fix(table): `paginationAffixedBottom` 支持配置 Affix 组件全部特性
> feat(table): paginationAffixedProps & affixedHeader

- src/form/_example/validator.jsx
- src/form/form.md
- src/form/formModel.ts
- feat(Form): 添加内置校验方法 whitespace
> feat: add whitespace validator

- src/tree-select/defaultProps.ts
- src/tree-select/useTreeSelectUtils.ts
- fix(treeselect):  默认lazy异步加载开启，与api保持一致
> fix(treeselect): 默认lazy异步加载开启

- src/tree/type.ts
> fix: 修复 tree 类型问题

- src/color-picker/components/panel/index.tsx
问题原因：useDefault改为useControlled后，没有加默认值
- fix(colorpicker): 修复最近使用颜色的功能
> fix(colorpicker): 修复最近使用颜色的功能

- CHANGELOG.md
- package.json
> chore: publish 0.36.2

- CHANGELOG.md
- package.json
> chore: publish 0.36.3

- src/date-picker/panel/PanelContent.tsx
- src/time-picker/index.ts
> feat: 调整timepicker 组件导出

- src/dialog/RenderDialog.tsx
- fix(Dialog): 修复 dialog 阻止冒泡导致 popup 无法正常关闭
> fix: 修复 dialog 阻止冒泡导致 popup 无法正常关闭

- src/form/FormList.tsx
- feat(Form): 支持 formList 初始化渲染initialData 数据
> feat: 支持 formList 初始化渲染initialData 数据

- script/generate-usage/config.js
- src/table/_usage/base-table-props.json
- src/table/_usage/index.jsx
- src/table/_usage/primary-table-props.json
> [Table]优化live demo

- src/input/Input.tsx
- fix(Input): 修复在 dialog 内中文输入导致光标定位错误问题
> fix: 修复 input 在 dialog 内中文输入导致光标定位错误问题

- src/button/Button.tsx
- src/button/__tests__/button.test.tsx
> fix: 修复 Button 渲染空字符串样式问题

- src/time-picker/panel/SinglePanel.tsx
> feat: timepicker 兼容node环境运行

- CHANGELOG.md
- package.json
> chore: publish 0.36.4

- src/date-picker/DatePicker.tsx
- feat(DatePicker): 支持面板年月动态响应 value 变化
> feat: 支持面板年月动态响应 value 变化

- src/popconfirm/Popcontent.tsx
> style(popconfirm): popconfirm style

- src/color-picker/components/panel/linear-gradient.tsx
> fix(colorpicker): colorpicker gradient slider

- src/pagination/hooks/usePrevNextJumper.tsx
- fix(Pagination): 修复左右切换禁用失效问题
> fix: 修复 pagination 左右切换禁用问题

- src/pagination/hooks/usePageNumber.tsx
> chore(pagination): remove pagination useless console.log

- src/form/type.ts
> fix: 修复form 类型问题

- src/form/form.md
- src/form/type.ts
> docs: 修复文档问题

- script/rollup.config.js
> chore: 修复 windows 下构建路径问题

- src/table/_example/tree.jsx
- src/table/hooks/tree-store.ts
> 修复树形结构，懒加载顺序问题

- src/table/_example/tree.jsx
- src/table/hooks/tree-store.ts
- feat(table): 树形结构，支持同时添加多个根节点
> feat(table): 树形结构，支持同时添加多个根节点

- src/form/hooks/useInstance.tsx
- src/table/__tests__/__snapshots__/table.test.tsx.snap
> fix: 修复 form validateOnly 报错

- src/select/base/Select.tsx
> fix(select): popupVisble display blank

- src/form/formModel.ts
> fix: 修复 form rule min max 不支持数组校验

- CHANGELOG.md
- package.json
> chore: publish 0.37.0

- CHANGELOG.md
- src/form/formModel.ts
> fix: 修复 form 数字字符串长度校验错误问题

- src/color-picker/_example/panel.jsx
- src/color-picker/components/panel/index.tsx
- src/color-picker/defaultProps.ts
> fix(color-picker): 修复添加颜色受控/非受控不能点击的问题

- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- fix(`DatePicker`): 修复重置日期后面板月份未重置问题
> fix: 修复重置日期后面板月份未重置问题

- src/cascader/hooks.tsx
> chore(Cascader): remove debug log

- src/list/ListItem.tsx
> fix: 修复 listItem 透传 style 问题

- src/date-picker/base/Table.tsx
- src/date-picker/hooks/useFormat.ts
- src/date-picker/panel/RangePanel.tsx
> fix: 修复周选择器禁用时间判断异常

- src/form/FormItem.tsx
> fix: 修复 formItem onchange细节

- src/rate/Rate.tsx
- src/rate/defaultProps.ts
> chore: rate hook

- src/anchor/Anchor.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/hooks/useFormat.ts
- src/date-picker/hooks/useRangeValue.ts
- src/date-picker/hooks/useSingleValue.tsx
- src/dialog/plugin.tsx
- src/form/FormList.tsx
- src/form/hooks/useInstance.tsx
- src/radio/RadioGroup.tsx
- src/switch/Switch.tsx
- src/switch/__tests__/switch.test.tsx
- src/table/FilterController.tsx
- src/table/hooks/useDragSort.ts
- src/tabs/TabBar.tsx
- src/upload/upload.tsx
> fix: 优化全局 error 提示信息

- src/button/button.md
- src/message/message.en-US.md
- src/message/message.md
- src/message/type.ts
> feat: modify API

- src/jumper/Jumper.tsx
https://github.com/Tencent/tdesign-react/issues/1220
> fix(jumper): fix jumper js error when onClick is empty

- src/dialog/_example/attach.jsx
fix: 修复示例拼写错误
fix #1214
- fix(dialog): 修复示例拼写错误
> fix(dialog): fix: 修复示例拼写错误

- src/date-picker/DateRangePicker.tsx
- src/date-picker/base/Header.tsx
- src/date-picker/hooks/useFormat.ts
- src/date-picker/hooks/useRangeValue.ts
- #1208 
- fix(`DatePicker`): 修复面板初始化月份问题
> fix: 修复面板初始化月份问题

- src/dropdown/defaultProps.ts
- src/dropdown/dropdown.en-US.md
- src/dropdown/dropdown.md
- src/dropdown/type.ts
> chore(Dropdown): add dropdown theme API

- src/dropdown/defaultProps.ts
- src/dropdown/dropdown.en-US.md
- src/dropdown/dropdown.md
- src/dropdown/type.ts
- dropdown item新增`theme` API
- dropdown 删除误增加的`theme` API
> chore(dropdown): dropdown item add theme api and remove dropdown theme api

- package.json
- feat(主题生成器): 支持字体相关配置
- feat: 新增字体相关CSS Token，支持通过CSS Token修改字体相关配置 具体请参考 [font tokens](https://github.com/Tencent/tdesign-common/blob/develop/style/web/theme/_font.less)
> feat: font panel generator

- CHANGELOG.md
- package.json
> chore: publish 0.39.0

- package.json
> chore: fix generator version config

- src/config-provider/config-provider.en-US.md
- src/config-provider/config-provider.md
- src/config-provider/type.ts
- src/date-picker/hooks/useTableData.tsx
- feat(`DatePicker`): 支持季度国际化配置
> feat: 支持季度国际化配置

- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
> feat(table): update ts type

- src/date-picker/base/Header.tsx
- feat(`DatePicker`): 支持滚动年份选择器自动加载更多年份
> feat: 支持滚动年份选择器自动加载更多年份

- src/progress/Progress.tsx
允许配置 progress 组件的 style 信息
progress 参数可以配置 style 但是没有处理
- fix(progress): 修复`progress` style属性失效的问题
> Fix(progress): transform style prop

- package.json
add react-is dependence
- fix: 添加 package.json 缺少的依赖，pnpm run dev 无法运行
> fix: 🐛 react-is

- src/table/hooks/useEditableRow.ts
> refactor(table): some little thing

- src/color-picker/ColorPicker.tsx
- src/color-picker/components/trigger.tsx
> fix: 修复 color-picker 受控问题

- src/date-picker/base/Header.tsx
- src/select/base/Select.tsx
> fix: 修复 datepicker 下拉样式问题

- src/cascader/Cascader.tsx
- fix(Cascader): 修复点击清除按钮无法一次性清空所有选项 ([issue #1236](https://github.com/Tencent/tdesign-react/issues/1236))
> fix: cascader tag clear

- src/table/hooks/useColumnResize.tsx
#1284 
1. 添加注释
- fix(table): 宽度计算函数添加注释
> fix(table): 表格宽度计算函数添加注释

- src/date-picker/DateRangePicker.tsx
- src/date-picker/panel/RangePanel.tsx
- fix(`DatePicker`): 修复在左侧输入框聚焦时右侧面板切换月份失效问题
> fix: 修复在左侧输入框聚焦时右侧面板切换月份失效问题

- CHANGELOG.md
- package.json
> chore: publish 0.40.1

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
> fix: 修复点击空白区域输入框被清空问题

- CHANGELOG.md
- package.json
> chore: publish 0.40.2

- src/message/Message.tsx
> fix: message.error theme bugfix

- src/select/_example/panel.jsx
- src/tabs/__tests__/tabs.test.tsx
> chore: 调整 select demo

- CHANGELOG.md
- package.json
> chore: publish 0.40.3

- src/textarea/Textarea.tsx
- src/textarea/textarea.en-US.md
- src/textarea/textarea.md
- src/textarea/type.ts
> fix: 修复 textarea 原生属性类型提示问题

- src/dialog/plugin.tsx
- src/dialog/type.ts
> fix: 修复dialog ts 类型问题

- src/dialog/Dialog.tsx
- src/dialog/RenderDialog.tsx
- src/dialog/_example/base.jsx
- src/dialog/dialog.en-US.md
- src/dialog/dialog.md
- src/dialog/type.ts
[#1376](https://github.com/Tencent/tdesign-vue-next/issues/1376)
feat(dialog): 新增`confirmOnEnter` API
> feat(dialog): 新增confirmOnEnter API

- src/link/__tests__/link.test.tsx
> test(link): add link test

- src/space/Space.tsx
- src/space/__tests__/__snapshots__/space.test.tsx.snap
- src/space/__tests__/space.test.tsx
- src/space/type.ts
> test: 补充 Space 测试

- src/radio/__tests__/__snapshots__/radio.test.tsx.snap
- src/radio/__tests__/radio.test.tsx
https://github.com/Tencent/tdesign-react/issues/1280
- test(radio): add radio test
> test(radio): add radio test

- src/select/base/PopupContent.tsx
- fix(select): 调整loading态显示优先于empty属性
> fix(select): 调整loading态显示优先于empty属性

- package.json
- src/config-provider/config-provider.md
> docs: 优化文档

- src/popup/Popup.tsx
- src/popup/popup.en-US.md
- src/popup/popup.md
- src/popup/type.ts
- src/tooltip/tooltip.en-US.md
- src/tooltip/tooltip.md
- feat(`Popup`): 支持 `overlayInnerClassName`
> feat(`Popup`): 支持 overlayInnerClassName

- src/steps/__tests__/steps.test.tsx
> fix(steps): 删去测试文件中的无用属性

- src/textarea/__tests__/textarea.test.tsx
> test(textarea): add textarea related tests #1280

- .github/workflows/typos-config.toml
> chore: typo thead

- src/config-provider/type.ts
- src/upload/upload.tsx
- fix(Upload): 支持受控使用时`files`可设置为null
- fix(Upload): 修复处理`locale`的`triggerUploadText`的类型问题
> fix(upload): null and type

- src/popup/hooks/useTrigger.tsx
- fix(popup): 修复 popup 显示状态点击页面事件重复触发问题
> fix: 修复 popup 显示状态点击页面事件重复触发问题

- src/popconfirm/_example/describe.jsx
组件【Popconfirm 气泡确认框】样式优化: https://github.com/Tencent/tdesign/issues/191
样式优化
- style(Popconfirm): Popconfirm 样式优化
> style(popconfirm): popconfirm demo style

- src/comment/__tests__/comment.test.tsx
> test(comment): add test

- src/transfer/__tests__/transfer.test.tsx
test(transfer):add transfer tests
[1280](https://github.com/Tencent/tdesign-react/issues/1280?transfer)
test(transfer):add transfer tests
> test(transfer): test(transfer):add transfer tests

- script/generate-usage/config.js
- src/collapse/_usage/index.jsx
- src/message/_example/close-function.jsx
- src/select/_example/base.jsx
- src/select/_example/multiple.jsx
- src/select/base/Option.tsx
- src/select/base/PopupContent.tsx
- fix(select): option设置content未生效问题
- feat(collapse): 增加live demo演示
- [] 本条 PR 不需要纳入 Changelog
> fix(select): option设置content未生效

- package.json
- site/plugin-tdoc/md-to-react.js
> chore: 优化站点 tab 切换滚动条进度体验

- src/dialog/RenderDialog.tsx
- src/dialog/_example/modal.jsx
[#1452](https://github.com/Tencent/tdesign-vue-next/issues/1452)
fix(dialog): 非模态对话框 优化拖拽事件鼠标表现
> fix(dialog): 非模态对话框 优化拖拽事件鼠标表现

- src/collapse/__tests__/collapse.test.tsx
> fix: 修复 collapse 测试问题

- src/image-viewer/__tests__/image-viewer.test.tsx
测试覆盖： https://github.com/Tencent/tdesign-react/issues/1280
- test(ImageViewr): add test
> test(ImageViewer): add test

- src/select/_example/filterable.jsx
https://github.com/Tencent/tdesign-react/issues/1392
- docs(select): fix filterable demo handler
> docs(select): fix filterable demo handler

- src/form/hooks/useInstance.tsx
- fix(`Form`): 兼容 FormItem 未定义字段调用 setFields 方法异常场景
> fix: 兼容 FormItem 未定义字段调用 setFields 方法异常场景

- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/_example/panel.jsx
- src/date-picker/base/Header.tsx
- fix(`DatePicker`): 修复 `onCellClick` 事件失效问题
> fix: 修复 cell-click 事件失效问题

- src/swiper/__tests__/__snapshots__/swiper.test.tsx.snap
- src/swiper/__tests__/swiper.test.tsx
> test(swiper): add swiper tests (#1280)

- src/form/Form.tsx
> fix: 禁用 input 输入框回车自动提交表单

- src/calendar/__tests__/__snapshots__/calendar.test.tsx.snap
- src/calendar/__tests__/calendar.test.tsx
> test(calendar): add test for calendar

- src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
- src/tooltip/__tests__/tooltip.test.tsx
#1280 
- test(Tooltip): 完善单元测试
> test: add test for tooltip

- src/button/Button.tsx
- fix(`Button`): 修复透传 html 属性类型错误
> fix: 修复 button 透传 html 属性类型错误

- src/date-picker/__tests__/__snapshots__/date-picker.test.tsx.snap
- src/time-picker/__tests__/__snapshots__/time-picker.test.tsx.snap
- src/time-picker/panel/SinglePanel.tsx
Reverts Tencent/tdesign-react#1426
> Revert "fix(TimePicker): 修复边界滚动异常问题"

- src/message/Message.tsx
- src/message/useMessageClass.ts
> fix: messagePlugin.xxx support configProvider.classPrefix

- site/src/components/codesandbox/content.js
- site/src/components/stackblitz/content.js
- src/table/hooks/useFixed.ts
> chore: 修复codesanbox 依赖问题

- CHANGELOG.md
- package.json
- src/dropdown/hooks/useDropdownOptions.ts
> chore: publish 0.40.6

- script/generate-usage/config.js
- src/collapse/_usage/index.jsx
- src/tree/_usage/index.jsx
> chore: 修复 tree live demo 问题

- src/dropdown/DropdownMenu.tsx
- src/dropdown/__tests__/__snapshots__/dropdown.test.tsx.snap
- src/dropdown/_example/button.jsx
- src/dropdown/_example/multiple.jsx
- test/ssr/__snapshots__/ssr.test.js.snap
> chore: optmize dropdown demo

- src/dropdown/DropdownMenu.tsx
#1464 
- fix(Dropdown): 修复 value 缺失点击异常
> fix: 修复 dropdown menu 不传 value 点击异常问题

- src/popup/Popup.tsx
- src/popup/hooks/useTrigger.tsx
- src/popup/popup.en-US.md
- src/popup/popup.md
- src/popup/type.ts
- src/tooltip/Tooltip.tsx
- feat(popup): 支持 `popperOptions`、`delay`、`hideEmptyPopup` api
> feat(popup): 支持popperOptions、delay api

- src/date-picker/DateRangePickerPanel.tsx
- src/range-input/RangeInput.tsx
- fix(DatePicker): 修复 cell-click 返回日期错误
> fix: 修复 cell-click 返回日期错误

- src/_util/composeRefs.ts
- src/popconfirm/Popconfirm.tsx
- src/popup/Popup.tsx
- src/popup/hooks/useTrigger.tsx
- src/popup/index.ts
- src/popup/utils/ref.ts
- src/tooltip/Tooltip.tsx
- src/tooltip/index.ts
> fix: 修复 ref 透传丢失属性问题

- src/dialog/__tests__/dialog.test.tsx
"#1280"
#1280 
test(dialog): add dialog tests
> test: dialog tests

- src/tabs/TabBar.tsx
- fix(Tabs): 修复未替换部分classPrefix导致样式异常的问题
> fix(tabs): replace t with classprefix

- src/tree-select/_example/base.jsx
- src/tree/Tree.tsx
- https://github.com/Tencent/tdesign-react/issues/1473
- fix(tree): 修复disabled下不可展开的问题
> fix(tree): enable expand when disabled

- src/select/util/helper.ts
https://github.com/Tencent/tdesign-react/issues/1190
- fix(组件名称): Select
> 当Select组件的Option选项值为布尔值时候，选中没有显示对应的文字

- CHANGELOG.md
- package.json
> chore: publish 0.41.0

- src/image-viewer/ImageViewerMini.tsx
- feat(`ImageViewer`): 适配移动端展示
> feat: 适配移动端展示

- src/tree-select/TreeSelect.tsx
#1460 
- fix(TreeSelect): 修复 data 异步更新，input 值没有及时更新的问题
> fix: 当 data 发生变更时更新 normalizedValue

- src/upload/_example/base.jsx
- src/upload/_example/image.jsx
- src/upload/themes/CustomFile.tsx
- src/upload/themes/DraggerFile.tsx
- src/upload/themes/NormalFile.tsx
- src/upload/type.ts
- src/upload/upload.en-US.md
- src/upload/upload.md
- feat(Upload): 自定义方法 `requestMethod`参数在单文件时文件对象，多文件上传时，是数组文件对象
- feat(Upload): `trigger/dragContent` 参数使用 `files` 而非 `displayFiles`
> 20220914 upload

- CHANGELOG.md
- package.json
> chore: publish 0.41.1

- src/select-input/_example/status.jsx
- src/select-input/_example/width.jsx
- fix(Demos): 修复 `select-input` 示例展示 ([issue #1640](https://github.com/Tencent/tdesign-vue-next/issues/1640)) ([issue #1641](https://github.com/Tencent/tdesign-vue-next/issues/1641))
> fix: select-input demo style

- src/color-picker/components/panel/format/index.tsx
- src/color-picker/components/panel/format/inputs.tsx
- src/hooks/useDebounce.ts
- src/tag-input/useTagList.tsx
> fix: 修复 lodash 全量导入问题

- src/select/base/Select.tsx
- fix(`Select`): 修复透传 tagProps 属性失败问题
>  fix: 修复 select 透传tagProps 属性失败问题

- src/form/Form.tsx
- src/form/FormContext.tsx
- src/form/FormItem.tsx
- src/form/_example/base.jsx
- src/form/form.en-US.md
- src/form/form.md
- src/form/hooks/interface.ts
- src/form/hooks/useForm.ts
- src/form/hooks/useInstance.tsx
- src/form/hooks/useWatch.ts
- src/form/type.ts
- feat(form): form 新增 useWatch hook
> feat(Form): form 新增 useWatch hook

- src/cascader/hooks.tsx
- fix(Cascader): 修复 `options` 动态设置为空失效
> fix: cascader dynamic empty options

- src/notification/NotificationList.tsx
> fix: fix notification style

- src/cascader/components/Item.tsx
- src/common/Check.tsx
> fix(check): 修复非规范属性引起的告警

- src/input-adornment/_example/select.jsx
- src/select/_example/noborder.jsx
- src/select/_usage/props.json
- src/select/base/Select.tsx
- src/select/defaultProps.ts
- src/select/select.en-US.md
- src/select/select.md
- src/select/type.ts
- feat(`Select`): 移除 onVisibleChange、bordered api
> 移除 onVisibleChange、bordered api

- src/date-picker/base/Header.tsx
- src/select-input/SelectInput.tsx
- src/select/base/Select.tsx
- feat(`DatePicker`): 优化动态更新年份滚动交互体验
> feat: 优化动态更新年份滚动交互体验

- CHANGELOG.md
- package.json
> chore: publish 0.42.0

- src/time-picker/panel/SinglePanel.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/1693
- fix(TimePicker): 修复部分场景滚动异常无法选中23:59:59的问题
> fix(timepicker): scroll position on Windows

- site/site.config.mjs
> docs: 修复 link 侧导航文案错误

- src/dropdown/Dropdown.tsx
- fix(Dropdown): 修复点击选项没有触发onVisibleChange的问题
> fix(Dropdown): trigger visibleChange callback when click item

- src/table/THead.tsx
- src/table/hooks/useColumnResize.tsx
- src/table/type.ts
https://github.com/Tencent/tdesign-vue/issues/1348
1. 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度
- feat(table): 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度
> feat(table): 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useSingle.tsx
> fix: 优化 datepicker 输入事件交互

- src/image-viewer/ImageViewerMini.tsx
- src/image-viewer/ImageViewerModel.tsx
- src/image-viewer/__tests__/image-viewer.test.tsx
> style(image-viewer): chore classname

- src/table/BaseTable.tsx
- src/table/EnhancedTable.tsx
- src/table/PrimaryTable.tsx
- src/table/hooks/useTreeData.tsx
- src/table/interface.ts
> feat(table): ts type

- src/card/Card.tsx
- https://github.com/Tencent/tdesign-react/issues/1548
- fix(Card): 修复`shadow` API不生效的问题
> fix(Card): 修复shadow API不生效的问题

- src/upload/_example/base.jsx
- src/upload/hooks/useUpload.ts
- fix(Upload): 添加参数 `response` 到事件 `onSuccess`，单文件是对象，多文件是数组，[tdesign-vue-next#1774](https://github.com/Tencent/tdesign-vue-next/issues/1774)
> fix(upload): add response to onSuccess

- src/select-input/useOverlayInnerStyle.ts
- https://github.com/Tencent/tdesign-react/issues/1523
- feat(Select): 调整下拉交互 允许输入时不关闭下拉面板 减少相关交互问题
> feat(SelectInput): 调整下拉交互 允许输入时不关闭下拉面板 减少相关交互问题

- src/tree-select/TreeSelect.tsx
#1565 
- fix(TreeSelect): 修复 filterable 时，点击 treeselect 闪的问题
> fix(TreeSelect): 修复 filterable 时，点击 treeselect 闪的问题

- src/form/FormItem.tsx
- src/form/FormList.tsx
- fix(Form): 修复 FormList 动态设置节点初始值丢失问题
> fix: 修复 FormList 动态设置节点初始值丢失问题

- src/input/Input.tsx
> fix: 兼容 inputRef 异常情况

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/date-picker.en-US.md
- src/date-picker/date-picker.md
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- src/date-picker/type.ts
- feat(DatePicker): 支持`valueType` API
> feat(DatePicker): support valueType

- src/pagination/Pagination.tsx
> fix: 修复 pagination jumper联动问题

- src/form/Form.tsx
- src/form/FormItem.tsx
- src/form/FormList.tsx
- src/form/hooks/interface.ts
- src/form/hooks/useForm.ts
- fix(`Form`): 修复 `formList` 动态渲染设置数据报错问题
- fix(`Form`): 修复 `getInternalHooks` 警告问题
> fix: 修复 form getInternalHooks 警告问题

- src/collapse/Collapse.tsx
- src/collapse/__tests__/__snapshots__/collapse.test.tsx.snap
- src/collapse/__tests__/collapse.test.tsx
- src/collapse/_example/base.jsx
- src/collapse/_usage/index.jsx
https://github.com/Tencent/tdesign-react/issues/1517
解决两个
1. defaultExpandAll 属性没有生效 ，setState异步问题，采用ref解决
3. 包含form表单的时候样式出现溢出问题，添加overflow 属性解决
> fix(collapse): 1. defaultExpandAll 属性没有生效 2. 包含form表单的时候样式出现溢出问题

- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/hooks/useRange.tsx
> fix: 修复 range 数据格式化异常问题

- src/table/PrimaryTable.tsx
- src/table/TBody.tsx
- src/table/TR.tsx
- src/table/hooks/useDragSort.ts
- fix(Table): 唯一 key 不再和 rowIndex 相加，避免重复问题
- fix(Table): 拖拽排序失效问题，primaryTableRef 丢失
> [table] fix key

- CHANGELOG.md
- package.json
> chore: publish 0.42.3

- src/drawer/Drawer.tsx
- fix(drawer): not need to focus on container when visible is false
> fix(drawer): not need to focus on container when visible is false

- src/input-adornment/_example/select.jsx
[InputAdornment] 设计优化: https://github.com/Tencent/tdesign/issues/217?from_wecom=1
- style(InputAdornment): 样式优化
> style(input-adornment): optimization

- src/select/base/Select.tsx
- src/select/util/helper.ts
- https://github.com/Tencent/tdesign-react/issues/1475
- fix(Select): 修复onChange回调参数缺失问题
> fix(select): onChange callback params

- src/tabs/TabBar.tsx
> Fix/tabs（fix #1583）：修复 activeId 下划线不能跟随内容变动而变化的问题

- src/swiper/Swiper.tsx
当轮播只有一个时，点击左侧按钮后，按钮失效问题
- fix(swiper): 当轮播只有一个时，点击左侧按钮后，按钮失效问题
> fix(swiper): 当轮播只有一个时，点击左侧按钮后，按钮失效问题

- package.json
Co-authored-by: @yilaierwang 
- feat: 主题生成器新增阴影配置 co-authored @yilaierwang
> feat: theme generator add boxshadow panel

- vitest.config.ts
> chore: fix ci

- src/avatar/__tests__/__snapshots__/avatar.test.tsx.snap
- src/avatar/_example/base.jsx
https://github.com/Tencent/tdesign/issues/242?from_wecom=1
> fix: [Avatar]demo中头像类型展示，删除重复头像并调整展示顺序

- src/tabs/Tabs.tsx
- src/tabs/__tests__/tabs.test.tsx
- fix(tabs): support list prop
> feat(tabs): support list prop

- src/input/Input.tsx
> fix: 修复input 限制字符无效问题

- src/popup/hooks/useTrigger.tsx
> fix: 兼容 popup trigger 元素获取异常报错问题

- CHANGELOG.md
- package.json
> chore: publish 0.42.4

- src/cascader/hooks.tsx
- fix(Cascader): 修复出现重复的 `options`
> fix: options repeat

- src/pagination/Pagination.tsx
- src/pagination/pagination.en-US.md
- src/pagination/pagination.md
- src/pagination/type.ts
- src/table/EditableCell.tsx
- src/table/THead.tsx
- src/table/_example/editable-row.jsx
- src/table/_example/pagination.jsx
- src/table/hooks/useColumnResize.tsx
- src/table/hooks/useDragSort.ts
- fix(Table): 提高 `dragSortOptions` 优先级，以便父组件自定义全部参数，[issue#1556](https://github.com/Tencent/tdesign-react/issues/1556)
- fix(Table): 修复可编辑表格，行编辑，数据校验问题，[issue#1514](https://github.com/Tencent/tdesign-react/issues/1514)
- fix(Table): 修复吸顶表头超出省略问题，[tdesign-vue#1639](https://github.com/Tencent/tdesign-vue/issues/1639)
- feat(Pagination): 透传`selectProps` 和 `selectProps.popupProps` 到组件 `Pagination`，以便实现挂载节点等复杂场景需求， [issue#1611](https://github.com/Tencent/tdesign-react/issues/1611)
> [Table] fix validate editable row problem

- src/message/Message.tsx
> fix: message 组件，render container 的逻辑异步化。

- src/form/FormItem.tsx
- src/form/FormList.tsx
> fix: 修复不同 trigger 下校验结果互相覆盖问题

- package.json
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- fix(Datepicker): 修复 `popupProps.onVisibleChange` 方法不能正常触发的问题
> fix: datepicker popupProps onVisibleChange

- src/date-picker/DatePicker.tsx
> fix: 修复单选日期时间无法确定问题

- src/pagination/Pagination.tsx
- src/pagination/__tests__/pagination.test.tsx
- src/popup/_example/container.jsx
- src/popup/_example/dynamic.jsx
- src/popup/_example/visible.jsx
- https://github.com/Tencent/tdesign-react/issues/1648
- fix(Pagination): 修复相同页码也会触发onChange的问题
> fix: 修复分页相同页码触发 onChange 问题

- CHANGELOG.md
- package.json
> chore: publish 0.42.5

- src/form/FormItem.tsx
> fix: 修复提交后 onChange 校验不清除状态问题

- README-zh_CN.md
> chore: add README in English

- src/dropdown/hooks/useDropdownOptions.ts
- https://github.com/Tencent/tdesign-react/issues/1670
- fix(Dropdown): 修复Children变化时没有重新渲染的异常
> fix(dropdown): fix render when children change

- src/popup/_example/style.jsx
- src/select/_example/label-in-value.jsx
- src/select/_example/popup-props.jsx
- src/select/base/Option.tsx
- https://github.com/Tencent/tdesign-react/issues/1643
- https://github.com/Tencent/tdesign-react/issues/1672
- https://github.com/Tencent/tdesign-react/issues/1613
- fix(Select): 修复选项文案过程内容未正确显示的问题
- fix(InputNumber): 修复最小值为0仍可点击减号至-1的问题 @lilonghe
- chore: 优化文档内容及示例代码
> fix(Select): option ellipsis

- src/swiper/Swiper.tsx
fix #1667
https://github.com/Tencent/tdesign-react/issues/1667?from_wecom=1
修改主动控制current的交互和正常保持一致，体现在最后一页切换到第一页时
- fix(swiper): swiper控制current交互和正常保持一致
> fix(swiper): swiper控制current交互和正常保持一致

- src/loading/gradient.tsx
- https://github.com/Tencent/tdesign-react/issues/1692
- fix(Loading): 处理loading在dialog等场景中样式异常的问题
> fix(Loading): fix loading in dialog

- src/dialog/Dialog.tsx
- src/dialog/RenderDialog.tsx
> chore: adjust dialog header structure

- src/tree-select/useTreeSelectPassthoughProps.ts
> feat: 修复 tree-select 浮层样式问题

- src/breadcrumb/BreadcrumbItem.tsx
- src/breadcrumb/_example/icon.jsx
- src/breadcrumb/breadcrumb.en-US.md
- src/breadcrumb/breadcrumb.md
- src/breadcrumb/type.ts
- src/dropdown/style/index.js
- feat(Breadcrumb): 新增`icon` API
- fix(Breadcrumbe): 修复文字省略样式丢失的问题
> feat(breadcrumb): add icon api and fix ellpsis

- src/comment/Comment.tsx
- src/comment/__tests__/comment.test.tsx
- src/comment/_example/list.jsx
- src/comment/_example/operation.jsx
- src/comment/_example/quote.jsx
- src/comment/_example/reply-form.jsx
- src/comment/_example/reply.jsx
- src/popup/hooks/useTrigger.tsx
> feat: 修复 comment 样式问题

- src/input-number/useInputNumber.tsx
- fix(InputNumber): 组件支持受控
```js
import React, { useState } from "react";
import { InputNumber } from "tdesign-react";
export default function InputNumberExample() {
const [minuteValue, setMinuteValue] = useState(0);
const change = (v) => {
setMinuteValue(Math.min(Math.max(0, v)));
};
return (
<InputNumber
value={minuteValue}
theme="column"
onBlur={change}
onChange={change}
/>
);
}
```
> fix(input-number): controlled

- src/image-viewer/ImageViewerMini.tsx
- src/image-viewer/ImageViewerModel.tsx
- src/image-viewer/__tests__/image-viewer.test.tsx
> feat: 修复 image-viewer 样式问题

- src/slider/Slider.tsx
> feat: 修复 slider 样式问题

- src/popup/Popup.tsx
- src/tooltip/Tooltip.tsx
- src/tooltip/defaultProps.ts
- src/tooltip/index.ts
> fix: 修复 tooltip 非受控问题

- src/form/useInitialData.ts
- fix(Form): 修复拦截 checkbox 默认值为 undefined 控制台警告问题
> fix(form): 修复拦截 checkbox 默认值为 undefined 控制台警告问题

- src/button/_example/block.jsx
- src/select-input/useMultiple.tsx
- src/select-input/useSingle.tsx
- src/select/_example/base.jsx
- src/select/_example/filterable.jsx
- src/select/base/Select.tsx
- src/select/hooks/useOptions.ts
- feat(Select): 支持使用Option Children形式时使用过滤等功能
> Feat: Select支持使用Option Children形式时使用过滤等功能

- CHANGELOG.md
- package.json
> chore: publish 0.43.0

- src/select/_example/filterable.jsx
- src/select/base/PopupContent.tsx
- src/select/hooks/useOptions.ts
- feat(select): Select option子组件搜索以label优先 支持复杂children为node节点的搜索
> feat(select): select option子组件搜索以label优先 支持复杂children为node节点的搜索

- src/input-number/_example/center.jsx
- src/input-number/defaultProps.ts
- src/input-number/input-number.en-US.md
- src/input-number/input-number.md
- src/input-number/type.ts
- src/input-number/useInputNumber.tsx
- feat(InputNumber): 支持 `allowInputOverLimit`，用于设置是否允许输入数字超过 `max` `min` 范围的值
- fix(InputNumber): 修复上个版本无法输入小数点问题
> feat(input-number): support allowInputOverLimit

- src/input-number/_example/center.jsx
- src/input-number/useInputNumber.tsx
- feat(InputNumber): 新增和减少按钮支持 `allowInputOverLimit `
> feat(input-number): allowInputOverLimit

- src/table/BaseTable.tsx
- src/table/Cell.tsx
- src/table/EditableCell.tsx
- src/table/TR.tsx
- src/table/hooks/useTreeData.tsx
- refactor(Table): 减少表格渲染次数，[issue#1731](https://github.com/Tencent/tdesign-react/issues/1731)
> refactor(table): reduce render times from 6 to 3

- src/select/_example/custom-options.jsx
- src/select/_example/custom-selected.jsx
- src/select/base/Select.tsx
- https://github.com/Tencent/tdesign-react/issues/1728
- fix(Select): 支持valueDisplay API在单选模式的使用
> feat(Select): 支持valueDisplay API在单选模式的使用

- src/table/BaseTable.tsx
> fix(table): affixedFooter position

- src/select/__tests__/select.test.tsx
- src/table/BaseTable.tsx
> chore: 修复 table 逻辑问题

- src/table/EditableCell.tsx
- fix(Table): 添加依赖到 `onRuleChange`，以保证数据最新
> fix(table): add more dependencies to onRuleChange

- src/popup/Popup.tsx
- src/popup/hooks/useTrigger.tsx
> fix: 修复 delay 无效问题

- CHANGELOG.md
- package.json
> chore: publish 0.43.1

- src/dropdown/DropdownMenu.tsx
> fix(dropdown): 修复 dropdown 不能传 className 和 style 的问题

- package.json
> feat: 添加mitt 依赖

- src/table/TR.tsx
- src/table/hooks/useFixed.ts
https://github.com/Tencent/tdesign-react/issues/1688
- refactor(Table): 减少表格重渲染， #1688
> refactor(table): 减少rerender (#1688)

- src/tooltip/Tooltip.tsx
- src/tooltip/TooltipLite.tsx
- src/tooltip/_example/lite.jsx
- src/tooltip/_example/mouse.jsx
- src/tooltip/tooltip.en-US.md
- src/tooltip/tooltip.md
- src/tooltip/type.ts
- feat(tooltip): 移除placement的mouse模式，该场景请使用TooltipLite
- feat(tooltiplite): placement支持mouse模式，实现原生title体验
> feat(tooltip): placement mouse移入tooltiplite

- script/generate-usage/config.js
- src/card/Card.tsx
- src/card/_usage/index.jsx
fix https://github.com/Tencent/tdesign-react/issues/1660
- fix(Card): 修复 Card 组件 loading 高度塌陷
> fix(card): 修复 Card 组件 loading 高度塌陷和没有 usage 问题

- src/message/Message.tsx
> fix: message.info 在 offset 不存在时 style 生效的缺陷修复

- src/drawer/Drawer.tsx
> fix: 修复 drawer 动画效果

- site/site.config.mjs
- src/auto-complete/AutoComplete.tsx
- src/auto-complete/HighlightOption.tsx
- src/auto-complete/OptionList.tsx
- src/auto-complete/_example/base.jsx
- src/auto-complete/_example/filter.jsx
- src/auto-complete/_example/option.jsx
- src/auto-complete/_example/size.jsx
- src/auto-complete/_example/status.jsx
- src/auto-complete/_example/trigger-element.jsx
- src/auto-complete/auto-complete.en-US.md
- src/auto-complete/auto-complete.md
- src/auto-complete/defaultProps.ts
- src/auto-complete/index.ts
- src/auto-complete/style/css.js
- src/auto-complete/style/index.js
- src/auto-complete/type.ts
- src/hooks/useCommonClassName.ts
- src/index.ts
- feat(AutoComplete): 新增组件 `AutoComplete`
> New Component AutoComplete

- src/cascader/Cascader.tsx
- src/collapse/CollapsePanel.tsx
- src/common/FakeArrow.tsx
- src/select/base/Select.tsx
- src/tree-select/SelectArrow.tsx
> chore: 更改 fake-arrow props

- src/popup/Popup.tsx
fix https://github.com/Tencent/tdesign-react/issues/1768
- fix(Popup): 快速移动鼠标弹出层闪烁
> fix(Popup): 修复移动鼠标弹出层闪烁

- package.json
> fix: 修复icon包升级snapshot报错

- src/dialog/type.ts
fix #1782
- fix(dialog): 修复 dialog instance ts 类型警告
> fix(dialog): 修复 dialog instance ts 类型警告

- src/affix/Affix.tsx
- src/affix/affix.en-US.md
- src/affix/affix.md
- src/affix/type.ts
> feat(affix): 新增 content

- src/_util/dom.ts
- src/anchor/Anchor.tsx
> fix(anchor): container 没有默认值

- src/input-adornment/InputAdornment.tsx
- src/input-adornment/_example/select.jsx
> fix: 修复 inputAdornment 样式

- src/time-picker/TimePicker.tsx
- src/time-picker/TimeRangePicker.tsx
- src/time-picker/_example/hms.jsx
- src/time-picker/defaultProps.ts
- src/time-picker/panel/SinglePanel.tsx
- src/time-picker/panel/TimePickerPanel.tsx
- src/time-picker/time-picker.en-US.md
- src/time-picker/time-picker.md
- src/time-picker/type.ts
- feat(TimePicker): 新增`status`、`tips`和`onPick` API
- fix(TimePicker): 修复打开面板时无法直接清空时间的交互问题
> feat(TimePicker): add status tips and onPick API

- src/input-number/input-number.en-US.md
- src/input-number/input-number.md
- src/input-number/type.ts
- src/input-number/useInputNumber.tsx
- fix(InputNumber): 无法输入小数点后面的第一位数字 `0`，[tdesign-vue-next#2103](https://github.com/Tencent/tdesign-vue-next/issues/2103)
- fix(InputNumber): 修复无法使用清空按钮清除输入数字问题，[issue#1855](https://github.com/Tencent/tdesign-vue/issues/1855)
> fix(input-number): can not clear input number

- CHANGELOG.md
- package.json
> chore: publish 0.44.1

- script/generate-usage/config.js
- src/table/_example/base.jsx
- src/table/_example/custom-cell.jsx
- src/table/_example/custom-col-button.jsx
- src/table/_example/custom-footer.jsx
- src/table/_example/editable-row.jsx
- src/table/_example/expandable.jsx
- src/table/_example/filter-controlled.jsx
- src/table/_example/fixed-header-col.jsx
- src/table/_example/tree.jsx
- src/table/_usage/index.jsx
上一个PR https://github.com/Tencent/tdesign-react/pull/1792
- demo(Table): `table demo` 样式修复
> chore: demo update

- src/common.ts
- src/hooks/useResizeObserver.ts
- src/hooks/useVirtualScroll.ts
- src/table/BaseTable.tsx
- src/table/TBody.tsx
- src/table/TR.tsx
- src/table/_example/tree-select.jsx
- src/table/_example/virtual-scroll.jsx
- src/table/hooks/useLazyLoad.ts
- src/table/hooks/useTreeData.tsx
- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
- feat(Table): 支持任意行高虚拟滚动和树形结构虚拟滚动、支持滚动定位到任意元素
> [Table] Virtual Scroll

- src/form/FormItem.tsx
- src/form/FormList.tsx
- src/form/hooks/useFormItemStyle.tsx
- src/form/hooks/useInstance.tsx
- src/form/utils/index.ts
- fix(Form): 修复 formList 下 error 跳转问题
> fix(form): 修复 formList 下 error 跳转问题

- src/guide/Guide.tsx
fix: https://github.com/Tencent/tdesign-vue-next/issues/2155
fix: https://github.com/Tencent/tdesign-vue-next/issues/2111
issue 对应的 vue-next pr 中有详细的说明，这里做同步修复
- fix(Guide): skip 和 finish 事件正确返回 current；相对元素位置不正确；
> fix(guide)/guide bug

- CHANGELOG.md
- package.json
> chore: publish 0.44.2

- src/input/Input.tsx
- fix(Input): 修复 input 动态宽度计算问题
> fix: 修复 input 动态宽度计算问题

- src/progress/Progress.tsx
> fix: 修复 progress label 展示问题

- src/table/BaseTable.tsx
- src/table/THead.tsx
- fix(Table): 修复固定表头缺少在数据没有溢出时，缺少背景色问题
> fix(table): fixed header missing grey background

- src/table/TR.tsx
- src/table/hooks/useRowExpand.tsx
- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
- feat(Table): 支持设置 `col.stopPropagation` 阻止整列事件冒泡
- fix(Table): 设置展开图标阻止事件冒泡，避免点击展开图标时触发行点击事件，进而触发其他特性
> feat(table): support col stopPropagation

- src/locale/en_US.ts
- src/locale/ja_JP.ts
- src/locale/ko_KR.ts
- src/locale/zh_CN.ts
> chore: fix type check

- src/dropdown/DropdownMenu.tsx
- https://github.com/Tencent/tdesign-react/issues/1785
- fix(Dropdown): 修复多级菜单过长无法选择的问题
> fix(Dropdown): dropdown menu overflow

- .github/CODEOWNERS
- src/tree/TreeItem.tsx
- fix(Tree): 修复叶子节点的label区域无法触发选中的问题
> fix(tree): leaf node label is checkable

- src/tree-select/TreeSelect.tsx
> fix(tree-select): 修复input 宽度展示问题

- src/hooks/useVirtualScroll.ts
- src/table/BaseTable.tsx
- src/table/_example/virtual-scroll.jsx
- fix(Table): 虚拟滚动支持表格高度动态变化，[tdesign-vue-next#1374](https://github.com/Tencent/tdesign-vue-next/issues/1374)
- fix(Table): 修复表格宽度过小时抖动问题
> [Table] virtual scroll support dynamic table height

- src/form/Form.tsx
- src/form/FormList.tsx
- src/form/hooks/interface.ts
- src/form/hooks/useForm.ts
- fix(form): 修复异步渲染 form 组件赋值失败问题
> fix(form): 修复异步渲染 form 组件赋值失败问题

- src/config-provider/config-provider.en-US.md
- src/config-provider/config-provider.md
- src/config-provider/type.ts
- src/guide/Guide.tsx
- src/guide/defaultProps.ts
- src/guide/guide.en-US.md
- src/guide/guide.md
- src/guide/type.ts
`Guide` 部分默认属性通过全局配置获取
- fix(Guide): 部分默认属性通过全局配置获取
> feat(guide): guide global config

- CHANGELOG.md
- package.json
> chore: publish 0.45.0

- src/dialog/dialog.en-US.md
- src/dialog/dialog.md
- src/dialog/type.ts
> chore: 修复 dialog 实例类型

- src/tooltip/TooltipLite.tsx
fix #1836
https://github.com/Tencent/tdesign-react/issues/1836
改变 `position` 位置
- fix(tooltip-lite): 修复层叠上下文样式问题
> fix(tooltip-lite): 修复层叠上下文样式问题

- src/date-picker/base/Header.tsx
- fix(date-picker): 修复年份选择器区间错误
> fix(date-picker): 修复年份选择器区间错误

- src/select/_example/multiple.jsx
- src/select/base/Option.tsx
- src/select/base/PopupContent.tsx
- src/select/base/Select.tsx
- feat(Select): 支持选项`checkAll` 功能
> feat(Select): support checkAll

- CHANGELOG.md
- package.json
- src/drawer/defaultProps.ts
> chore: publish 0.45.1

- src/_util/useLatest.ts
- src/table/hooks/useDragSort.ts
https://github.com/Tencent/tdesign/issues/294
- fix(table): 修正 onDragSort 使用过期变量的问题
> fix(table): 修正 onDragSort 使用过期变量的问题

- src/breadcrumb/BreadcrumbItem.tsx
- src/breadcrumb/_example/base.jsx
> feat(Breadcrumb): 超长文本省略支持悬浮查看完整内容

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
> fix: 修复 datepicker 输入框变化面板未响应问题

- src/image-viewer/ImageViewerMini.tsx
> style(image-viewer): z-index层级调整，修复窗口模式拖拽问题

- src/date-picker/__tests__/date-picker.test.tsx
- src/date-picker/__tests__/date-range-picker.test.tsx
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- src/popup/hooks/useTrigger.tsx
- src/popup/popup.en-US.md
- src/popup/popup.md
- src/popup/type.ts
- fix(`DatePicker`): 修复输入框修改内容面板未响应问题
- feat(`Popup`): 支持 trigger='mousedown' 功能
> feat(popup): 新增 trigger='mousedown' 功能

- src/dialog/Dialog.tsx
- fix(Dialog): 修复 dialog style 透传问题
> fix: 修复 dialog style 透传问题

- src/form/FormItem.tsx
- src/form/formModel.ts
- src/form/hooks/useForm.ts
- https://github.com/Tencent/tdesign-react/issues/1854
- fix(Form): 修复 `unsafe-eval`报错的问题
> fix: 修复 form csp 报错 unsafe-eval

- src/select/base/Select.tsx
- fix(Select): 修复`readonly`状态下可以通过选项的关闭按钮移除选项的问题
> fix(select): tag is not closable when readonly

- CHANGELOG.md
- package.json
> chore: publish 0.45.2

- src/locale/ar_KW.ts
> feat: 支持阿拉伯语言包引入

- src/tree-select/TreeSelect.tsx
> fix: 修复 tree-select value 为 0 无法选中问题

- src/hooks/usePrevious.ts
- src/popup/Popup.tsx
> fix: 修复 popup 滚动事件执行时机问题

- src/message/__tests__/message.test.jsx
([#1280](https://github.com/Tencent/tdesign-react/issues/1280))
- [☑️] 测试用例
[#1280](https://github.com/Tencent/tdesign-react/issues/1280)
> test(message-component): add test for message-component

- src/form/FormList.tsx
- fix(Form): 修复 formList add move 未触发onChange 事件
> fix: 修复 formList add move 未触发onChange 事件

- site/plugin-tdoc/md-to-react.js
> docs: 优化最后更新日期展示

- CHANGELOG.md
> chore: publish 0.45.3

- src/cascader/components/Item.tsx
> fix(cascader): 修复 checkbox 样式丢失
